server:
  port: 8087

spring:
  config:
    import:
      - file:./config/fragments/database.yaml
      - file:./config/fragments/springdoc.yaml
      - file:./config/fragments/rabbitmq.yaml
      - file:./config/fragments/eureka-client.yaml
      - file:./config/fragments/mail.yaml
      - file:./config/fragments/firebase.yaml

database:
  schema: notification

notification:
  url:
    assignment: ${ASSIGNMENT_URL:http://localhost:3000/assignments/%id%}
    submission: ${SUBMISSION_URL:http://localhost:3000/submissions/%id%}
    support-session: ${SUPPORT_SESSION_URL:http://localhost:3000/support/sessions/%id%}
    verification: ${VERIFICATION_URL:http://localhost:3000/verify-email?token=%token%}
    reset-password: ${RESET_PASSWORD_URL:http://localhost:3000/reset-password?token=%token%}
  email:
    from: ${EMAIL_FROM:noreply@apsas.edu.vn}
    from-name: ${EMAIL_FROM_NAME:APSAS System}
