spring:
  application:
    name: support-service

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:h2:mem:support_it;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS support
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: support

  sql:
    init:
      mode: never

eureka:
  client:
    enabled: false

jwt:
  secret: 12345678901234567890123456789012
