# Project
version=dev
# Gradle
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2048m -Xms512m -Dfile.encoding=UTF-8
# Kotlin
kotlin.stdlib.default.dependency=false
# Sonar
sonar.projectKey=apsas-backend
sonar.organization=apsas-test
