modules:
  - sources/shared/security
  - sources/shared/models
  - sources/shared/feign-clients
  - sources/service-registry
  - sources/config-server
  - sources/gateway
  - sources/services/identity
  - sources/services/content
  - sources/services/submission
  - sources/services/evaluation
  - sources/services/support
  - sources/services/notification
  - sources/shared/messaging
  - sources/shared/exception
