// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import {
  contentServiceArchiveAssignmentResponseTransformer,
  contentServiceCreateAssignmentResponseTransformer,
  contentServiceCreateSkillResponseTransformer,
  contentServiceCreateTutorialResponseTransformer,
  contentServiceGetAllAssignmentsResponseTransformer,
  contentServiceGetAllSkillsResponseTransformer,
  contentServiceGetAllTutorialsResponseTransformer,
  contentServiceGetAssignmentByIdResponseTransformer,
  contentServiceGetSkillByIdResponseTransformer,
  contentServiceGetTutorialByIdResponseTransformer,
  contentServicePublishAssignmentResponseTransformer,
  contentServiceUpdateAssignmentResponseTransformer,
  contentServiceUpdateAssignmentScheduleResponseTransformer,
  contentServiceUpdateSkillResponseTransformer,
  contentServiceUpdateTutorialResponseTransformer,
  identityServiceCreateUserResponseTransformer,
  identityServiceGetAllUsersResponseTransformer,
  identityServiceGetCurrentUserResponseTransformer,
  identityServiceGetUserByIdResponseTransformer,
  identityServiceGetUsersByRoleResponseTransformer,
  identityServiceLoginResponseTransformer,
  identityServiceRegisterResponseTransformer,
  identityServiceUpdateCurrentUserProfileResponseTransformer,
  notificationServiceGetPreferencesResponseTransformer,
  notificationServiceGetUserDevicesResponseTransformer,
  notificationServiceRegisterDeviceResponseTransformer,
  notificationServiceUpdatePreferencesResponseTransformer,
  submissionServiceCreateSubmissionResponseTransformer,
  submissionServiceGetAllSubmissionsResponseTransformer,
  submissionServiceGetSubmissionByIdResponseTransformer,
  submissionServiceProvideFeedbackResponseTransformer,
  supportServiceCloseSessionResponseTransformer,
  supportServiceCreateSessionResponseTransformer,
  supportServiceGetSessionByIdResponseTransformer,
  supportServiceListSessionsResponseTransformer,
  supportServiceSendMessageResponseTransformer,
} from "./transformers.gen"
import type {
  ContentServiceArchiveAssignmentData,
  ContentServiceArchiveAssignmentErrors,
  ContentServiceArchiveAssignmentResponses,
  ContentServiceCreateAssignmentData,
  ContentServiceCreateAssignmentErrors,
  ContentServiceCreateAssignmentResponses,
  ContentServiceCreateSkillData,
  ContentServiceCreateSkillErrors,
  ContentServiceCreateSkillResponses,
  ContentServiceCreateTutorialData,
  ContentServiceCreateTutorialErrors,
  ContentServiceCreateTutorialResponses,
  ContentServiceDeleteAssignmentData,
  ContentServiceDeleteAssignmentErrors,
  ContentServiceDeleteAssignmentResponses,
  ContentServiceDeleteSkillData,
  ContentServiceDeleteSkillErrors,
  ContentServiceDeleteSkillResponses,
  ContentServiceDeleteTutorialData,
  ContentServiceDeleteTutorialErrors,
  ContentServiceDeleteTutorialResponses,
  ContentServiceGetAllAssignmentsData,
  ContentServiceGetAllAssignmentsErrors,
  ContentServiceGetAllAssignmentsResponses,
  ContentServiceGetAllSkillsData,
  ContentServiceGetAllSkillsErrors,
  ContentServiceGetAllSkillsResponses,
  ContentServiceGetAllTutorialsData,
  ContentServiceGetAllTutorialsErrors,
  ContentServiceGetAllTutorialsResponses,
  ContentServiceGetAssignmentByIdData,
  ContentServiceGetAssignmentByIdErrors,
  ContentServiceGetAssignmentByIdResponses,
  ContentServiceGetSkillByIdData,
  ContentServiceGetSkillByIdErrors,
  ContentServiceGetSkillByIdResponses,
  ContentServiceGetTutorialByIdData,
  ContentServiceGetTutorialByIdErrors,
  ContentServiceGetTutorialByIdResponses,
  ContentServicePublishAssignmentData,
  ContentServicePublishAssignmentErrors,
  ContentServicePublishAssignmentResponses,
  ContentServiceUpdateAssignmentData,
  ContentServiceUpdateAssignmentErrors,
  ContentServiceUpdateAssignmentResponses,
  ContentServiceUpdateAssignmentScheduleData,
  ContentServiceUpdateAssignmentScheduleErrors,
  ContentServiceUpdateAssignmentScheduleResponses,
  ContentServiceUpdateSkillData,
  ContentServiceUpdateSkillErrors,
  ContentServiceUpdateSkillResponses,
  ContentServiceUpdateTutorialData,
  ContentServiceUpdateTutorialErrors,
  ContentServiceUpdateTutorialResponses,
  EvaluationServiceGetSupportedRuntimesData,
  EvaluationServiceGetSupportedRuntimesErrors,
  EvaluationServiceGetSupportedRuntimesResponses,
  IdentityServiceActivateUserData,
  IdentityServiceActivateUserErrors,
  IdentityServiceActivateUserResponses,
  IdentityServiceChangePasswordData,
  IdentityServiceChangePasswordErrors,
  IdentityServiceChangePasswordResponses,
  IdentityServiceCreateUserData,
  IdentityServiceCreateUserErrors,
  IdentityServiceCreateUserResponses,
  IdentityServiceDeactivateUserData,
  IdentityServiceDeactivateUserErrors,
  IdentityServiceDeactivateUserResponses,
  IdentityServiceDeleteUserData,
  IdentityServiceDeleteUserErrors,
  IdentityServiceDeleteUserResponses,
  IdentityServiceGetAllUsersData,
  IdentityServiceGetAllUsersErrors,
  IdentityServiceGetAllUsersResponses,
  IdentityServiceGetCurrentUserData,
  IdentityServiceGetCurrentUserErrors,
  IdentityServiceGetCurrentUserResponses,
  IdentityServiceGetUserByIdData,
  IdentityServiceGetUserByIdErrors,
  IdentityServiceGetUserByIdResponses,
  IdentityServiceGetUsersByRoleData,
  IdentityServiceGetUsersByRoleErrors,
  IdentityServiceGetUsersByRoleResponses,
  IdentityServiceLoginData,
  IdentityServiceLoginErrors,
  IdentityServiceLoginResponses,
  IdentityServiceRegisterData,
  IdentityServiceRegisterErrors,
  IdentityServiceRegisterResponses,
  IdentityServiceRequestPasswordResetData,
  IdentityServiceRequestPasswordResetErrors,
  IdentityServiceRequestPasswordResetResponses,
  IdentityServiceResendVerificationEmailData,
  IdentityServiceResendVerificationEmailErrors,
  IdentityServiceResendVerificationEmailResponses,
  IdentityServiceResetPasswordData,
  IdentityServiceResetPasswordErrors,
  IdentityServiceResetPasswordResponses,
  IdentityServiceUpdateCurrentUserProfileData,
  IdentityServiceUpdateCurrentUserProfileErrors,
  IdentityServiceUpdateCurrentUserProfileResponses,
  IdentityServiceVerifyEmailData,
  IdentityServiceVerifyEmailErrors,
  IdentityServiceVerifyEmailResponses,
  NotificationServiceGetPreferencesData,
  NotificationServiceGetPreferencesErrors,
  NotificationServiceGetPreferencesResponses,
  NotificationServiceGetUserDevicesData,
  NotificationServiceGetUserDevicesErrors,
  NotificationServiceGetUserDevicesResponses,
  NotificationServiceRegisterDeviceData,
  NotificationServiceRegisterDeviceErrors,
  NotificationServiceRegisterDeviceResponses,
  NotificationServiceRemoveDeviceData,
  NotificationServiceRemoveDeviceErrors,
  NotificationServiceRemoveDeviceResponses,
  NotificationServiceUpdatePreferencesData,
  NotificationServiceUpdatePreferencesErrors,
  NotificationServiceUpdatePreferencesResponses,
  SubmissionServiceCreateSubmissionData,
  SubmissionServiceCreateSubmissionErrors,
  SubmissionServiceCreateSubmissionResponses,
  SubmissionServiceGetAllSubmissionsData,
  SubmissionServiceGetAllSubmissionsErrors,
  SubmissionServiceGetAllSubmissionsResponses,
  SubmissionServiceGetSubmissionByIdData,
  SubmissionServiceGetSubmissionByIdErrors,
  SubmissionServiceGetSubmissionByIdResponses,
  SubmissionServiceProvideFeedbackData,
  SubmissionServiceProvideFeedbackErrors,
  SubmissionServiceProvideFeedbackResponses,
  SupportServiceCloseSessionData,
  SupportServiceCloseSessionErrors,
  SupportServiceCloseSessionResponses,
  SupportServiceCreateSessionData,
  SupportServiceCreateSessionErrors,
  SupportServiceCreateSessionResponses,
  SupportServiceGetSessionByIdData,
  SupportServiceGetSessionByIdErrors,
  SupportServiceGetSessionByIdResponses,
  SupportServiceListSessionsData,
  SupportServiceListSessionsErrors,
  SupportServiceListSessionsResponses,
  SupportServiceSendMessageData,
  SupportServiceSendMessageErrors,
  SupportServiceSendMessageResponses,
} from "./types.gen"

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Lấy tất cả người dùng
 *
 * Lấy danh sách người dùng có phân trang và sắp xếp (chỉ Admin)
 */
export const identityServiceGetAllUsers = <ThrowOnError extends boolean = false>(
  options?: Options<IdentityServiceGetAllUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    IdentityServiceGetAllUsersResponses,
    IdentityServiceGetAllUsersErrors,
    ThrowOnError
  >({
    responseTransformer: identityServiceGetAllUsersResponseTransformer,
    url: "/api/v1/users",
    ...options,
  })
}

/**
 * Tạo người dùng
 *
 * Tạo mới người dùng (chỉ Admin)
 */
export const identityServiceCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceCreateUserData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    IdentityServiceCreateUserResponses,
    IdentityServiceCreateUserErrors,
    ThrowOnError
  >({
    responseTransformer: identityServiceCreateUserResponseTransformer,
    url: "/api/v1/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Vô hiệu hóa người dùng
 *
 * Vô hiệu hóa tài khoản người dùng (chỉ Admin)
 */
export const identityServiceDeactivateUser = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceDeactivateUserData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    IdentityServiceDeactivateUserResponses,
    IdentityServiceDeactivateUserErrors,
    ThrowOnError
  >({
    url: "/api/v1/users/{userId}/deactivate",
    ...options,
  })
}

/**
 * Kích hoạt người dùng
 *
 * Kích hoạt tài khoản người dùng (chỉ Admin)
 */
export const identityServiceActivateUser = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceActivateUserData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    IdentityServiceActivateUserResponses,
    IdentityServiceActivateUserErrors,
    ThrowOnError
  >({
    url: "/api/v1/users/{userId}/activate",
    ...options,
  })
}

/**
 * Đổi mật khẩu
 *
 * Đổi mật khẩu cho người dùng đang đăng nhập
 */
export const identityServiceChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceChangePasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    IdentityServiceChangePasswordResponses,
    IdentityServiceChangePasswordErrors,
    ThrowOnError
  >({
    url: "/api/v1/users/me/change-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Xác thực email
 *
 * Xác thực email người dùng bằng mã token
 */
export const identityServiceVerifyEmail = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceVerifyEmailData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    IdentityServiceVerifyEmailResponses,
    IdentityServiceVerifyEmailErrors,
    ThrowOnError
  >({
    url: "/api/auth/verify-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Đặt lại mật khẩu
 *
 * Đặt lại mật khẩu bằng mã token
 */
export const identityServiceResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceResetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    IdentityServiceResetPasswordResponses,
    IdentityServiceResetPasswordErrors,
    ThrowOnError
  >({
    url: "/api/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Gửi lại email xác thực
 *
 * Gửi lại liên kết xác thực email
 */
export const identityServiceResendVerificationEmail = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceResendVerificationEmailData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    IdentityServiceResendVerificationEmailResponses,
    IdentityServiceResendVerificationEmailErrors,
    ThrowOnError
  >({
    url: "/api/auth/resend-verification",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Đăng ký người dùng mới
 *
 * Đăng ký tài khoản mới với vai trò sinh viên
 */
export const identityServiceRegister = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceRegisterData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceRegisterResponses, IdentityServiceRegisterErrors, ThrowOnError>(
    {
      responseTransformer: identityServiceRegisterResponseTransformer,
      url: "/api/auth/register",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    },
  )
}

/**
 * Đăng nhập
 *
 * Xác thực người dùng và trả về JWT token
 */
export const identityServiceLogin = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceLoginResponses, IdentityServiceLoginErrors, ThrowOnError>({
    responseTransformer: identityServiceLoginResponseTransformer,
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Yêu cầu đặt lại mật khẩu
 *
 * Yêu cầu gửi liên kết đặt lại mật khẩu qua email
 */
export const identityServiceRequestPasswordReset = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceRequestPasswordResetData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    IdentityServiceRequestPasswordResetResponses,
    IdentityServiceRequestPasswordResetErrors,
    ThrowOnError
  >({
    url: "/api/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Lấy hồ sơ người dùng hiện tại
 *
 * Lấy thông tin hồ sơ của người dùng đang đăng nhập
 */
export const identityServiceGetCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<IdentityServiceGetCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    IdentityServiceGetCurrentUserResponses,
    IdentityServiceGetCurrentUserErrors,
    ThrowOnError
  >({
    responseTransformer: identityServiceGetCurrentUserResponseTransformer,
    url: "/api/v1/users/me",
    ...options,
  })
}

/**
 * Cập nhật hồ sơ người dùng
 *
 * Cập nhật thông tin hồ sơ của người dùng đang đăng nhập
 */
export const identityServiceUpdateCurrentUserProfile = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceUpdateCurrentUserProfileData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    IdentityServiceUpdateCurrentUserProfileResponses,
    IdentityServiceUpdateCurrentUserProfileErrors,
    ThrowOnError
  >({
    responseTransformer: identityServiceUpdateCurrentUserProfileResponseTransformer,
    url: "/api/v1/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Xóa người dùng
 *
 * Xóa tài khoản người dùng (chỉ Admin)
 */
export const identityServiceDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    IdentityServiceDeleteUserResponses,
    IdentityServiceDeleteUserErrors,
    ThrowOnError
  >({
    url: "/api/v1/users/{userId}",
    ...options,
  })
}

/**
 * Lấy người dùng theo ID
 *
 * Lấy thông tin người dùng theo ID (chỉ Admin và Giảng viên)
 */
export const identityServiceGetUserById = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceGetUserByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    IdentityServiceGetUserByIdResponses,
    IdentityServiceGetUserByIdErrors,
    ThrowOnError
  >({
    responseTransformer: identityServiceGetUserByIdResponseTransformer,
    url: "/api/v1/users/{userId}",
    ...options,
  })
}

/**
 * Lấy người dùng theo vai trò
 *
 * Lấy danh sách người dùng theo vai trò có phân trang và sắp xếp (chỉ Admin và Giảng viên)
 */
export const identityServiceGetUsersByRole = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceGetUsersByRoleData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    IdentityServiceGetUsersByRoleResponses,
    IdentityServiceGetUsersByRoleErrors,
    ThrowOnError
  >({
    responseTransformer: identityServiceGetUsersByRoleResponseTransformer,
    url: "/api/v1/users/role/{role}",
    ...options,
  })
}

/**
 * Lấy tất cả hướng dẫn
 *
 * Lấy danh sách hướng dẫn có phân trang và sắp xếp
 */
export const contentServiceGetAllTutorials = <ThrowOnError extends boolean = false>(
  options?: Options<ContentServiceGetAllTutorialsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ContentServiceGetAllTutorialsResponses,
    ContentServiceGetAllTutorialsErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceGetAllTutorialsResponseTransformer,
    url: "/api/v1/tutorials",
    ...options,
  })
}

/**
 * Tạo hướng dẫn mới
 *
 * Tạo mới hướng dẫn (chỉ Content Provider)
 */
export const contentServiceCreateTutorial = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceCreateTutorialData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContentServiceCreateTutorialResponses,
    ContentServiceCreateTutorialErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceCreateTutorialResponseTransformer,
    url: "/api/v1/tutorials",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Lấy tất cả kỹ năng
 *
 * Lấy danh sách kỹ năng có phân trang và sắp xếp
 */
export const contentServiceGetAllSkills = <ThrowOnError extends boolean = false>(
  options?: Options<ContentServiceGetAllSkillsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ContentServiceGetAllSkillsResponses,
    ContentServiceGetAllSkillsErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceGetAllSkillsResponseTransformer,
    url: "/api/v1/skills",
    ...options,
  })
}

/**
 * Tạo kỹ năng mới
 *
 * Tạo mới kỹ năng (chỉ Content Provider)
 */
export const contentServiceCreateSkill = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceCreateSkillData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContentServiceCreateSkillResponses,
    ContentServiceCreateSkillErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceCreateSkillResponseTransformer,
    url: "/api/v1/skills",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Lấy tất cả bài tập
 *
 * Lấy danh sách bài tập có phân trang và sắp xếp
 */
export const contentServiceGetAllAssignments = <ThrowOnError extends boolean = false>(
  options?: Options<ContentServiceGetAllAssignmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ContentServiceGetAllAssignmentsResponses,
    ContentServiceGetAllAssignmentsErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceGetAllAssignmentsResponseTransformer,
    url: "/api/v1/assignments",
    ...options,
  })
}

/**
 * Tạo bài tập mới
 *
 * Tạo mới bài tập (chỉ Content Provider)
 */
export const contentServiceCreateAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceCreateAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContentServiceCreateAssignmentResponses,
    ContentServiceCreateAssignmentErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceCreateAssignmentResponseTransformer,
    url: "/api/v1/assignments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Xuất bản bài tập
 *
 * Xuất bản bài tập nháp (chỉ Content Provider)
 */
export const contentServicePublishAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServicePublishAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContentServicePublishAssignmentResponses,
    ContentServicePublishAssignmentErrors,
    ThrowOnError
  >({
    responseTransformer: contentServicePublishAssignmentResponseTransformer,
    url: "/api/v1/assignments/{id}/publish",
    ...options,
  })
}

/**
 * Lưu trữ bài tập
 *
 * Lưu trữ bài tập (chỉ Content Provider)
 */
export const contentServiceArchiveAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceArchiveAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    ContentServiceArchiveAssignmentResponses,
    ContentServiceArchiveAssignmentErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceArchiveAssignmentResponseTransformer,
    url: "/api/v1/assignments/{id}/archive",
    ...options,
  })
}

/**
 * Xóa hướng dẫn
 *
 * Xóa hướng dẫn (chỉ Content Provider)
 */
export const contentServiceDeleteTutorial = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceDeleteTutorialData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    ContentServiceDeleteTutorialResponses,
    ContentServiceDeleteTutorialErrors,
    ThrowOnError
  >({
    url: "/api/v1/tutorials/{id}",
    ...options,
  })
}

/**
 * Lấy hướng dẫn theo ID
 *
 * Lấy chi tiết hướng dẫn theo ID
 */
export const contentServiceGetTutorialById = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceGetTutorialByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ContentServiceGetTutorialByIdResponses,
    ContentServiceGetTutorialByIdErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceGetTutorialByIdResponseTransformer,
    url: "/api/v1/tutorials/{id}",
    ...options,
  })
}

/**
 * Cập nhật hướng dẫn
 *
 * Cập nhật thông tin hướng dẫn (chỉ Content Provider)
 */
export const contentServiceUpdateTutorial = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceUpdateTutorialData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    ContentServiceUpdateTutorialResponses,
    ContentServiceUpdateTutorialErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceUpdateTutorialResponseTransformer,
    url: "/api/v1/tutorials/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Xóa kỹ năng
 *
 * Xóa kỹ năng (chỉ Content Provider)
 */
export const contentServiceDeleteSkill = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceDeleteSkillData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    ContentServiceDeleteSkillResponses,
    ContentServiceDeleteSkillErrors,
    ThrowOnError
  >({
    url: "/api/v1/skills/{id}",
    ...options,
  })
}

/**
 * Lấy kỹ năng theo ID
 *
 * Lấy chi tiết kỹ năng theo ID
 */
export const contentServiceGetSkillById = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceGetSkillByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ContentServiceGetSkillByIdResponses,
    ContentServiceGetSkillByIdErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceGetSkillByIdResponseTransformer,
    url: "/api/v1/skills/{id}",
    ...options,
  })
}

/**
 * Cập nhật kỹ năng
 *
 * Cập nhật thông tin kỹ năng (chỉ Content Provider)
 */
export const contentServiceUpdateSkill = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceUpdateSkillData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    ContentServiceUpdateSkillResponses,
    ContentServiceUpdateSkillErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceUpdateSkillResponseTransformer,
    url: "/api/v1/skills/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Xóa bài tập
 *
 * Xóa bài tập (chỉ Content Provider)
 */
export const contentServiceDeleteAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceDeleteAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    ContentServiceDeleteAssignmentResponses,
    ContentServiceDeleteAssignmentErrors,
    ThrowOnError
  >({
    url: "/api/v1/assignments/{id}",
    ...options,
  })
}

/**
 * Lấy bài tập theo ID
 *
 * Lấy chi tiết bài tập theo ID
 */
export const contentServiceGetAssignmentById = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceGetAssignmentByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    ContentServiceGetAssignmentByIdResponses,
    ContentServiceGetAssignmentByIdErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceGetAssignmentByIdResponseTransformer,
    url: "/api/v1/assignments/{id}",
    ...options,
  })
}

/**
 * Cập nhật bài tập
 *
 * Cập nhật thông tin bài tập (chỉ Content Provider)
 */
export const contentServiceUpdateAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceUpdateAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    ContentServiceUpdateAssignmentResponses,
    ContentServiceUpdateAssignmentErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceUpdateAssignmentResponseTransformer,
    url: "/api/v1/assignments/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Cập nhật lịch bài tập
 *
 * Cập nhật lịch bài tập (start_date, due_date) (chỉ Giảng viên)
 */
export const contentServiceUpdateAssignmentSchedule = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceUpdateAssignmentScheduleData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    ContentServiceUpdateAssignmentScheduleResponses,
    ContentServiceUpdateAssignmentScheduleErrors,
    ThrowOnError
  >({
    responseTransformer: contentServiceUpdateAssignmentScheduleResponseTransformer,
    url: "/api/v1/assignments/{id}/schedule",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Lấy tất cả bài nộp
 *
 * Lấy danh sách bài nộp với phân trang và sắp xếp. Sinh viên chỉ xem bài của mình, giảng viên có thể lọc theo bài tập và sinh viên.
 */
export const submissionServiceGetAllSubmissions = <ThrowOnError extends boolean = false>(
  options?: Options<SubmissionServiceGetAllSubmissionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SubmissionServiceGetAllSubmissionsResponses,
    SubmissionServiceGetAllSubmissionsErrors,
    ThrowOnError
  >({
    responseTransformer: submissionServiceGetAllSubmissionsResponseTransformer,
    url: "/api/v1/submissions",
    ...options,
  })
}

/**
 * Tạo bài nộp mới
 *
 * Nộp bài giải cho một bài tập (chỉ sinh viên)
 */
export const submissionServiceCreateSubmission = <ThrowOnError extends boolean = false>(
  options: Options<SubmissionServiceCreateSubmissionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SubmissionServiceCreateSubmissionResponses,
    SubmissionServiceCreateSubmissionErrors,
    ThrowOnError
  >({
    responseTransformer: submissionServiceCreateSubmissionResponseTransformer,
    url: "/api/v1/submissions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Thêm nhận xét cho bài nộp
 *
 * Thêm nhận xét của giảng viên cho bài nộp (chỉ giảng viên)
 */
export const submissionServiceProvideFeedback = <ThrowOnError extends boolean = false>(
  options: Options<SubmissionServiceProvideFeedbackData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SubmissionServiceProvideFeedbackResponses,
    SubmissionServiceProvideFeedbackErrors,
    ThrowOnError
  >({
    responseTransformer: submissionServiceProvideFeedbackResponseTransformer,
    url: "/api/v1/submissions/{id}/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Lấy bài nộp theo ID
 *
 * Lấy chi tiết bài nộp theo ID. Sinh viên chỉ xem bài của mình, giảng viên xem được tất cả.
 */
export const submissionServiceGetSubmissionById = <ThrowOnError extends boolean = false>(
  options: Options<SubmissionServiceGetSubmissionByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    SubmissionServiceGetSubmissionByIdResponses,
    SubmissionServiceGetSubmissionByIdErrors,
    ThrowOnError
  >({
    responseTransformer: submissionServiceGetSubmissionByIdResponseTransformer,
    url: "/api/v1/submissions/{id}",
    ...options,
  })
}

/**
 * Lấy danh sách runtime hỗ trợ
 *
 * Trả về danh sách tất cả ngôn ngữ lập trình và phiên bản được hỗ trợ
 */
export const evaluationServiceGetSupportedRuntimes = <ThrowOnError extends boolean = false>(
  options?: Options<EvaluationServiceGetSupportedRuntimesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    EvaluationServiceGetSupportedRuntimesResponses,
    EvaluationServiceGetSupportedRuntimesErrors,
    ThrowOnError
  >({
    url: "/api/v1/runtimes",
    ...options,
  })
}

/**
 * Liệt kê các phiên hỗ trợ
 *
 * Giảng viên xem tất cả phiên, sinh viên chỉ xem phiên của mình
 */
export const supportServiceListSessions = <ThrowOnError extends boolean = false>(
  options?: Options<SupportServiceListSessionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    SupportServiceListSessionsResponses,
    SupportServiceListSessionsErrors,
    ThrowOnError
  >({
    responseTransformer: supportServiceListSessionsResponseTransformer,
    url: "/api/v1/support/sessions",
    ...options,
  })
}

/**
 * Tạo phiên hỗ trợ mới
 *
 * Sinh viên có thể tạo phiên hỗ trợ mới
 */
export const supportServiceCreateSession = <ThrowOnError extends boolean = false>(
  options: Options<SupportServiceCreateSessionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SupportServiceCreateSessionResponses,
    SupportServiceCreateSessionErrors,
    ThrowOnError
  >({
    responseTransformer: supportServiceCreateSessionResponseTransformer,
    url: "/api/v1/support/sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Gửi tin nhắn trong phiên hỗ trợ
 *
 * Gửi tin nhắn trong một phiên hỗ trợ
 */
export const supportServiceSendMessage = <ThrowOnError extends boolean = false>(
  options: Options<SupportServiceSendMessageData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SupportServiceSendMessageResponses,
    SupportServiceSendMessageErrors,
    ThrowOnError
  >({
    responseTransformer: supportServiceSendMessageResponseTransformer,
    url: "/api/v1/support/sessions/{sessionId}/messages",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Đóng phiên hỗ trợ
 *
 * Chỉ sinh viên tạo phiên mới được đóng phiên
 */
export const supportServiceCloseSession = <ThrowOnError extends boolean = false>(
  options: Options<SupportServiceCloseSessionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SupportServiceCloseSessionResponses,
    SupportServiceCloseSessionErrors,
    ThrowOnError
  >({
    responseTransformer: supportServiceCloseSessionResponseTransformer,
    url: "/api/v1/support/sessions/{sessionId}/close",
    ...options,
  })
}

/**
 * Xem chi tiết phiên hỗ trợ
 *
 * Giảng viên xem mọi phiên, sinh viên chỉ xem phiên của mình
 */
export const supportServiceGetSessionById = <ThrowOnError extends boolean = false>(
  options: Options<SupportServiceGetSessionByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    SupportServiceGetSessionByIdResponses,
    SupportServiceGetSessionByIdErrors,
    ThrowOnError
  >({
    responseTransformer: supportServiceGetSessionByIdResponseTransformer,
    url: "/api/v1/support/sessions/{sessionId}",
    ...options,
  })
}

/**
 * Đăng ký token thiết bị FCM
 *
 * Đăng ký token thiết bị Firebase Cloud Messaging để nhận thông báo đẩy
 */
export const notificationServiceRegisterDevice = <ThrowOnError extends boolean = false>(
  options: Options<NotificationServiceRegisterDeviceData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    NotificationServiceRegisterDeviceResponses,
    NotificationServiceRegisterDeviceErrors,
    ThrowOnError
  >({
    responseTransformer: notificationServiceRegisterDeviceResponseTransformer,
    url: "/api/v1/devices/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Lấy tùy chọn thông báo
 *
 * Lấy tùy chọn nhận thông báo của người dùng hiện tại
 */
export const notificationServiceGetPreferences = <ThrowOnError extends boolean = false>(
  options?: Options<NotificationServiceGetPreferencesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    NotificationServiceGetPreferencesResponses,
    NotificationServiceGetPreferencesErrors,
    ThrowOnError
  >({
    responseTransformer: notificationServiceGetPreferencesResponseTransformer,
    url: "/api/v1/preferences",
    ...options,
  })
}

/**
 * Cập nhật tùy chọn thông báo
 *
 * Cập nhật tùy chọn nhận thông báo của người dùng hiện tại
 */
export const notificationServiceUpdatePreferences = <ThrowOnError extends boolean = false>(
  options: Options<NotificationServiceUpdatePreferencesData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<
    NotificationServiceUpdatePreferencesResponses,
    NotificationServiceUpdatePreferencesErrors,
    ThrowOnError
  >({
    responseTransformer: notificationServiceUpdatePreferencesResponseTransformer,
    url: "/api/v1/preferences",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Lấy danh sách thiết bị
 *
 * Lấy tất cả thiết bị đã đăng ký của người dùng hiện tại
 */
export const notificationServiceGetUserDevices = <ThrowOnError extends boolean = false>(
  options?: Options<NotificationServiceGetUserDevicesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    NotificationServiceGetUserDevicesResponses,
    NotificationServiceGetUserDevicesErrors,
    ThrowOnError
  >({
    responseTransformer: notificationServiceGetUserDevicesResponseTransformer,
    url: "/api/v1/devices",
    ...options,
  })
}

/**
 * Xóa token thiết bị
 *
 * Xóa token thiết bị FCM đã đăng ký
 */
export const notificationServiceRemoveDevice = <ThrowOnError extends boolean = false>(
  options: Options<NotificationServiceRemoveDeviceData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<
    NotificationServiceRemoveDeviceResponses,
    NotificationServiceRemoveDeviceErrors,
    ThrowOnError
  >({
    url: "/api/v1/devices/{token}",
    ...options,
  })
}
