// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import {
  contentServiceArchiveAssignmentResponseTransformer,
  contentServiceCreateAssignmentResponseTransformer,
  contentServiceCreateSkillResponseTransformer,
  contentServiceCreateTutorialResponseTransformer,
  contentServiceGetAllAssignmentsResponseTransformer,
  contentServiceGetAllSkillsResponseTransformer,
  contentServiceGetAllTutorialsResponseTransformer,
  contentServiceGetAssignmentByIdResponseTransformer,
  contentServiceGetSkillByIdResponseTransformer,
  contentServiceGetTutorialByIdResponseTransformer,
  contentServicePublishAssignmentResponseTransformer,
  contentServiceUpdateAssignmentResponseTransformer,
  contentServiceUpdateAssignmentScheduleResponseTransformer,
  contentServiceUpdateSkillResponseTransformer,
  contentServiceUpdateTutorialResponseTransformer,
  identityServiceCreateUserResponseTransformer,
  identityServiceGetAllUsersResponseTransformer,
  identityServiceGetCurrentUserResponseTransformer,
  identityServiceGetUserByIdResponseTransformer,
  identityServiceGetUsersByRoleResponseTransformer,
  identityServiceLoginResponseTransformer,
  identityServiceRegisterResponseTransformer,
  identityServiceUpdateCurrentUserProfileResponseTransformer,
  submissionServiceCreateSubmissionResponseTransformer,
  submissionServiceGetAllSubmissionsResponseTransformer,
  submissionServiceGetSubmissionByIdResponseTransformer,
  submissionServiceProvideFeedbackResponseTransformer,
  supportServiceCloseSessionResponseTransformer,
  supportServiceCreateSessionResponseTransformer,
  supportServiceGetSessionByIdResponseTransformer,
  supportServiceListSessionsResponseTransformer,
} from "./transformers.gen"
import type {
  ContentServiceArchiveAssignmentData,
  ContentServiceArchiveAssignmentResponses,
  ContentServiceCreateAssignmentData,
  ContentServiceCreateAssignmentResponses,
  ContentServiceCreateSkillData,
  ContentServiceCreateSkillResponses,
  ContentServiceCreateTutorialData,
  ContentServiceCreateTutorialResponses,
  ContentServiceDeleteAssignmentData,
  ContentServiceDeleteAssignmentResponses,
  ContentServiceDeleteSkillData,
  ContentServiceDeleteSkillResponses,
  ContentServiceDeleteTutorialData,
  ContentServiceDeleteTutorialResponses,
  ContentServiceGetAllAssignmentsData,
  ContentServiceGetAllAssignmentsResponses,
  ContentServiceGetAllSkillsData,
  ContentServiceGetAllSkillsResponses,
  ContentServiceGetAllTutorialsData,
  ContentServiceGetAllTutorialsResponses,
  ContentServiceGetAssignmentByIdData,
  ContentServiceGetAssignmentByIdResponses,
  ContentServiceGetSkillByIdData,
  ContentServiceGetSkillByIdResponses,
  ContentServiceGetTutorialByIdData,
  ContentServiceGetTutorialByIdResponses,
  ContentServicePublishAssignmentData,
  ContentServicePublishAssignmentResponses,
  ContentServiceUpdateAssignmentData,
  ContentServiceUpdateAssignmentResponses,
  ContentServiceUpdateAssignmentScheduleData,
  ContentServiceUpdateAssignmentScheduleResponses,
  ContentServiceUpdateSkillData,
  ContentServiceUpdateSkillResponses,
  ContentServiceUpdateTutorialData,
  ContentServiceUpdateTutorialResponses,
  EvaluationServiceGetSupportedRuntimesData,
  EvaluationServiceGetSupportedRuntimesErrors,
  EvaluationServiceGetSupportedRuntimesResponses,
  IdentityServiceActivateUserData,
  IdentityServiceActivateUserResponses,
  IdentityServiceChangePasswordData,
  IdentityServiceChangePasswordResponses,
  IdentityServiceCreateUserData,
  IdentityServiceCreateUserResponses,
  IdentityServiceDeactivateUserData,
  IdentityServiceDeactivateUserResponses,
  IdentityServiceDeleteUserData,
  IdentityServiceDeleteUserResponses,
  IdentityServiceGetAllUsersData,
  IdentityServiceGetAllUsersResponses,
  IdentityServiceGetCurrentUserData,
  IdentityServiceGetCurrentUserResponses,
  IdentityServiceGetUserByIdData,
  IdentityServiceGetUserByIdResponses,
  IdentityServiceGetUsersByRoleData,
  IdentityServiceGetUsersByRoleResponses,
  IdentityServiceLoginData,
  IdentityServiceLoginResponses,
  IdentityServiceRegisterData,
  IdentityServiceRegisterResponses,
  IdentityServiceRequestPasswordResetData,
  IdentityServiceRequestPasswordResetResponses,
  IdentityServiceResendVerificationEmailData,
  IdentityServiceResendVerificationEmailResponses,
  IdentityServiceResetPasswordData,
  IdentityServiceResetPasswordResponses,
  IdentityServiceUpdateCurrentUserProfileData,
  IdentityServiceUpdateCurrentUserProfileResponses,
  IdentityServiceVerifyEmailData,
  IdentityServiceVerifyEmailResponses,
  SubmissionServiceCreateSubmissionData,
  SubmissionServiceCreateSubmissionResponses,
  SubmissionServiceGetAllSubmissionsData,
  SubmissionServiceGetAllSubmissionsResponses,
  SubmissionServiceGetSubmissionByIdData,
  SubmissionServiceGetSubmissionByIdResponses,
  SubmissionServiceProvideFeedbackData,
  SubmissionServiceProvideFeedbackResponses,
  SupportServiceCloseSessionData,
  SupportServiceCloseSessionErrors,
  SupportServiceCloseSessionResponses,
  SupportServiceCreateSessionData,
  SupportServiceCreateSessionErrors,
  SupportServiceCreateSessionResponses,
  SupportServiceGetSessionByIdData,
  SupportServiceGetSessionByIdErrors,
  SupportServiceGetSessionByIdResponses,
  SupportServiceListSessionsData,
  SupportServiceListSessionsResponses,
} from "./types.gen"
import {
  zContentServiceArchiveAssignmentData,
  zContentServiceCreateAssignmentData,
  zContentServiceCreateSkillData,
  zContentServiceCreateTutorialData,
  zContentServiceDeleteAssignmentData,
  zContentServiceDeleteSkillData,
  zContentServiceDeleteTutorialData,
  zContentServiceGetAllAssignmentsData,
  zContentServiceGetAllSkillsData,
  zContentServiceGetAllTutorialsData,
  zContentServiceGetAssignmentByIdData,
  zContentServiceGetSkillByIdData,
  zContentServiceGetTutorialByIdData,
  zContentServicePublishAssignmentData,
  zContentServiceUpdateAssignmentData,
  zContentServiceUpdateAssignmentScheduleData,
  zContentServiceUpdateSkillData,
  zContentServiceUpdateTutorialData,
  zEvaluationServiceGetSupportedRuntimesData,
  zIdentityServiceActivateUserData,
  zIdentityServiceChangePasswordData,
  zIdentityServiceCreateUserData,
  zIdentityServiceDeactivateUserData,
  zIdentityServiceDeleteUserData,
  zIdentityServiceGetAllUsersData,
  zIdentityServiceGetCurrentUserData,
  zIdentityServiceGetUserByIdData,
  zIdentityServiceGetUsersByRoleData,
  zIdentityServiceLoginData,
  zIdentityServiceRegisterData,
  zIdentityServiceRequestPasswordResetData,
  zIdentityServiceResendVerificationEmailData,
  zIdentityServiceResetPasswordData,
  zIdentityServiceUpdateCurrentUserProfileData,
  zIdentityServiceVerifyEmailData,
  zSubmissionServiceCreateSubmissionData,
  zSubmissionServiceGetAllSubmissionsData,
  zSubmissionServiceGetSubmissionByIdData,
  zSubmissionServiceProvideFeedbackData,
  zSupportServiceCloseSessionData,
  zSupportServiceCreateSessionData,
  zSupportServiceGetSessionByIdData,
  zSupportServiceListSessionsData,
} from "./zod.gen"

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Deactivate user
 * Deactivate a user account (Admin only)
 */
export const identityServiceDeactivateUser = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceDeactivateUserData, ThrowOnError>,
) => {
  return (options.client ?? client).put<IdentityServiceDeactivateUserResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceDeactivateUserData.parseAsync(data)
    },
    url: "/api/v1/users/{userId}/deactivate",
    ...options,
  })
}

/**
 * Activate user
 * Activate a user account (Admin only)
 */
export const identityServiceActivateUser = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceActivateUserData, ThrowOnError>,
) => {
  return (options.client ?? client).put<IdentityServiceActivateUserResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceActivateUserData.parseAsync(data)
    },
    url: "/api/v1/users/{userId}/activate",
    ...options,
  })
}

/**
 * Get current user profile
 * Get the profile of the currently authenticated user
 */
export const identityServiceGetCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<IdentityServiceGetCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<IdentityServiceGetCurrentUserResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceGetCurrentUserData.parseAsync(data)
    },
    responseTransformer: identityServiceGetCurrentUserResponseTransformer,
    url: "/api/v1/users/me",
    ...options,
  })
}

/**
 * Update current user profile
 * Update the profile of the currently authenticated user
 */
export const identityServiceUpdateCurrentUserProfile = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceUpdateCurrentUserProfileData, ThrowOnError>,
) => {
  return (options.client ?? client).put<IdentityServiceUpdateCurrentUserProfileResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceUpdateCurrentUserProfileData.parseAsync(data)
    },
    responseTransformer: identityServiceUpdateCurrentUserProfileResponseTransformer,
    url: "/api/v1/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Get all users
 * Get all users with pagination and sorting (Admin only)
 */
export const identityServiceGetAllUsers = <ThrowOnError extends boolean = false>(
  options?: Options<IdentityServiceGetAllUsersData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<IdentityServiceGetAllUsersResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceGetAllUsersData.parseAsync(data)
    },
    responseTransformer: identityServiceGetAllUsersResponseTransformer,
    url: "/api/v1/users",
    ...options,
  })
}

/**
 * Create user
 * Create a new user (Admin only)
 */
export const identityServiceCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceCreateUserData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceCreateUserResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceCreateUserData.parseAsync(data)
    },
    responseTransformer: identityServiceCreateUserResponseTransformer,
    url: "/api/v1/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Change password
 * Change password for the currently authenticated user
 */
export const identityServiceChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceChangePasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceChangePasswordResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceChangePasswordData.parseAsync(data)
    },
    url: "/api/v1/users/me/change-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Verify email
 * Verify user email with token
 */
export const identityServiceVerifyEmail = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceVerifyEmailData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceVerifyEmailResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceVerifyEmailData.parseAsync(data)
    },
    url: "/api/auth/verify-email",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Reset password
 * Reset password with token
 */
export const identityServiceResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceResetPasswordData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceResetPasswordResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceResetPasswordData.parseAsync(data)
    },
    url: "/api/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Resend verification email
 * Resend email verification link
 */
export const identityServiceResendVerificationEmail = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceResendVerificationEmailData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceResendVerificationEmailResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceResendVerificationEmailData.parseAsync(data)
    },
    url: "/api/auth/resend-verification",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Register a new user
 * Register a new user account with student role
 */
export const identityServiceRegister = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceRegisterData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceRegisterResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceRegisterData.parseAsync(data)
    },
    responseTransformer: identityServiceRegisterResponseTransformer,
    url: "/api/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Login
 * Authenticate user and return JWT token
 */
export const identityServiceLogin = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceLoginData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceLoginResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceLoginData.parseAsync(data)
    },
    responseTransformer: identityServiceLoginResponseTransformer,
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Request password reset
 * Request password reset link
 */
export const identityServiceRequestPasswordReset = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceRequestPasswordResetData, ThrowOnError>,
) => {
  return (options.client ?? client).post<IdentityServiceRequestPasswordResetResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceRequestPasswordResetData.parseAsync(data)
    },
    url: "/api/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Delete user
 * Delete a user account (Admin only)
 */
export const identityServiceDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceDeleteUserData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<IdentityServiceDeleteUserResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceDeleteUserData.parseAsync(data)
    },
    url: "/api/v1/users/{userId}",
    ...options,
  })
}

/**
 * Get user by ID
 * Get user details by ID (Admin and Instructor only)
 */
export const identityServiceGetUserById = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceGetUserByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<IdentityServiceGetUserByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceGetUserByIdData.parseAsync(data)
    },
    responseTransformer: identityServiceGetUserByIdResponseTransformer,
    url: "/api/v1/users/{userId}",
    ...options,
  })
}

/**
 * Get users by role
 * Get users by role with pagination and sorting (Admin and Instructor only)
 */
export const identityServiceGetUsersByRole = <ThrowOnError extends boolean = false>(
  options: Options<IdentityServiceGetUsersByRoleData, ThrowOnError>,
) => {
  return (options.client ?? client).get<IdentityServiceGetUsersByRoleResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zIdentityServiceGetUsersByRoleData.parseAsync(data)
    },
    responseTransformer: identityServiceGetUsersByRoleResponseTransformer,
    url: "/api/v1/users/role/{role}",
    ...options,
  })
}

/**
 * Get all tutorials
 * Get all available tutorials with pagination and sorting
 */
export const contentServiceGetAllTutorials = <ThrowOnError extends boolean = false>(
  options?: Options<ContentServiceGetAllTutorialsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<ContentServiceGetAllTutorialsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceGetAllTutorialsData.parseAsync(data)
    },
    responseTransformer: contentServiceGetAllTutorialsResponseTransformer,
    url: "/api/v1/tutorials",
    ...options,
  })
}

/**
 * Create a new tutorial
 * Create a new tutorial (Content Provider only)
 */
export const contentServiceCreateTutorial = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceCreateTutorialData, ThrowOnError>,
) => {
  return (options.client ?? client).post<ContentServiceCreateTutorialResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceCreateTutorialData.parseAsync(data)
    },
    responseTransformer: contentServiceCreateTutorialResponseTransformer,
    url: "/api/v1/tutorials",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Get all skills
 * Get all available skills with pagination and sorting
 */
export const contentServiceGetAllSkills = <ThrowOnError extends boolean = false>(
  options?: Options<ContentServiceGetAllSkillsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<ContentServiceGetAllSkillsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceGetAllSkillsData.parseAsync(data)
    },
    responseTransformer: contentServiceGetAllSkillsResponseTransformer,
    url: "/api/v1/skills",
    ...options,
  })
}

/**
 * Create a new skill
 * Create a new skill (Content Provider only)
 */
export const contentServiceCreateSkill = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceCreateSkillData, ThrowOnError>,
) => {
  return (options.client ?? client).post<ContentServiceCreateSkillResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceCreateSkillData.parseAsync(data)
    },
    responseTransformer: contentServiceCreateSkillResponseTransformer,
    url: "/api/v1/skills",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Get all assignments
 * Get all available assignments with pagination and sorting
 */
export const contentServiceGetAllAssignments = <ThrowOnError extends boolean = false>(
  options?: Options<ContentServiceGetAllAssignmentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<ContentServiceGetAllAssignmentsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceGetAllAssignmentsData.parseAsync(data)
    },
    responseTransformer: contentServiceGetAllAssignmentsResponseTransformer,
    url: "/api/v1/assignments",
    ...options,
  })
}

/**
 * Create a new assignment
 * Create a new assignment (Content Provider only)
 */
export const contentServiceCreateAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceCreateAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<ContentServiceCreateAssignmentResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceCreateAssignmentData.parseAsync(data)
    },
    responseTransformer: contentServiceCreateAssignmentResponseTransformer,
    url: "/api/v1/assignments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Publish an assignment
 * Publish a draft assignment (Content Provider only)
 */
export const contentServicePublishAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServicePublishAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<ContentServicePublishAssignmentResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServicePublishAssignmentData.parseAsync(data)
    },
    responseTransformer: contentServicePublishAssignmentResponseTransformer,
    url: "/api/v1/assignments/{id}/publish",
    ...options,
  })
}

/**
 * Archive an assignment
 * Archive an assignment (Content Provider only)
 */
export const contentServiceArchiveAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceArchiveAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).post<ContentServiceArchiveAssignmentResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceArchiveAssignmentData.parseAsync(data)
    },
    responseTransformer: contentServiceArchiveAssignmentResponseTransformer,
    url: "/api/v1/assignments/{id}/archive",
    ...options,
  })
}

/**
 * Delete tutorial
 * Delete a tutorial (Content Provider only)
 */
export const contentServiceDeleteTutorial = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceDeleteTutorialData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<ContentServiceDeleteTutorialResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceDeleteTutorialData.parseAsync(data)
    },
    url: "/api/v1/tutorials/{id}",
    ...options,
  })
}

/**
 * Get tutorial by ID
 * Get tutorial details by ID
 */
export const contentServiceGetTutorialById = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceGetTutorialByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<ContentServiceGetTutorialByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceGetTutorialByIdData.parseAsync(data)
    },
    responseTransformer: contentServiceGetTutorialByIdResponseTransformer,
    url: "/api/v1/tutorials/{id}",
    ...options,
  })
}

/**
 * Update tutorial
 * Update tutorial details (Content Provider only)
 */
export const contentServiceUpdateTutorial = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceUpdateTutorialData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<ContentServiceUpdateTutorialResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceUpdateTutorialData.parseAsync(data)
    },
    responseTransformer: contentServiceUpdateTutorialResponseTransformer,
    url: "/api/v1/tutorials/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Delete skill
 * Delete a skill (Content Provider only)
 */
export const contentServiceDeleteSkill = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceDeleteSkillData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<ContentServiceDeleteSkillResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceDeleteSkillData.parseAsync(data)
    },
    url: "/api/v1/skills/{id}",
    ...options,
  })
}

/**
 * Get skill by ID
 * Get skill details by ID
 */
export const contentServiceGetSkillById = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceGetSkillByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<ContentServiceGetSkillByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceGetSkillByIdData.parseAsync(data)
    },
    responseTransformer: contentServiceGetSkillByIdResponseTransformer,
    url: "/api/v1/skills/{id}",
    ...options,
  })
}

/**
 * Update skill
 * Update skill details (Content Provider only)
 */
export const contentServiceUpdateSkill = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceUpdateSkillData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<ContentServiceUpdateSkillResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceUpdateSkillData.parseAsync(data)
    },
    responseTransformer: contentServiceUpdateSkillResponseTransformer,
    url: "/api/v1/skills/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Delete assignment
 * Delete an assignment (Content Provider only)
 */
export const contentServiceDeleteAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceDeleteAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).delete<ContentServiceDeleteAssignmentResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceDeleteAssignmentData.parseAsync(data)
    },
    url: "/api/v1/assignments/{id}",
    ...options,
  })
}

/**
 * Get assignment by ID
 * Get assignment details by ID
 */
export const contentServiceGetAssignmentById = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceGetAssignmentByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<ContentServiceGetAssignmentByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceGetAssignmentByIdData.parseAsync(data)
    },
    responseTransformer: contentServiceGetAssignmentByIdResponseTransformer,
    url: "/api/v1/assignments/{id}",
    ...options,
  })
}

/**
 * Update assignment
 * Update assignment details (Content Provider only)
 */
export const contentServiceUpdateAssignment = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceUpdateAssignmentData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<ContentServiceUpdateAssignmentResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceUpdateAssignmentData.parseAsync(data)
    },
    responseTransformer: contentServiceUpdateAssignmentResponseTransformer,
    url: "/api/v1/assignments/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Update assignment schedule
 * Update assignment schedule (start_date, due_date) (Instructor only)
 */
export const contentServiceUpdateAssignmentSchedule = <ThrowOnError extends boolean = false>(
  options: Options<ContentServiceUpdateAssignmentScheduleData, ThrowOnError>,
) => {
  return (options.client ?? client).patch<ContentServiceUpdateAssignmentScheduleResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zContentServiceUpdateAssignmentScheduleData.parseAsync(data)
    },
    responseTransformer: contentServiceUpdateAssignmentScheduleResponseTransformer,
    url: "/api/v1/assignments/{id}/schedule",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Get all submissions
 * Get all submissions with pagination and sorting. Students see only their own, instructors can filter by assignment and student
 */
export const submissionServiceGetAllSubmissions = <ThrowOnError extends boolean = false>(
  options?: Options<SubmissionServiceGetAllSubmissionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<SubmissionServiceGetAllSubmissionsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zSubmissionServiceGetAllSubmissionsData.parseAsync(data)
    },
    responseTransformer: submissionServiceGetAllSubmissionsResponseTransformer,
    url: "/api/v1/submissions",
    ...options,
  })
}

/**
 * Create a new submission
 * Submit a solution for an assignment (Students only)
 */
export const submissionServiceCreateSubmission = <ThrowOnError extends boolean = false>(
  options: Options<SubmissionServiceCreateSubmissionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<SubmissionServiceCreateSubmissionResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zSubmissionServiceCreateSubmissionData.parseAsync(data)
    },
    responseTransformer: submissionServiceCreateSubmissionResponseTransformer,
    url: "/api/v1/submissions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Provide feedback for a submission
 * Add instructor feedback to a submission (Instructors only)
 */
export const submissionServiceProvideFeedback = <ThrowOnError extends boolean = false>(
  options: Options<SubmissionServiceProvideFeedbackData, ThrowOnError>,
) => {
  return (options.client ?? client).post<SubmissionServiceProvideFeedbackResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zSubmissionServiceProvideFeedbackData.parseAsync(data)
    },
    responseTransformer: submissionServiceProvideFeedbackResponseTransformer,
    url: "/api/v1/submissions/{id}/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Get submission by ID
 * Get submission details by ID. Students can only view their own, instructors can view all
 */
export const submissionServiceGetSubmissionById = <ThrowOnError extends boolean = false>(
  options: Options<SubmissionServiceGetSubmissionByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<SubmissionServiceGetSubmissionByIdResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zSubmissionServiceGetSubmissionByIdData.parseAsync(data)
    },
    responseTransformer: submissionServiceGetSubmissionByIdResponseTransformer,
    url: "/api/v1/submissions/{id}",
    ...options,
  })
}

/**
 * Get supported runtimes
 * Returns list of all supported programming languages and their versions
 */
export const evaluationServiceGetSupportedRuntimes = <ThrowOnError extends boolean = false>(
  options?: Options<EvaluationServiceGetSupportedRuntimesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    EvaluationServiceGetSupportedRuntimesResponses,
    EvaluationServiceGetSupportedRuntimesErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zEvaluationServiceGetSupportedRuntimesData.parseAsync(data)
    },
    url: "/api/v1/runtimes",
    ...options,
  })
}

/**
 * List all support sessions
 * Instructors view all sessions with pagination, students view their own
 */
export const supportServiceListSessions = <ThrowOnError extends boolean = false>(
  options?: Options<SupportServiceListSessionsData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<SupportServiceListSessionsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => {
      return await zSupportServiceListSessionsData.parseAsync(data)
    },
    responseTransformer: supportServiceListSessionsResponseTransformer,
    url: "/api/v1/support/sessions",
    ...options,
  })
}

/**
 * Create a new support session
 * Students can create support sessions
 */
export const supportServiceCreateSession = <ThrowOnError extends boolean = false>(
  options: Options<SupportServiceCreateSessionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SupportServiceCreateSessionResponses,
    SupportServiceCreateSessionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zSupportServiceCreateSessionData.parseAsync(data)
    },
    responseTransformer: supportServiceCreateSessionResponseTransformer,
    url: "/api/v1/support/sessions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
}

/**
 * Close a support session
 * Only the student who created the session can close it
 */
export const supportServiceCloseSession = <ThrowOnError extends boolean = false>(
  options: Options<SupportServiceCloseSessionData, ThrowOnError>,
) => {
  return (options.client ?? client).post<
    SupportServiceCloseSessionResponses,
    SupportServiceCloseSessionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zSupportServiceCloseSessionData.parseAsync(data)
    },
    responseTransformer: supportServiceCloseSessionResponseTransformer,
    url: "/api/v1/support/sessions/{id}/close",
    ...options,
  })
}

/**
 * Get support session by ID
 * Instructors can view all, students can view their own
 */
export const supportServiceGetSessionById = <ThrowOnError extends boolean = false>(
  options: Options<SupportServiceGetSessionByIdData, ThrowOnError>,
) => {
  return (options.client ?? client).get<
    SupportServiceGetSessionByIdResponses,
    SupportServiceGetSessionByIdErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => {
      return await zSupportServiceGetSessionByIdData.parseAsync(data)
    },
    responseTransformer: supportServiceGetSessionByIdResponseTransformer,
    url: "/api/v1/support/sessions/{id}",
    ...options,
  })
}
