// This file is auto-generated by @hey-api/openapi-ts

import type {
  ContentServiceArchiveAssignmentResponse,
  ContentServiceCreateAssignmentResponse,
  ContentServiceCreateSkillResponse,
  ContentServiceCreateTutorialResponse,
  ContentServiceGetAllAssignmentsResponse,
  ContentServiceGetAllSkillsResponse,
  ContentServiceGetAllTutorialsResponse,
  ContentServiceGetAssignmentByIdResponse,
  ContentServiceGetSkillByIdResponse,
  ContentServiceGetTutorialByIdResponse,
  ContentServicePublishAssignmentResponse,
  ContentServiceUpdateAssignmentResponse,
  ContentServiceUpdateAssignmentScheduleResponse,
  ContentServiceUpdateSkillResponse,
  ContentServiceUpdateTutorialResponse,
  IdentityServiceCreateUserResponse,
  IdentityServiceGetAllUsersResponse,
  IdentityServiceGetCurrentUserResponse,
  IdentityServiceGetUserByIdResponse,
  IdentityServiceGetUsersByRoleResponse,
  IdentityServiceLoginResponse,
  IdentityServiceRegisterResponse,
  IdentityServiceUpdateCurrentUserProfileResponse,
  SubmissionServiceCreateSubmissionResponse,
  SubmissionServiceGetAllSubmissionsResponse,
  SubmissionServiceGetSubmissionByIdResponse,
  SubmissionServiceProvideFeedbackResponse,
  SupportServiceCloseSessionResponse,
  SupportServiceCreateSessionResponse,
  SupportServiceGetSessionByIdResponse,
  SupportServiceListSessionsResponse,
} from "./types.gen"

export const identityServiceGetCurrentUserResponseTransformer = async (
  data: any,
): Promise<IdentityServiceGetCurrentUserResponse> => {
  data = identityServiceUserResponseSchemaResponseTransformer(data)
  return data
}

const identityServiceUserResponseSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt)
  }
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt)
  }
  return data
}

export const identityServiceUpdateCurrentUserProfileResponseTransformer = async (
  data: any,
): Promise<IdentityServiceUpdateCurrentUserProfileResponse> => {
  data = identityServiceUserResponseSchemaResponseTransformer(data)
  return data
}

export const identityServiceGetAllUsersResponseTransformer = async (
  data: any,
): Promise<IdentityServiceGetAllUsersResponse> => {
  data = identityServicePageResponseUserResponseSchemaResponseTransformer(data)
  return data
}

const identityServicePageResponseUserResponseSchemaResponseTransformer = (data: any) => {
  if (data.content) {
    data.content = data.content.map((item: any) => {
      return identityServiceUserResponseSchemaResponseTransformer(item)
    })
  }
  if (data.totalElements) {
    data.totalElements = BigInt(data.totalElements.toString())
  }
  return data
}

export const identityServiceCreateUserResponseTransformer = async (
  data: any,
): Promise<IdentityServiceCreateUserResponse> => {
  data = identityServiceUserResponseSchemaResponseTransformer(data)
  return data
}

export const identityServiceRegisterResponseTransformer = async (
  data: any,
): Promise<IdentityServiceRegisterResponse> => {
  data = identityServiceAuthResponseSchemaResponseTransformer(data)
  return data
}

const identityServiceAuthResponseSchemaResponseTransformer = (data: any) => {
  if (data.user) {
    data.user = identityServiceUserResponseSchemaResponseTransformer(data.user)
  }
  return data
}

export const identityServiceLoginResponseTransformer = async (data: any): Promise<IdentityServiceLoginResponse> => {
  data = identityServiceAuthResponseSchemaResponseTransformer(data)
  return data
}

export const identityServiceGetUserByIdResponseTransformer = async (
  data: any,
): Promise<IdentityServiceGetUserByIdResponse> => {
  data = identityServiceUserResponseSchemaResponseTransformer(data)
  return data
}

export const identityServiceGetUsersByRoleResponseTransformer = async (
  data: any,
): Promise<IdentityServiceGetUsersByRoleResponse> => {
  data = identityServicePageResponseUserResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceGetAllTutorialsResponseTransformer = async (
  data: any,
): Promise<ContentServiceGetAllTutorialsResponse> => {
  data = contentServicePageResponseTutorialResponseSchemaResponseTransformer(data)
  return data
}

const contentServicePageResponseTutorialResponseSchemaResponseTransformer = (data: any) => {
  if (data.content) {
    data.content = data.content.map((item: any) => {
      return contentServiceTutorialResponseSchemaResponseTransformer(item)
    })
  }
  if (data.totalElements) {
    data.totalElements = BigInt(data.totalElements.toString())
  }
  return data
}

const contentServiceTutorialResponseSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt)
  }
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt)
  }
  return data
}

export const contentServiceCreateTutorialResponseTransformer = async (
  data: any,
): Promise<ContentServiceCreateTutorialResponse> => {
  data = contentServiceTutorialResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceGetAllSkillsResponseTransformer = async (
  data: any,
): Promise<ContentServiceGetAllSkillsResponse> => {
  data = contentServicePageResponseSkillResponseSchemaResponseTransformer(data)
  return data
}

const contentServicePageResponseSkillResponseSchemaResponseTransformer = (data: any) => {
  if (data.content) {
    data.content = data.content.map((item: any) => {
      return contentServiceSkillResponseSchemaResponseTransformer(item)
    })
  }
  if (data.totalElements) {
    data.totalElements = BigInt(data.totalElements.toString())
  }
  return data
}

const contentServiceSkillResponseSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt)
  }
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt)
  }
  return data
}

export const contentServiceCreateSkillResponseTransformer = async (
  data: any,
): Promise<ContentServiceCreateSkillResponse> => {
  data = contentServiceSkillResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceGetAllAssignmentsResponseTransformer = async (
  data: any,
): Promise<ContentServiceGetAllAssignmentsResponse> => {
  data = contentServicePageResponseAssignmentResponseSchemaResponseTransformer(data)
  return data
}

const contentServicePageResponseAssignmentResponseSchemaResponseTransformer = (data: any) => {
  if (data.content) {
    data.content = data.content.map((item: any) => {
      return contentServiceAssignmentResponseSchemaResponseTransformer(item)
    })
  }
  if (data.totalElements) {
    data.totalElements = BigInt(data.totalElements.toString())
  }
  return data
}

const contentServiceAssignmentResponseSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt)
  }
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt)
  }
  if (data.startDate) {
    data.startDate = new Date(data.startDate)
  }
  if (data.dueDate) {
    data.dueDate = new Date(data.dueDate)
  }
  if (data.skills) {
    data.skills = data.skills.map((item: any) => {
      return contentServiceSkillResponseSchemaResponseTransformer(item)
    })
  }
  if (data.tutorials) {
    data.tutorials = data.tutorials.map((item: any) => {
      return contentServiceTutorialResponseSchemaResponseTransformer(item)
    })
  }
  return data
}

export const contentServiceCreateAssignmentResponseTransformer = async (
  data: any,
): Promise<ContentServiceCreateAssignmentResponse> => {
  data = contentServiceAssignmentResponseSchemaResponseTransformer(data)
  return data
}

export const contentServicePublishAssignmentResponseTransformer = async (
  data: any,
): Promise<ContentServicePublishAssignmentResponse> => {
  data = contentServiceAssignmentResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceArchiveAssignmentResponseTransformer = async (
  data: any,
): Promise<ContentServiceArchiveAssignmentResponse> => {
  data = contentServiceAssignmentResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceGetTutorialByIdResponseTransformer = async (
  data: any,
): Promise<ContentServiceGetTutorialByIdResponse> => {
  data = contentServiceTutorialResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceUpdateTutorialResponseTransformer = async (
  data: any,
): Promise<ContentServiceUpdateTutorialResponse> => {
  data = contentServiceTutorialResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceGetSkillByIdResponseTransformer = async (
  data: any,
): Promise<ContentServiceGetSkillByIdResponse> => {
  data = contentServiceSkillResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceUpdateSkillResponseTransformer = async (
  data: any,
): Promise<ContentServiceUpdateSkillResponse> => {
  data = contentServiceSkillResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceGetAssignmentByIdResponseTransformer = async (
  data: any,
): Promise<ContentServiceGetAssignmentByIdResponse> => {
  data = contentServiceAssignmentResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceUpdateAssignmentResponseTransformer = async (
  data: any,
): Promise<ContentServiceUpdateAssignmentResponse> => {
  data = contentServiceAssignmentResponseSchemaResponseTransformer(data)
  return data
}

export const contentServiceUpdateAssignmentScheduleResponseTransformer = async (
  data: any,
): Promise<ContentServiceUpdateAssignmentScheduleResponse> => {
  data = contentServiceAssignmentResponseSchemaResponseTransformer(data)
  return data
}

export const submissionServiceGetAllSubmissionsResponseTransformer = async (
  data: any,
): Promise<SubmissionServiceGetAllSubmissionsResponse> => {
  data = submissionServicePageResponseSubmissionResponseSchemaResponseTransformer(data)
  return data
}

const submissionServicePageResponseSubmissionResponseSchemaResponseTransformer = (data: any) => {
  if (data.content) {
    data.content = data.content.map((item: any) => {
      return submissionServiceSubmissionResponseSchemaResponseTransformer(item)
    })
  }
  if (data.totalElements) {
    data.totalElements = BigInt(data.totalElements.toString())
  }
  return data
}

const submissionServiceSubmissionResponseSchemaResponseTransformer = (data: any) => {
  if (data.submittedAt) {
    data.submittedAt = new Date(data.submittedAt)
  }
  if (data.evaluatedAt) {
    data.evaluatedAt = new Date(data.evaluatedAt)
  }
  return data
}

export const submissionServiceCreateSubmissionResponseTransformer = async (
  data: any,
): Promise<SubmissionServiceCreateSubmissionResponse> => {
  data = submissionServiceSubmissionResponseSchemaResponseTransformer(data)
  return data
}

export const submissionServiceProvideFeedbackResponseTransformer = async (
  data: any,
): Promise<SubmissionServiceProvideFeedbackResponse> => {
  data = submissionServiceSubmissionResponseSchemaResponseTransformer(data)
  return data
}

export const submissionServiceGetSubmissionByIdResponseTransformer = async (
  data: any,
): Promise<SubmissionServiceGetSubmissionByIdResponse> => {
  data = submissionServiceSubmissionResponseSchemaResponseTransformer(data)
  return data
}

export const supportServiceListSessionsResponseTransformer = async (
  data: any,
): Promise<SupportServiceListSessionsResponse> => {
  data = supportServicePageResponseSupportSessionDtoSchemaResponseTransformer(data)
  return data
}

const supportServicePageResponseSupportSessionDtoSchemaResponseTransformer = (data: any) => {
  if (data.content) {
    data.content = data.content.map((item: any) => {
      return supportServiceSupportSessionDtoSchemaResponseTransformer(item)
    })
  }
  if (data.totalElements) {
    data.totalElements = BigInt(data.totalElements.toString())
  }
  return data
}

const supportServiceSupportSessionDtoSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt)
  }
  if (data.closedAt) {
    data.closedAt = new Date(data.closedAt)
  }
  if (data.messages) {
    data.messages = data.messages.map((item: any) => {
      return supportServiceSupportMessageDtoSchemaResponseTransformer(item)
    })
  }
  return data
}

const supportServiceSupportMessageDtoSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt)
  }
  return data
}

export const supportServiceCreateSessionResponseTransformer = async (
  data: any,
): Promise<SupportServiceCreateSessionResponse> => {
  data = supportServiceSupportSessionDtoSchemaResponseTransformer(data)
  return data
}

export const supportServiceCloseSessionResponseTransformer = async (
  data: any,
): Promise<SupportServiceCloseSessionResponse> => {
  data = supportServiceSupportSessionDtoSchemaResponseTransformer(data)
  return data
}

export const supportServiceGetSessionByIdResponseTransformer = async (
  data: any,
): Promise<SupportServiceGetSessionByIdResponse> => {
  data = supportServiceSupportSessionDtoSchemaResponseTransformer(data)
  return data
}
