// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | "http://localhost:8085" | (string & {})
}

export type IdentityServiceUpdateProfileRequest = {
  firstName?: string
  lastName?: string
}

export type IdentityServiceUserResponse = {
  id?: string
  email?: string
  firstName?: string
  lastName?: string
  role?: "STUDENT" | "INSTRUCTOR" | "CONTENT_PROVIDER" | "ADMIN"
  isActive?: boolean
  isEmailVerified?: boolean
  createdAt?: Date
  updatedAt?: Date
}

export type IdentityServiceCreateUserRequest = {
  email: string
  password: string
  firstName: string
  lastName: string
  role?: "STUDENT" | "INSTRUCTOR" | "CONTENT_PROVIDER" | "ADMIN"
  isActive?: boolean
  isEmailVerified?: boolean
}

export type IdentityServiceChangePasswordRequest = {
  currentPassword: string
  newPassword: string
}

export type IdentityServiceTokenRequest = {
  token: string
}

export type IdentityServiceResetPasswordRequest = {
  token: string
  newPassword: string
}

export type IdentityServiceEmailRequest = {
  email: string
}

export type IdentityServiceRegisterRequest = {
  email: string
  password: string
  firstName: string
  lastName: string
}

export type IdentityServiceAuthResponse = {
  token?: string
  type?: string
  user?: IdentityServiceUserResponse
}

export type IdentityServiceLoginRequest = {
  email: string
  password: string
}

/**
 * Paginated response wrapper
 */
export type IdentityServicePageResponseUserResponse = {
  /**
   * List of items in the current page
   */
  content?: Array<IdentityServiceUserResponse>
  /**
   * Current page number (0-indexed)
   */
  pageNumber?: number
  /**
   * Number of items per page
   */
  pageSize?: number
  /**
   * Total number of items across all pages
   */
  totalElements?: bigint
  /**
   * Total number of pages
   */
  totalPages?: number
  /**
   * Whether this is the first page
   */
  first?: boolean
  /**
   * Whether this is the last page
   */
  last?: boolean
  /**
   * Whether there is a next page
   */
  hasNext?: boolean
  /**
   * Whether there is a previous page
   */
  hasPrevious?: boolean
}

export type ContentServiceCreateTutorialRequest = {
  title: string
  content: string
  tags?: Array<string>
}

export type ContentServiceTutorialResponse = {
  id?: string
  title?: string
  content?: string
  creatorId?: string
  createdAt?: Date
  updatedAt?: Date
  tags?: Array<string>
}

export type ContentServiceCreateSkillRequest = {
  name: string
  description?: string
}

export type ContentServiceSkillResponse = {
  id?: string
  name?: string
  description?: string
  createdAt?: Date
  updatedAt?: Date
}

export type ContentServiceCreateAssignmentRequest = {
  title: string
  description: string
  difficultyLevel: "EASY" | "MEDIUM" | "HARD"
  startDate?: Date
  dueDate?: Date
  maxScore: number
  languages: Array<string>
  testCases: Array<ContentServiceTestCase>
  skillIds?: Array<string>
  tutorialIds?: Array<string>
}

export type ContentServiceTestCase = {
  order?: number
  description?: string
  hidden?: boolean
  weight?: number
  input?: string
  output?: string
  timeout?: number
  memoryLimit?: number
}

export type ContentServiceAssignmentResponse = {
  id?: string
  title?: string
  description?: string
  difficultyLevel?: "EASY" | "MEDIUM" | "HARD"
  creatorId?: string
  createdAt?: Date
  updatedAt?: Date
  startDate?: Date
  dueDate?: Date
  maxScore?: number
  status?: "DRAFT" | "PUBLISHED" | "ARCHIVED"
  languages?: Array<string>
  testCases?: Array<ContentServiceTestCase>
  skills?: Array<ContentServiceSkillResponse>
  tutorials?: Array<ContentServiceTutorialResponse>
}

export type ContentServiceUpdateTutorialRequest = {
  title?: string
  content?: string
  tags?: Array<string>
}

export type ContentServiceUpdateSkillRequest = {
  name?: string
  description?: string
}

export type ContentServiceUpdateAssignmentRequest = {
  title?: string
  description?: string
  difficultyLevel?: "EASY" | "MEDIUM" | "HARD"
  startDate?: Date
  dueDate?: Date
  maxScore?: number
  languages?: Array<string>
  testCases?: Array<ContentServiceTestCase>
  skillIds?: Array<string>
  tutorialIds?: Array<string>
}

export type ContentServiceUpdateAssignmentScheduleRequest = {
  startDate: Date
  dueDate: Date
}

/**
 * Paginated response wrapper
 */
export type ContentServicePageResponseTutorialResponse = {
  /**
   * List of items in the current page
   */
  content?: Array<ContentServiceTutorialResponse>
  /**
   * Current page number (0-indexed)
   */
  pageNumber?: number
  /**
   * Number of items per page
   */
  pageSize?: number
  /**
   * Total number of items across all pages
   */
  totalElements?: bigint
  /**
   * Total number of pages
   */
  totalPages?: number
  /**
   * Whether this is the first page
   */
  first?: boolean
  /**
   * Whether this is the last page
   */
  last?: boolean
  /**
   * Whether there is a next page
   */
  hasNext?: boolean
  /**
   * Whether there is a previous page
   */
  hasPrevious?: boolean
}

/**
 * Paginated response wrapper
 */
export type ContentServicePageResponseSkillResponse = {
  /**
   * List of items in the current page
   */
  content?: Array<ContentServiceSkillResponse>
  /**
   * Current page number (0-indexed)
   */
  pageNumber?: number
  /**
   * Number of items per page
   */
  pageSize?: number
  /**
   * Total number of items across all pages
   */
  totalElements?: bigint
  /**
   * Total number of pages
   */
  totalPages?: number
  /**
   * Whether this is the first page
   */
  first?: boolean
  /**
   * Whether this is the last page
   */
  last?: boolean
  /**
   * Whether there is a next page
   */
  hasNext?: boolean
  /**
   * Whether there is a previous page
   */
  hasPrevious?: boolean
}

/**
 * Paginated response wrapper
 */
export type ContentServicePageResponseAssignmentResponse = {
  /**
   * List of items in the current page
   */
  content?: Array<ContentServiceAssignmentResponse>
  /**
   * Current page number (0-indexed)
   */
  pageNumber?: number
  /**
   * Number of items per page
   */
  pageSize?: number
  /**
   * Total number of items across all pages
   */
  totalElements?: bigint
  /**
   * Total number of pages
   */
  totalPages?: number
  /**
   * Whether this is the first page
   */
  first?: boolean
  /**
   * Whether this is the last page
   */
  last?: boolean
  /**
   * Whether there is a next page
   */
  hasNext?: boolean
  /**
   * Whether there is a previous page
   */
  hasPrevious?: boolean
}

export type SubmissionServiceCreateSubmissionRequest = {
  assignmentId: string
  code: string
  language: string
}

export type SubmissionServiceSubmissionResponse = {
  id?: string
  assignmentId?: string
  studentId?: string
  submittedAt?: Date
  status?: "PENDING" | "EVALUATED" | "FAILED"
  code?: string
  language?: string
  result?: "PASSED" | "FAILED" | "PARTIAL"
  score?: number
  testCaseResults?: Array<SubmissionServiceTestCaseResultResponse>
  evaluatedAt?: Date
  feedback?: string
}

export type SubmissionServiceTestCaseResultResponse = {
  order?: number
  description?: string
  hidden?: boolean
  weight?: number
  input?: string
  output?: string
  timeout?: number
  memoryLimit?: number
  passed?: boolean
  actualOutput?: string
  errorMessage?: string
  executionTime?: number
  memoryUsed?: number
}

export type SubmissionServiceSubmissionFeedbackRequest = {
  feedback: string
}

/**
 * Paginated response wrapper
 */
export type SubmissionServicePageResponseSubmissionResponse = {
  /**
   * List of items in the current page
   */
  content?: Array<SubmissionServiceSubmissionResponse>
  /**
   * Current page number (0-indexed)
   */
  pageNumber?: number
  /**
   * Number of items per page
   */
  pageSize?: number
  /**
   * Total number of items across all pages
   */
  totalElements?: bigint
  /**
   * Total number of pages
   */
  totalPages?: number
  /**
   * Whether this is the first page
   */
  first?: boolean
  /**
   * Whether this is the last page
   */
  last?: boolean
  /**
   * Whether there is a next page
   */
  hasNext?: boolean
  /**
   * Whether there is a previous page
   */
  hasPrevious?: boolean
}

/**
 * Supported programming language runtime information
 */
export type EvaluationServiceRuntimeResponse = {
  /**
   * Name of the programming language
   */
  language?: string
  /**
   * Version of the runtime
   */
  version?: string
  /**
   * List of alternative names for the language
   */
  aliases?: Array<string>
  /**
   * Name of the runtime, only provided if alternative runtimes exist
   */
  runtime?: string
}

export type SupportServiceCreateSupportSessionRequest = {
  initialMessage: string
}

export type SupportServiceSupportMessageDto = {
  id?: string
  senderId?: string
  content?: string
  isInstructor?: boolean
  isRead?: boolean
  createdAt?: Date
}

export type SupportServiceSupportSessionDto = {
  id?: string
  studentId?: string
  instructorId?: string
  isClosed?: boolean
  createdAt?: Date
  closedAt?: Date
  messages?: Array<SupportServiceSupportMessageDto>
}

/**
 * Paginated response wrapper
 */
export type SupportServicePageResponseSupportSessionDto = {
  /**
   * List of items in the current page
   */
  content?: Array<SupportServiceSupportSessionDto>
  /**
   * Current page number (0-indexed)
   */
  pageNumber?: number
  /**
   * Number of items per page
   */
  pageSize?: number
  /**
   * Total number of items across all pages
   */
  totalElements?: bigint
  /**
   * Total number of pages
   */
  totalPages?: number
  /**
   * Whether this is the first page
   */
  first?: boolean
  /**
   * Whether this is the last page
   */
  last?: boolean
  /**
   * Whether there is a next page
   */
  hasNext?: boolean
  /**
   * Whether there is a previous page
   */
  hasPrevious?: boolean
}

export type IdentityServiceDeactivateUserData = {
  body?: never
  path: {
    userId: string
  }
  query?: never
  url: "/api/v1/users/{userId}/deactivate"
}

export type IdentityServiceDeactivateUserResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type IdentityServiceDeactivateUserResponse =
  IdentityServiceDeactivateUserResponses[keyof IdentityServiceDeactivateUserResponses]

export type IdentityServiceActivateUserData = {
  body?: never
  path: {
    userId: string
  }
  query?: never
  url: "/api/v1/users/{userId}/activate"
}

export type IdentityServiceActivateUserResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type IdentityServiceActivateUserResponse =
  IdentityServiceActivateUserResponses[keyof IdentityServiceActivateUserResponses]

export type IdentityServiceGetCurrentUserData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type IdentityServiceGetCurrentUserResponses = {
  /**
   * OK
   */
  200: IdentityServiceUserResponse
}

export type IdentityServiceGetCurrentUserResponse =
  IdentityServiceGetCurrentUserResponses[keyof IdentityServiceGetCurrentUserResponses]

export type IdentityServiceUpdateCurrentUserProfileData = {
  body: IdentityServiceUpdateProfileRequest
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type IdentityServiceUpdateCurrentUserProfileResponses = {
  /**
   * OK
   */
  200: IdentityServiceUserResponse
}

export type IdentityServiceUpdateCurrentUserProfileResponse =
  IdentityServiceUpdateCurrentUserProfileResponses[keyof IdentityServiceUpdateCurrentUserProfileResponses]

export type IdentityServiceGetAllUsersData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page number (0-indexed)
     */
    page?: string
    /**
     * Number of items per page
     */
    size?: string
    /**
     * Sort by field(s). Format: field1,direction;field2,direction. Direction can be 'asc' or 'desc'. Multiple sort criteria separated by semicolon.
     */
    sort?: string
  }
  url: "/api/v1/users"
}

export type IdentityServiceGetAllUsersResponses = {
  /**
   * OK
   */
  200: IdentityServicePageResponseUserResponse
}

export type IdentityServiceGetAllUsersResponse =
  IdentityServiceGetAllUsersResponses[keyof IdentityServiceGetAllUsersResponses]

export type IdentityServiceCreateUserData = {
  body: IdentityServiceCreateUserRequest
  path?: never
  query?: never
  url: "/api/v1/users"
}

export type IdentityServiceCreateUserResponses = {
  /**
   * OK
   */
  200: IdentityServiceUserResponse
}

export type IdentityServiceCreateUserResponse =
  IdentityServiceCreateUserResponses[keyof IdentityServiceCreateUserResponses]

export type IdentityServiceChangePasswordData = {
  body: IdentityServiceChangePasswordRequest
  path?: never
  query?: never
  url: "/api/v1/users/me/change-password"
}

export type IdentityServiceChangePasswordResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type IdentityServiceChangePasswordResponse =
  IdentityServiceChangePasswordResponses[keyof IdentityServiceChangePasswordResponses]

export type IdentityServiceVerifyEmailData = {
  body: IdentityServiceTokenRequest
  path?: never
  query?: never
  url: "/api/auth/verify-email"
}

export type IdentityServiceVerifyEmailResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type IdentityServiceVerifyEmailResponse =
  IdentityServiceVerifyEmailResponses[keyof IdentityServiceVerifyEmailResponses]

export type IdentityServiceResetPasswordData = {
  body: IdentityServiceResetPasswordRequest
  path?: never
  query?: never
  url: "/api/auth/reset-password"
}

export type IdentityServiceResetPasswordResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type IdentityServiceResetPasswordResponse =
  IdentityServiceResetPasswordResponses[keyof IdentityServiceResetPasswordResponses]

export type IdentityServiceResendVerificationEmailData = {
  body: IdentityServiceEmailRequest
  path?: never
  query?: never
  url: "/api/auth/resend-verification"
}

export type IdentityServiceResendVerificationEmailResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type IdentityServiceResendVerificationEmailResponse =
  IdentityServiceResendVerificationEmailResponses[keyof IdentityServiceResendVerificationEmailResponses]

export type IdentityServiceRegisterData = {
  body: IdentityServiceRegisterRequest
  path?: never
  query?: never
  url: "/api/auth/register"
}

export type IdentityServiceRegisterResponses = {
  /**
   * OK
   */
  200: IdentityServiceAuthResponse
}

export type IdentityServiceRegisterResponse = IdentityServiceRegisterResponses[keyof IdentityServiceRegisterResponses]

export type IdentityServiceLoginData = {
  body: IdentityServiceLoginRequest
  path?: never
  query?: never
  url: "/api/auth/login"
}

export type IdentityServiceLoginResponses = {
  /**
   * OK
   */
  200: IdentityServiceAuthResponse
}

export type IdentityServiceLoginResponse = IdentityServiceLoginResponses[keyof IdentityServiceLoginResponses]

export type IdentityServiceRequestPasswordResetData = {
  body: IdentityServiceEmailRequest
  path?: never
  query?: never
  url: "/api/auth/forgot-password"
}

export type IdentityServiceRequestPasswordResetResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type IdentityServiceRequestPasswordResetResponse =
  IdentityServiceRequestPasswordResetResponses[keyof IdentityServiceRequestPasswordResetResponses]

export type IdentityServiceDeleteUserData = {
  body?: never
  path: {
    userId: string
  }
  query?: never
  url: "/api/v1/users/{userId}"
}

export type IdentityServiceDeleteUserResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type IdentityServiceDeleteUserResponse =
  IdentityServiceDeleteUserResponses[keyof IdentityServiceDeleteUserResponses]

export type IdentityServiceGetUserByIdData = {
  body?: never
  path: {
    userId: string
  }
  query?: never
  url: "/api/v1/users/{userId}"
}

export type IdentityServiceGetUserByIdResponses = {
  /**
   * OK
   */
  200: IdentityServiceUserResponse
}

export type IdentityServiceGetUserByIdResponse =
  IdentityServiceGetUserByIdResponses[keyof IdentityServiceGetUserByIdResponses]

export type IdentityServiceGetUsersByRoleData = {
  body?: never
  path: {
    role: "STUDENT" | "INSTRUCTOR" | "CONTENT_PROVIDER" | "ADMIN"
  }
  query?: {
    /**
     * Page number (0-indexed)
     */
    page?: string
    /**
     * Number of items per page
     */
    size?: string
    /**
     * Sort by field(s). Format: field1,direction;field2,direction. Direction can be 'asc' or 'desc'. Multiple sort criteria separated by semicolon.
     */
    sort?: string
  }
  url: "/api/v1/users/role/{role}"
}

export type IdentityServiceGetUsersByRoleResponses = {
  /**
   * OK
   */
  200: IdentityServicePageResponseUserResponse
}

export type IdentityServiceGetUsersByRoleResponse =
  IdentityServiceGetUsersByRoleResponses[keyof IdentityServiceGetUsersByRoleResponses]

export type ContentServiceGetAllTutorialsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page number (0-indexed)
     */
    page?: string
    /**
     * Number of items per page
     */
    size?: string
    /**
     * Sort by field(s). Format: field1,direction;field2,direction. Direction can be 'asc' or 'desc'. Multiple sort criteria separated by semicolon.
     */
    sort?: string
  }
  url: "/api/v1/tutorials"
}

export type ContentServiceGetAllTutorialsResponses = {
  /**
   * OK
   */
  200: ContentServicePageResponseTutorialResponse
}

export type ContentServiceGetAllTutorialsResponse =
  ContentServiceGetAllTutorialsResponses[keyof ContentServiceGetAllTutorialsResponses]

export type ContentServiceCreateTutorialData = {
  body: ContentServiceCreateTutorialRequest
  path?: never
  query?: never
  url: "/api/v1/tutorials"
}

export type ContentServiceCreateTutorialResponses = {
  /**
   * OK
   */
  200: ContentServiceTutorialResponse
}

export type ContentServiceCreateTutorialResponse =
  ContentServiceCreateTutorialResponses[keyof ContentServiceCreateTutorialResponses]

export type ContentServiceGetAllSkillsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page number (0-indexed)
     */
    page?: string
    /**
     * Number of items per page
     */
    size?: string
    /**
     * Sort by field(s). Format: field1,direction;field2,direction. Direction can be 'asc' or 'desc'. Multiple sort criteria separated by semicolon.
     */
    sort?: string
  }
  url: "/api/v1/skills"
}

export type ContentServiceGetAllSkillsResponses = {
  /**
   * OK
   */
  200: ContentServicePageResponseSkillResponse
}

export type ContentServiceGetAllSkillsResponse =
  ContentServiceGetAllSkillsResponses[keyof ContentServiceGetAllSkillsResponses]

export type ContentServiceCreateSkillData = {
  body: ContentServiceCreateSkillRequest
  path?: never
  query?: never
  url: "/api/v1/skills"
}

export type ContentServiceCreateSkillResponses = {
  /**
   * OK
   */
  200: ContentServiceSkillResponse
}

export type ContentServiceCreateSkillResponse =
  ContentServiceCreateSkillResponses[keyof ContentServiceCreateSkillResponses]

export type ContentServiceGetAllAssignmentsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page number (0-indexed)
     */
    page?: string
    /**
     * Number of items per page
     */
    size?: string
    /**
     * Sort by field(s). Format: field1,direction;field2,direction. Direction can be 'asc' or 'desc'. Multiple sort criteria separated by semicolon.
     */
    sort?: string
  }
  url: "/api/v1/assignments"
}

export type ContentServiceGetAllAssignmentsResponses = {
  /**
   * OK
   */
  200: ContentServicePageResponseAssignmentResponse
}

export type ContentServiceGetAllAssignmentsResponse =
  ContentServiceGetAllAssignmentsResponses[keyof ContentServiceGetAllAssignmentsResponses]

export type ContentServiceCreateAssignmentData = {
  body: ContentServiceCreateAssignmentRequest
  path?: never
  query?: never
  url: "/api/v1/assignments"
}

export type ContentServiceCreateAssignmentResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServiceCreateAssignmentResponse =
  ContentServiceCreateAssignmentResponses[keyof ContentServiceCreateAssignmentResponses]

export type ContentServicePublishAssignmentData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}/publish"
}

export type ContentServicePublishAssignmentResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServicePublishAssignmentResponse =
  ContentServicePublishAssignmentResponses[keyof ContentServicePublishAssignmentResponses]

export type ContentServiceArchiveAssignmentData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}/archive"
}

export type ContentServiceArchiveAssignmentResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServiceArchiveAssignmentResponse =
  ContentServiceArchiveAssignmentResponses[keyof ContentServiceArchiveAssignmentResponses]

export type ContentServiceDeleteTutorialData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/tutorials/{id}"
}

export type ContentServiceDeleteTutorialResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type ContentServiceDeleteTutorialResponse =
  ContentServiceDeleteTutorialResponses[keyof ContentServiceDeleteTutorialResponses]

export type ContentServiceGetTutorialByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/tutorials/{id}"
}

export type ContentServiceGetTutorialByIdResponses = {
  /**
   * OK
   */
  200: ContentServiceTutorialResponse
}

export type ContentServiceGetTutorialByIdResponse =
  ContentServiceGetTutorialByIdResponses[keyof ContentServiceGetTutorialByIdResponses]

export type ContentServiceUpdateTutorialData = {
  body: ContentServiceUpdateTutorialRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/tutorials/{id}"
}

export type ContentServiceUpdateTutorialResponses = {
  /**
   * OK
   */
  200: ContentServiceTutorialResponse
}

export type ContentServiceUpdateTutorialResponse =
  ContentServiceUpdateTutorialResponses[keyof ContentServiceUpdateTutorialResponses]

export type ContentServiceDeleteSkillData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/skills/{id}"
}

export type ContentServiceDeleteSkillResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type ContentServiceDeleteSkillResponse =
  ContentServiceDeleteSkillResponses[keyof ContentServiceDeleteSkillResponses]

export type ContentServiceGetSkillByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/skills/{id}"
}

export type ContentServiceGetSkillByIdResponses = {
  /**
   * OK
   */
  200: ContentServiceSkillResponse
}

export type ContentServiceGetSkillByIdResponse =
  ContentServiceGetSkillByIdResponses[keyof ContentServiceGetSkillByIdResponses]

export type ContentServiceUpdateSkillData = {
  body: ContentServiceUpdateSkillRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/skills/{id}"
}

export type ContentServiceUpdateSkillResponses = {
  /**
   * OK
   */
  200: ContentServiceSkillResponse
}

export type ContentServiceUpdateSkillResponse =
  ContentServiceUpdateSkillResponses[keyof ContentServiceUpdateSkillResponses]

export type ContentServiceDeleteAssignmentData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}"
}

export type ContentServiceDeleteAssignmentResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string
  }
}

export type ContentServiceDeleteAssignmentResponse =
  ContentServiceDeleteAssignmentResponses[keyof ContentServiceDeleteAssignmentResponses]

export type ContentServiceGetAssignmentByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}"
}

export type ContentServiceGetAssignmentByIdResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServiceGetAssignmentByIdResponse =
  ContentServiceGetAssignmentByIdResponses[keyof ContentServiceGetAssignmentByIdResponses]

export type ContentServiceUpdateAssignmentData = {
  body: ContentServiceUpdateAssignmentRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}"
}

export type ContentServiceUpdateAssignmentResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServiceUpdateAssignmentResponse =
  ContentServiceUpdateAssignmentResponses[keyof ContentServiceUpdateAssignmentResponses]

export type ContentServiceUpdateAssignmentScheduleData = {
  body: ContentServiceUpdateAssignmentScheduleRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}/schedule"
}

export type ContentServiceUpdateAssignmentScheduleResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServiceUpdateAssignmentScheduleResponse =
  ContentServiceUpdateAssignmentScheduleResponses[keyof ContentServiceUpdateAssignmentScheduleResponses]

export type SubmissionServiceGetAllSubmissionsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Filter by assignment ID (instructors only)
     */
    assignmentId?: string
    /**
     * Filter by student ID (instructors only)
     */
    studentId?: string
    /**
     * Filter by status
     */
    status?: "PENDING" | "EVALUATED" | "FAILED"
    /**
     * Page number (0-indexed)
     */
    page?: string
    /**
     * Number of items per page
     */
    size?: string
    /**
     * Sort by field(s). Format: field1,direction;field2,direction. Direction can be 'asc' or 'desc'. Multiple sort criteria separated by semicolon.
     */
    sort?: string
  }
  url: "/api/v1/submissions"
}

export type SubmissionServiceGetAllSubmissionsResponses = {
  /**
   * OK
   */
  200: SubmissionServicePageResponseSubmissionResponse
}

export type SubmissionServiceGetAllSubmissionsResponse =
  SubmissionServiceGetAllSubmissionsResponses[keyof SubmissionServiceGetAllSubmissionsResponses]

export type SubmissionServiceCreateSubmissionData = {
  body: SubmissionServiceCreateSubmissionRequest
  path?: never
  query?: never
  url: "/api/v1/submissions"
}

export type SubmissionServiceCreateSubmissionResponses = {
  /**
   * OK
   */
  200: SubmissionServiceSubmissionResponse
}

export type SubmissionServiceCreateSubmissionResponse =
  SubmissionServiceCreateSubmissionResponses[keyof SubmissionServiceCreateSubmissionResponses]

export type SubmissionServiceProvideFeedbackData = {
  body: SubmissionServiceSubmissionFeedbackRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/submissions/{id}/feedback"
}

export type SubmissionServiceProvideFeedbackResponses = {
  /**
   * OK
   */
  200: SubmissionServiceSubmissionResponse
}

export type SubmissionServiceProvideFeedbackResponse =
  SubmissionServiceProvideFeedbackResponses[keyof SubmissionServiceProvideFeedbackResponses]

export type SubmissionServiceGetSubmissionByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/submissions/{id}"
}

export type SubmissionServiceGetSubmissionByIdResponses = {
  /**
   * OK
   */
  200: SubmissionServiceSubmissionResponse
}

export type SubmissionServiceGetSubmissionByIdResponse =
  SubmissionServiceGetSubmissionByIdResponses[keyof SubmissionServiceGetSubmissionByIdResponses]

export type EvaluationServiceGetSupportedRuntimesData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/runtimes"
}

export type EvaluationServiceGetSupportedRuntimesErrors = {
  /**
   * Internal server error
   */
  500: Array<EvaluationServiceRuntimeResponse>
}

export type EvaluationServiceGetSupportedRuntimesError =
  EvaluationServiceGetSupportedRuntimesErrors[keyof EvaluationServiceGetSupportedRuntimesErrors]

export type EvaluationServiceGetSupportedRuntimesResponses = {
  /**
   * Successfully retrieved runtimes
   */
  200: Array<EvaluationServiceRuntimeResponse>
}

export type EvaluationServiceGetSupportedRuntimesResponse =
  EvaluationServiceGetSupportedRuntimesResponses[keyof EvaluationServiceGetSupportedRuntimesResponses]

export type SupportServiceListSessionsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page number (0-indexed)
     */
    page?: string
    /**
     * Number of items per page
     */
    size?: string
    /**
     * Sort by field(s). Format: field1,direction;field2,direction. Direction can be 'asc' or 'desc'. Multiple sort criteria separated by semicolon.
     */
    sort?: string
    userId?: string
    email?: string
    firstName?: string
    lastName?: string
    role?: string
    isActive?: boolean
  }
  url: "/api/v1/support/sessions"
}

export type SupportServiceListSessionsResponses = {
  /**
   * Successfully retrieved sessions
   */
  200: SupportServicePageResponseSupportSessionDto
}

export type SupportServiceListSessionsResponse =
  SupportServiceListSessionsResponses[keyof SupportServiceListSessionsResponses]

export type SupportServiceCreateSessionData = {
  body: SupportServiceCreateSupportSessionRequest
  path?: never
  query?: {
    userId?: string
    email?: string
    firstName?: string
    lastName?: string
    role?: string
    isActive?: boolean
  }
  url: "/api/v1/support/sessions"
}

export type SupportServiceCreateSessionErrors = {
  /**
   * Invalid request
   */
  400: SupportServiceSupportSessionDto
}

export type SupportServiceCreateSessionError =
  SupportServiceCreateSessionErrors[keyof SupportServiceCreateSessionErrors]

export type SupportServiceCreateSessionResponses = {
  /**
   * Session created successfully
   */
  201: SupportServiceSupportSessionDto
}

export type SupportServiceCreateSessionResponse =
  SupportServiceCreateSessionResponses[keyof SupportServiceCreateSessionResponses]

export type SupportServiceCloseSessionData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    userId?: string
    email?: string
    firstName?: string
    lastName?: string
    role?: string
    isActive?: boolean
  }
  url: "/api/v1/support/sessions/{id}/close"
}

export type SupportServiceCloseSessionErrors = {
  /**
   * Session already closed
   */
  400: SupportServiceSupportSessionDto
  /**
   * Access denied
   */
  403: SupportServiceSupportSessionDto
  /**
   * Session not found
   */
  404: SupportServiceSupportSessionDto
}

export type SupportServiceCloseSessionError = SupportServiceCloseSessionErrors[keyof SupportServiceCloseSessionErrors]

export type SupportServiceCloseSessionResponses = {
  /**
   * Session closed successfully
   */
  200: SupportServiceSupportSessionDto
}

export type SupportServiceCloseSessionResponse =
  SupportServiceCloseSessionResponses[keyof SupportServiceCloseSessionResponses]

export type SupportServiceGetSessionByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    userId?: string
    email?: string
    firstName?: string
    lastName?: string
    role?: string
    isActive?: boolean
  }
  url: "/api/v1/support/sessions/{id}"
}

export type SupportServiceGetSessionByIdErrors = {
  /**
   * Access denied
   */
  403: SupportServiceSupportSessionDto
  /**
   * Session not found
   */
  404: SupportServiceSupportSessionDto
}

export type SupportServiceGetSessionByIdError =
  SupportServiceGetSessionByIdErrors[keyof SupportServiceGetSessionByIdErrors]

export type SupportServiceGetSessionByIdResponses = {
  /**
   * Successfully retrieved session
   */
  200: SupportServiceSupportSessionDto
}

export type SupportServiceGetSessionByIdResponse =
  SupportServiceGetSessionByIdResponses[keyof SupportServiceGetSessionByIdResponses]
