// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

export type IdentityServiceUpdateProfileRequest = {
  firstName?: string
  lastName?: string
}

export type IdentityServiceUserResponse = {
  id?: string
  email?: string
  firstName?: string
  lastName?: string
  role?: "STUDENT" | "INSTRUCTOR" | "CONTENT_PROVIDER" | "ADMIN"
  isActive?: boolean
  isEmailVerified?: boolean
  createdAt?: Date
  updatedAt?: Date
}

export type IdentityServiceCreateUserRequest = {
  email: string
  password: string
  firstName: string
  lastName: string
  role?: "STUDENT" | "INSTRUCTOR" | "CONTENT_PROVIDER" | "ADMIN"
  isActive?: boolean
  isEmailVerified?: boolean
}

export type IdentityServiceChangePasswordRequest = {
  currentPassword: string
  newPassword: string
}

export type IdentityServiceTokenRequest = {
  token: string
}

export type IdentityServiceResetPasswordRequest = {
  token: string
  newPassword: string
}

export type IdentityServiceEmailRequest = {
  email: string
}

export type IdentityServiceRegisterRequest = {
  email: string
  password: string
  firstName: string
  lastName: string
}

export type IdentityServiceAuthResponse = {
  token?: string
  type?: string
  user?: IdentityServiceUserResponse
}

export type IdentityServiceLoginRequest = {
  email: string
  password: string
}

/**
 * Lớp bọc phản hồi phân trang
 */
export type IdentityServicePageResponseUserResponse = {
  /**
   * Danh sách phần tử trong trang hiện tại
   */
  content?: Array<IdentityServiceUserResponse>
  /**
   * Số trang hiện tại (bắt đầu từ 0)
   */
  pageNumber?: number
  /**
   * Số lượng phần tử mỗi trang
   */
  pageSize?: number
  /**
   * Tổng số phần tử trên tất cả các trang
   */
  totalElements?: bigint
  /**
   * Tổng số trang
   */
  totalPages?: number
  /**
   * Có phải trang đầu tiên không
   */
  first?: boolean
  /**
   * Có phải trang cuối cùng không
   */
  last?: boolean
  /**
   * Có trang tiếp theo không
   */
  hasNext?: boolean
  /**
   * Có trang trước đó không
   */
  hasPrevious?: boolean
}

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export type IdentityServiceProblemDetail = {
  /**
   * Loại lỗi (URI)
   */
  type?: unknown
  /**
   * Tiêu đề lỗi
   */
  title?: unknown
  /**
   * Mã trạng thái HTTP
   */
  status?: unknown
  /**
   * Mô tả chi tiết lỗi
   */
  detail?: unknown
  /**
   * Đường dẫn instance lỗi
   */
  instance?: unknown
}

export type ContentServiceCreateTutorialRequest = {
  title: string
  content: string
  tags?: Array<string>
}

export type ContentServiceTutorialResponse = {
  id?: string
  title?: string
  content?: string
  creatorId?: string
  createdAt?: Date
  updatedAt?: Date
  tags?: Array<string>
}

export type ContentServiceCreateSkillRequest = {
  name: string
  description?: string
}

export type ContentServiceSkillResponse = {
  id?: string
  name?: string
  description?: string
  createdAt?: Date
  updatedAt?: Date
}

export type ContentServiceCreateAssignmentRequest = {
  title: string
  description: string
  difficultyLevel: "EASY" | "MEDIUM" | "HARD"
  startDate?: Date
  dueDate?: Date
  maxScore: number
  languages: Array<string>
  testCases: Array<ContentServiceTestCase>
  skillIds?: Array<string>
  tutorialIds?: Array<string>
}

export type ContentServiceTestCase = {
  order?: number
  description?: string
  hidden?: boolean
  weight?: number
  input?: string
  output?: string
  timeout?: number
  memoryLimit?: number
}

export type ContentServiceAssignmentResponse = {
  id?: string
  title?: string
  description?: string
  difficultyLevel?: "EASY" | "MEDIUM" | "HARD"
  creatorId?: string
  createdAt?: Date
  updatedAt?: Date
  startDate?: Date
  dueDate?: Date
  maxScore?: number
  status?: "DRAFT" | "PUBLISHED" | "ARCHIVED"
  languages?: Array<string>
  testCases?: Array<ContentServiceTestCase>
  skills?: Array<ContentServiceSkillResponse>
  tutorials?: Array<ContentServiceTutorialResponse>
}

export type ContentServiceUpdateTutorialRequest = {
  title?: string
  content?: string
  tags?: Array<string>
}

export type ContentServiceUpdateSkillRequest = {
  name?: string
  description?: string
}

export type ContentServiceUpdateAssignmentRequest = {
  title?: string
  description?: string
  difficultyLevel?: "EASY" | "MEDIUM" | "HARD"
  startDate?: Date
  dueDate?: Date
  maxScore?: number
  languages?: Array<string>
  testCases?: Array<ContentServiceTestCase>
  skillIds?: Array<string>
  tutorialIds?: Array<string>
}

export type ContentServiceUpdateAssignmentScheduleRequest = {
  startDate: Date
  dueDate: Date
}

/**
 * Lớp bọc phản hồi phân trang
 */
export type ContentServicePageResponseTutorialResponse = {
  /**
   * Danh sách phần tử trong trang hiện tại
   */
  content?: Array<ContentServiceTutorialResponse>
  /**
   * Số trang hiện tại (bắt đầu từ 0)
   */
  pageNumber?: number
  /**
   * Số lượng phần tử mỗi trang
   */
  pageSize?: number
  /**
   * Tổng số phần tử trên tất cả các trang
   */
  totalElements?: bigint
  /**
   * Tổng số trang
   */
  totalPages?: number
  /**
   * Có phải trang đầu tiên không
   */
  first?: boolean
  /**
   * Có phải trang cuối cùng không
   */
  last?: boolean
  /**
   * Có trang tiếp theo không
   */
  hasNext?: boolean
  /**
   * Có trang trước đó không
   */
  hasPrevious?: boolean
}

/**
 * Lớp bọc phản hồi phân trang
 */
export type ContentServicePageResponseSkillResponse = {
  /**
   * Danh sách phần tử trong trang hiện tại
   */
  content?: Array<ContentServiceSkillResponse>
  /**
   * Số trang hiện tại (bắt đầu từ 0)
   */
  pageNumber?: number
  /**
   * Số lượng phần tử mỗi trang
   */
  pageSize?: number
  /**
   * Tổng số phần tử trên tất cả các trang
   */
  totalElements?: bigint
  /**
   * Tổng số trang
   */
  totalPages?: number
  /**
   * Có phải trang đầu tiên không
   */
  first?: boolean
  /**
   * Có phải trang cuối cùng không
   */
  last?: boolean
  /**
   * Có trang tiếp theo không
   */
  hasNext?: boolean
  /**
   * Có trang trước đó không
   */
  hasPrevious?: boolean
}

/**
 * Lớp bọc phản hồi phân trang
 */
export type ContentServicePageResponseAssignmentResponse = {
  /**
   * Danh sách phần tử trong trang hiện tại
   */
  content?: Array<ContentServiceAssignmentResponse>
  /**
   * Số trang hiện tại (bắt đầu từ 0)
   */
  pageNumber?: number
  /**
   * Số lượng phần tử mỗi trang
   */
  pageSize?: number
  /**
   * Tổng số phần tử trên tất cả các trang
   */
  totalElements?: bigint
  /**
   * Tổng số trang
   */
  totalPages?: number
  /**
   * Có phải trang đầu tiên không
   */
  first?: boolean
  /**
   * Có phải trang cuối cùng không
   */
  last?: boolean
  /**
   * Có trang tiếp theo không
   */
  hasNext?: boolean
  /**
   * Có trang trước đó không
   */
  hasPrevious?: boolean
}

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export type ContentServiceProblemDetail = {
  /**
   * Loại lỗi (URI)
   */
  type?: unknown
  /**
   * Tiêu đề lỗi
   */
  title?: unknown
  /**
   * Mã trạng thái HTTP
   */
  status?: unknown
  /**
   * Mô tả chi tiết lỗi
   */
  detail?: unknown
  /**
   * Đường dẫn instance lỗi
   */
  instance?: unknown
}

export type SubmissionServiceCreateSubmissionRequest = {
  assignmentId: string
  code: string
  language: string
}

export type SubmissionServiceSubmissionResponse = {
  id?: string
  assignmentId?: string
  studentId?: string
  submittedAt?: Date
  status?: "PENDING" | "EVALUATED" | "FAILED"
  code?: string
  language?: string
  result?: "PASSED" | "FAILED" | "PARTIAL"
  score?: number
  testCaseResults?: Array<SubmissionServiceTestCaseResultDto>
  evaluatedAt?: Date
  feedback?: string
}

export type SubmissionServiceTestCaseResultDto = {
  order?: number
  description?: string
  hidden?: boolean
  weight?: number
  input?: string
  output?: string
  timeout?: number
  memoryLimit?: number
  passed?: boolean
  actualOutput?: string
  errorMessage?: string
  executionTime?: number
  memoryUsed?: number
}

export type SubmissionServiceSubmissionFeedbackRequest = {
  feedback: string
}

/**
 * Lớp bọc phản hồi phân trang
 */
export type SubmissionServicePageResponseSubmissionResponse = {
  /**
   * Danh sách phần tử trong trang hiện tại
   */
  content?: Array<SubmissionServiceSubmissionResponse>
  /**
   * Số trang hiện tại (bắt đầu từ 0)
   */
  pageNumber?: number
  /**
   * Số lượng phần tử mỗi trang
   */
  pageSize?: number
  /**
   * Tổng số phần tử trên tất cả các trang
   */
  totalElements?: bigint
  /**
   * Tổng số trang
   */
  totalPages?: number
  /**
   * Có phải trang đầu tiên không
   */
  first?: boolean
  /**
   * Có phải trang cuối cùng không
   */
  last?: boolean
  /**
   * Có trang tiếp theo không
   */
  hasNext?: boolean
  /**
   * Có trang trước đó không
   */
  hasPrevious?: boolean
}

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export type SubmissionServiceProblemDetail = {
  /**
   * Loại lỗi (URI)
   */
  type?: unknown
  /**
   * Tiêu đề lỗi
   */
  title?: unknown
  /**
   * Mã trạng thái HTTP
   */
  status?: unknown
  /**
   * Mô tả chi tiết lỗi
   */
  detail?: unknown
  /**
   * Đường dẫn instance lỗi
   */
  instance?: unknown
}

/**
 * Thông tin runtime của ngôn ngữ lập trình được hỗ trợ
 */
export type EvaluationServiceRuntimeResponse = {
  /**
   * Tên ngôn ngữ lập trình
   */
  language?: string
  /**
   * Phiên bản của runtime
   */
  version?: string
  /**
   * Danh sách tên thay thế cho ngôn ngữ
   */
  aliases?: Array<string>
  /**
   * Tên runtime, chỉ cung cấp nếu có nhiều runtime thay thế
   */
  runtime?: string
}

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export type EvaluationServiceProblemDetail = {
  /**
   * Loại lỗi (URI)
   */
  type?: unknown
  /**
   * Tiêu đề lỗi
   */
  title?: unknown
  /**
   * Mã trạng thái HTTP
   */
  status?: unknown
  /**
   * Mô tả chi tiết lỗi
   */
  detail?: unknown
  /**
   * Đường dẫn instance lỗi
   */
  instance?: unknown
}

export type SupportServiceCreateSupportSessionRequest = {
  initialMessage: string
}

export type SupportServiceSupportMessageDto = {
  id?: string
  senderId?: string
  content?: string
  isInstructor?: boolean
  isRead?: boolean
  createdAt?: Date
}

export type SupportServiceSupportSessionDto = {
  id?: string
  studentId?: string
  instructorId?: string
  isClosed?: boolean
  createdAt?: Date
  closedAt?: Date
  messages?: Array<SupportServiceSupportMessageDto>
}

/**
 * Lớp bọc phản hồi phân trang
 */
export type SupportServicePageResponseSupportSessionDto = {
  /**
   * Danh sách phần tử trong trang hiện tại
   */
  content?: Array<SupportServiceSupportSessionDto>
  /**
   * Số trang hiện tại (bắt đầu từ 0)
   */
  pageNumber?: number
  /**
   * Số lượng phần tử mỗi trang
   */
  pageSize?: number
  /**
   * Tổng số phần tử trên tất cả các trang
   */
  totalElements?: bigint
  /**
   * Tổng số trang
   */
  totalPages?: number
  /**
   * Có phải trang đầu tiên không
   */
  first?: boolean
  /**
   * Có phải trang cuối cùng không
   */
  last?: boolean
  /**
   * Có trang tiếp theo không
   */
  hasNext?: boolean
  /**
   * Có trang trước đó không
   */
  hasPrevious?: boolean
}

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export type SupportServiceProblemDetail = {
  /**
   * Loại lỗi (URI)
   */
  type?: unknown
  /**
   * Tiêu đề lỗi
   */
  title?: unknown
  /**
   * Mã trạng thái HTTP
   */
  status?: unknown
  /**
   * Mô tả chi tiết lỗi
   */
  detail?: unknown
  /**
   * Đường dẫn instance lỗi
   */
  instance?: unknown
}

export type NotificationServiceNotificationPreferencesRequest = {
  emailEnabled?: boolean
  pushEnabled?: boolean
  emailAssignmentPublished?: boolean
  emailSubmissionEvaluated?: boolean
  pushAssignmentPublished?: boolean
  pushSubmissionEvaluated?: boolean
}

export type NotificationServiceNotificationPreferencesResponse = {
  id?: string
  userId?: string
  emailEnabled?: boolean
  pushEnabled?: boolean
  emailAssignmentPublished?: boolean
  emailSubmissionEvaluated?: boolean
  pushAssignmentPublished?: boolean
  pushSubmissionEvaluated?: boolean
  createdAt?: Date
  updatedAt?: Date
}

export type NotificationServiceRegisterDeviceRequest = {
  token: string
  deviceType: string
  userAgent?: string
}

export type NotificationServiceDeviceTokenResponse = {
  id?: string
  token?: string
  deviceType?: string
  userAgent?: string
  isActive?: boolean
  createdAt?: Date
  updatedAt?: Date
}

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export type NotificationServiceProblemDetail = {
  /**
   * Loại lỗi (URI)
   */
  type?: unknown
  /**
   * Tiêu đề lỗi
   */
  title?: unknown
  /**
   * Mã trạng thái HTTP
   */
  status?: unknown
  /**
   * Mô tả chi tiết lỗi
   */
  detail?: unknown
  /**
   * Đường dẫn instance lỗi
   */
  instance?: unknown
}

export type IdentityServiceDeactivateUserData = {
  body?: never
  path: {
    userId: string
  }
  query?: never
  url: "/api/v1/users/{userId}/deactivate"
}

export type IdentityServiceDeactivateUserErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceDeactivateUserError =
  IdentityServiceDeactivateUserErrors[keyof IdentityServiceDeactivateUserErrors]

export type IdentityServiceDeactivateUserResponses = {
  /**
   * No Content
   */
  204: void
}

export type IdentityServiceDeactivateUserResponse =
  IdentityServiceDeactivateUserResponses[keyof IdentityServiceDeactivateUserResponses]

export type IdentityServiceActivateUserData = {
  body?: never
  path: {
    userId: string
  }
  query?: never
  url: "/api/v1/users/{userId}/activate"
}

export type IdentityServiceActivateUserErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceActivateUserError =
  IdentityServiceActivateUserErrors[keyof IdentityServiceActivateUserErrors]

export type IdentityServiceActivateUserResponses = {
  /**
   * No Content
   */
  204: void
}

export type IdentityServiceActivateUserResponse =
  IdentityServiceActivateUserResponses[keyof IdentityServiceActivateUserResponses]

export type IdentityServiceGetCurrentUserData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type IdentityServiceGetCurrentUserErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceGetCurrentUserError =
  IdentityServiceGetCurrentUserErrors[keyof IdentityServiceGetCurrentUserErrors]

export type IdentityServiceGetCurrentUserResponses = {
  /**
   * OK
   */
  200: IdentityServiceUserResponse
}

export type IdentityServiceGetCurrentUserResponse =
  IdentityServiceGetCurrentUserResponses[keyof IdentityServiceGetCurrentUserResponses]

export type IdentityServiceUpdateCurrentUserProfileData = {
  body: IdentityServiceUpdateProfileRequest
  path?: never
  query?: never
  url: "/api/v1/users/me"
}

export type IdentityServiceUpdateCurrentUserProfileErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceUpdateCurrentUserProfileError =
  IdentityServiceUpdateCurrentUserProfileErrors[keyof IdentityServiceUpdateCurrentUserProfileErrors]

export type IdentityServiceUpdateCurrentUserProfileResponses = {
  /**
   * OK
   */
  200: IdentityServiceUserResponse
}

export type IdentityServiceUpdateCurrentUserProfileResponse =
  IdentityServiceUpdateCurrentUserProfileResponses[keyof IdentityServiceUpdateCurrentUserProfileResponses]

export type IdentityServiceGetAllUsersData = {
  body?: never
  path?: never
  query?: {
    /**
     * Số trang (bắt đầu từ 0)
     */
    page?: string
    /**
     * Số lượng phần tử mỗi trang
     */
    size?: string
  }
  url: "/api/v1/users"
}

export type IdentityServiceGetAllUsersErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceGetAllUsersError = IdentityServiceGetAllUsersErrors[keyof IdentityServiceGetAllUsersErrors]

export type IdentityServiceGetAllUsersResponses = {
  /**
   * OK
   */
  200: IdentityServicePageResponseUserResponse
}

export type IdentityServiceGetAllUsersResponse =
  IdentityServiceGetAllUsersResponses[keyof IdentityServiceGetAllUsersResponses]

export type IdentityServiceCreateUserData = {
  body: IdentityServiceCreateUserRequest
  path?: never
  query?: never
  url: "/api/v1/users"
}

export type IdentityServiceCreateUserErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceCreateUserError = IdentityServiceCreateUserErrors[keyof IdentityServiceCreateUserErrors]

export type IdentityServiceCreateUserResponses = {
  /**
   * Created
   */
  201: IdentityServiceUserResponse
}

export type IdentityServiceCreateUserResponse =
  IdentityServiceCreateUserResponses[keyof IdentityServiceCreateUserResponses]

export type IdentityServiceChangePasswordData = {
  body: IdentityServiceChangePasswordRequest
  path?: never
  query?: never
  url: "/api/v1/users/me/change-password"
}

export type IdentityServiceChangePasswordErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceChangePasswordError =
  IdentityServiceChangePasswordErrors[keyof IdentityServiceChangePasswordErrors]

export type IdentityServiceChangePasswordResponses = {
  /**
   * No Content
   */
  204: void
}

export type IdentityServiceChangePasswordResponse =
  IdentityServiceChangePasswordResponses[keyof IdentityServiceChangePasswordResponses]

export type IdentityServiceVerifyEmailData = {
  body: IdentityServiceTokenRequest
  path?: never
  query?: never
  url: "/api/auth/verify-email"
}

export type IdentityServiceVerifyEmailErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceVerifyEmailError = IdentityServiceVerifyEmailErrors[keyof IdentityServiceVerifyEmailErrors]

export type IdentityServiceVerifyEmailResponses = {
  /**
   * No Content
   */
  204: void
}

export type IdentityServiceVerifyEmailResponse =
  IdentityServiceVerifyEmailResponses[keyof IdentityServiceVerifyEmailResponses]

export type IdentityServiceResetPasswordData = {
  body: IdentityServiceResetPasswordRequest
  path?: never
  query?: never
  url: "/api/auth/reset-password"
}

export type IdentityServiceResetPasswordErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceResetPasswordError =
  IdentityServiceResetPasswordErrors[keyof IdentityServiceResetPasswordErrors]

export type IdentityServiceResetPasswordResponses = {
  /**
   * No Content
   */
  204: void
}

export type IdentityServiceResetPasswordResponse =
  IdentityServiceResetPasswordResponses[keyof IdentityServiceResetPasswordResponses]

export type IdentityServiceResendVerificationEmailData = {
  body: IdentityServiceEmailRequest
  path?: never
  query?: never
  url: "/api/auth/resend-verification"
}

export type IdentityServiceResendVerificationEmailErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceResendVerificationEmailError =
  IdentityServiceResendVerificationEmailErrors[keyof IdentityServiceResendVerificationEmailErrors]

export type IdentityServiceResendVerificationEmailResponses = {
  /**
   * No Content
   */
  204: void
}

export type IdentityServiceResendVerificationEmailResponse =
  IdentityServiceResendVerificationEmailResponses[keyof IdentityServiceResendVerificationEmailResponses]

export type IdentityServiceRegisterData = {
  body: IdentityServiceRegisterRequest
  path?: never
  query?: never
  url: "/api/auth/register"
}

export type IdentityServiceRegisterErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceRegisterError = IdentityServiceRegisterErrors[keyof IdentityServiceRegisterErrors]

export type IdentityServiceRegisterResponses = {
  /**
   * Created
   */
  201: IdentityServiceAuthResponse
}

export type IdentityServiceRegisterResponse = IdentityServiceRegisterResponses[keyof IdentityServiceRegisterResponses]

export type IdentityServiceLoginData = {
  body: IdentityServiceLoginRequest
  path?: never
  query?: never
  url: "/api/auth/login"
}

export type IdentityServiceLoginErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceLoginError = IdentityServiceLoginErrors[keyof IdentityServiceLoginErrors]

export type IdentityServiceLoginResponses = {
  /**
   * OK
   */
  200: IdentityServiceAuthResponse
}

export type IdentityServiceLoginResponse = IdentityServiceLoginResponses[keyof IdentityServiceLoginResponses]

export type IdentityServiceRequestPasswordResetData = {
  body: IdentityServiceEmailRequest
  path?: never
  query?: never
  url: "/api/auth/forgot-password"
}

export type IdentityServiceRequestPasswordResetErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceRequestPasswordResetError =
  IdentityServiceRequestPasswordResetErrors[keyof IdentityServiceRequestPasswordResetErrors]

export type IdentityServiceRequestPasswordResetResponses = {
  /**
   * No Content
   */
  204: void
}

export type IdentityServiceRequestPasswordResetResponse =
  IdentityServiceRequestPasswordResetResponses[keyof IdentityServiceRequestPasswordResetResponses]

export type IdentityServiceDeleteUserData = {
  body?: never
  path: {
    userId: string
  }
  query?: never
  url: "/api/v1/users/{userId}"
}

export type IdentityServiceDeleteUserErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceDeleteUserError = IdentityServiceDeleteUserErrors[keyof IdentityServiceDeleteUserErrors]

export type IdentityServiceDeleteUserResponses = {
  /**
   * No Content
   */
  204: void
}

export type IdentityServiceDeleteUserResponse =
  IdentityServiceDeleteUserResponses[keyof IdentityServiceDeleteUserResponses]

export type IdentityServiceGetUserByIdData = {
  body?: never
  path: {
    userId: string
  }
  query?: never
  url: "/api/v1/users/{userId}"
}

export type IdentityServiceGetUserByIdErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceGetUserByIdError = IdentityServiceGetUserByIdErrors[keyof IdentityServiceGetUserByIdErrors]

export type IdentityServiceGetUserByIdResponses = {
  /**
   * OK
   */
  200: IdentityServiceUserResponse
}

export type IdentityServiceGetUserByIdResponse =
  IdentityServiceGetUserByIdResponses[keyof IdentityServiceGetUserByIdResponses]

export type IdentityServiceGetUsersByRoleData = {
  body?: never
  path: {
    role: "STUDENT" | "INSTRUCTOR" | "CONTENT_PROVIDER" | "ADMIN"
  }
  query?: {
    /**
     * Số trang (bắt đầu từ 0)
     */
    page?: string
    /**
     * Số lượng phần tử mỗi trang
     */
    size?: string
  }
  url: "/api/v1/users/role/{role}"
}

export type IdentityServiceGetUsersByRoleErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: IdentityServiceProblemDetail
}

export type IdentityServiceGetUsersByRoleError =
  IdentityServiceGetUsersByRoleErrors[keyof IdentityServiceGetUsersByRoleErrors]

export type IdentityServiceGetUsersByRoleResponses = {
  /**
   * OK
   */
  200: IdentityServicePageResponseUserResponse
}

export type IdentityServiceGetUsersByRoleResponse =
  IdentityServiceGetUsersByRoleResponses[keyof IdentityServiceGetUsersByRoleResponses]

export type ContentServiceGetAllTutorialsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Số trang (bắt đầu từ 0)
     */
    page?: string
    /**
     * Số lượng phần tử mỗi trang
     */
    size?: string
  }
  url: "/api/v1/tutorials"
}

export type ContentServiceGetAllTutorialsErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceGetAllTutorialsError =
  ContentServiceGetAllTutorialsErrors[keyof ContentServiceGetAllTutorialsErrors]

export type ContentServiceGetAllTutorialsResponses = {
  /**
   * OK
   */
  200: ContentServicePageResponseTutorialResponse
}

export type ContentServiceGetAllTutorialsResponse =
  ContentServiceGetAllTutorialsResponses[keyof ContentServiceGetAllTutorialsResponses]

export type ContentServiceCreateTutorialData = {
  body: ContentServiceCreateTutorialRequest
  path?: never
  query?: never
  url: "/api/v1/tutorials"
}

export type ContentServiceCreateTutorialErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceCreateTutorialError =
  ContentServiceCreateTutorialErrors[keyof ContentServiceCreateTutorialErrors]

export type ContentServiceCreateTutorialResponses = {
  /**
   * Created
   */
  201: ContentServiceTutorialResponse
}

export type ContentServiceCreateTutorialResponse =
  ContentServiceCreateTutorialResponses[keyof ContentServiceCreateTutorialResponses]

export type ContentServiceGetAllSkillsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Số trang (bắt đầu từ 0)
     */
    page?: string
    /**
     * Số lượng phần tử mỗi trang
     */
    size?: string
  }
  url: "/api/v1/skills"
}

export type ContentServiceGetAllSkillsErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceGetAllSkillsError = ContentServiceGetAllSkillsErrors[keyof ContentServiceGetAllSkillsErrors]

export type ContentServiceGetAllSkillsResponses = {
  /**
   * OK
   */
  200: ContentServicePageResponseSkillResponse
}

export type ContentServiceGetAllSkillsResponse =
  ContentServiceGetAllSkillsResponses[keyof ContentServiceGetAllSkillsResponses]

export type ContentServiceCreateSkillData = {
  body: ContentServiceCreateSkillRequest
  path?: never
  query?: never
  url: "/api/v1/skills"
}

export type ContentServiceCreateSkillErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceCreateSkillError = ContentServiceCreateSkillErrors[keyof ContentServiceCreateSkillErrors]

export type ContentServiceCreateSkillResponses = {
  /**
   * Created
   */
  201: ContentServiceSkillResponse
}

export type ContentServiceCreateSkillResponse =
  ContentServiceCreateSkillResponses[keyof ContentServiceCreateSkillResponses]

export type ContentServiceGetAllAssignmentsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Số trang (bắt đầu từ 0)
     */
    page?: string
    /**
     * Số lượng phần tử mỗi trang
     */
    size?: string
  }
  url: "/api/v1/assignments"
}

export type ContentServiceGetAllAssignmentsErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceGetAllAssignmentsError =
  ContentServiceGetAllAssignmentsErrors[keyof ContentServiceGetAllAssignmentsErrors]

export type ContentServiceGetAllAssignmentsResponses = {
  /**
   * OK
   */
  200: ContentServicePageResponseAssignmentResponse
}

export type ContentServiceGetAllAssignmentsResponse =
  ContentServiceGetAllAssignmentsResponses[keyof ContentServiceGetAllAssignmentsResponses]

export type ContentServiceCreateAssignmentData = {
  body: ContentServiceCreateAssignmentRequest
  path?: never
  query?: never
  url: "/api/v1/assignments"
}

export type ContentServiceCreateAssignmentErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceCreateAssignmentError =
  ContentServiceCreateAssignmentErrors[keyof ContentServiceCreateAssignmentErrors]

export type ContentServiceCreateAssignmentResponses = {
  /**
   * Created
   */
  201: ContentServiceAssignmentResponse
}

export type ContentServiceCreateAssignmentResponse =
  ContentServiceCreateAssignmentResponses[keyof ContentServiceCreateAssignmentResponses]

export type ContentServicePublishAssignmentData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}/publish"
}

export type ContentServicePublishAssignmentErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServicePublishAssignmentError =
  ContentServicePublishAssignmentErrors[keyof ContentServicePublishAssignmentErrors]

export type ContentServicePublishAssignmentResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServicePublishAssignmentResponse =
  ContentServicePublishAssignmentResponses[keyof ContentServicePublishAssignmentResponses]

export type ContentServiceArchiveAssignmentData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}/archive"
}

export type ContentServiceArchiveAssignmentErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceArchiveAssignmentError =
  ContentServiceArchiveAssignmentErrors[keyof ContentServiceArchiveAssignmentErrors]

export type ContentServiceArchiveAssignmentResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServiceArchiveAssignmentResponse =
  ContentServiceArchiveAssignmentResponses[keyof ContentServiceArchiveAssignmentResponses]

export type ContentServiceDeleteTutorialData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/tutorials/{id}"
}

export type ContentServiceDeleteTutorialErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceDeleteTutorialError =
  ContentServiceDeleteTutorialErrors[keyof ContentServiceDeleteTutorialErrors]

export type ContentServiceDeleteTutorialResponses = {
  /**
   * No Content
   */
  204: void
}

export type ContentServiceDeleteTutorialResponse =
  ContentServiceDeleteTutorialResponses[keyof ContentServiceDeleteTutorialResponses]

export type ContentServiceGetTutorialByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/tutorials/{id}"
}

export type ContentServiceGetTutorialByIdErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceGetTutorialByIdError =
  ContentServiceGetTutorialByIdErrors[keyof ContentServiceGetTutorialByIdErrors]

export type ContentServiceGetTutorialByIdResponses = {
  /**
   * OK
   */
  200: ContentServiceTutorialResponse
}

export type ContentServiceGetTutorialByIdResponse =
  ContentServiceGetTutorialByIdResponses[keyof ContentServiceGetTutorialByIdResponses]

export type ContentServiceUpdateTutorialData = {
  body: ContentServiceUpdateTutorialRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/tutorials/{id}"
}

export type ContentServiceUpdateTutorialErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceUpdateTutorialError =
  ContentServiceUpdateTutorialErrors[keyof ContentServiceUpdateTutorialErrors]

export type ContentServiceUpdateTutorialResponses = {
  /**
   * OK
   */
  200: ContentServiceTutorialResponse
}

export type ContentServiceUpdateTutorialResponse =
  ContentServiceUpdateTutorialResponses[keyof ContentServiceUpdateTutorialResponses]

export type ContentServiceDeleteSkillData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/skills/{id}"
}

export type ContentServiceDeleteSkillErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceDeleteSkillError = ContentServiceDeleteSkillErrors[keyof ContentServiceDeleteSkillErrors]

export type ContentServiceDeleteSkillResponses = {
  /**
   * No Content
   */
  204: void
}

export type ContentServiceDeleteSkillResponse =
  ContentServiceDeleteSkillResponses[keyof ContentServiceDeleteSkillResponses]

export type ContentServiceGetSkillByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/skills/{id}"
}

export type ContentServiceGetSkillByIdErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceGetSkillByIdError = ContentServiceGetSkillByIdErrors[keyof ContentServiceGetSkillByIdErrors]

export type ContentServiceGetSkillByIdResponses = {
  /**
   * OK
   */
  200: ContentServiceSkillResponse
}

export type ContentServiceGetSkillByIdResponse =
  ContentServiceGetSkillByIdResponses[keyof ContentServiceGetSkillByIdResponses]

export type ContentServiceUpdateSkillData = {
  body: ContentServiceUpdateSkillRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/skills/{id}"
}

export type ContentServiceUpdateSkillErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceUpdateSkillError = ContentServiceUpdateSkillErrors[keyof ContentServiceUpdateSkillErrors]

export type ContentServiceUpdateSkillResponses = {
  /**
   * OK
   */
  200: ContentServiceSkillResponse
}

export type ContentServiceUpdateSkillResponse =
  ContentServiceUpdateSkillResponses[keyof ContentServiceUpdateSkillResponses]

export type ContentServiceDeleteAssignmentData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}"
}

export type ContentServiceDeleteAssignmentErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceDeleteAssignmentError =
  ContentServiceDeleteAssignmentErrors[keyof ContentServiceDeleteAssignmentErrors]

export type ContentServiceDeleteAssignmentResponses = {
  /**
   * No Content
   */
  204: void
}

export type ContentServiceDeleteAssignmentResponse =
  ContentServiceDeleteAssignmentResponses[keyof ContentServiceDeleteAssignmentResponses]

export type ContentServiceGetAssignmentByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}"
}

export type ContentServiceGetAssignmentByIdErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceGetAssignmentByIdError =
  ContentServiceGetAssignmentByIdErrors[keyof ContentServiceGetAssignmentByIdErrors]

export type ContentServiceGetAssignmentByIdResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServiceGetAssignmentByIdResponse =
  ContentServiceGetAssignmentByIdResponses[keyof ContentServiceGetAssignmentByIdResponses]

export type ContentServiceUpdateAssignmentData = {
  body: ContentServiceUpdateAssignmentRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}"
}

export type ContentServiceUpdateAssignmentErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceUpdateAssignmentError =
  ContentServiceUpdateAssignmentErrors[keyof ContentServiceUpdateAssignmentErrors]

export type ContentServiceUpdateAssignmentResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServiceUpdateAssignmentResponse =
  ContentServiceUpdateAssignmentResponses[keyof ContentServiceUpdateAssignmentResponses]

export type ContentServiceUpdateAssignmentScheduleData = {
  body: ContentServiceUpdateAssignmentScheduleRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/assignments/{id}/schedule"
}

export type ContentServiceUpdateAssignmentScheduleErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: ContentServiceProblemDetail
}

export type ContentServiceUpdateAssignmentScheduleError =
  ContentServiceUpdateAssignmentScheduleErrors[keyof ContentServiceUpdateAssignmentScheduleErrors]

export type ContentServiceUpdateAssignmentScheduleResponses = {
  /**
   * OK
   */
  200: ContentServiceAssignmentResponse
}

export type ContentServiceUpdateAssignmentScheduleResponse =
  ContentServiceUpdateAssignmentScheduleResponses[keyof ContentServiceUpdateAssignmentScheduleResponses]

export type SubmissionServiceGetAllSubmissionsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Lọc theo ID bài tập (chỉ giảng viên)
     */
    assignmentId?: string
    /**
     * Lọc theo ID sinh viên (chỉ giảng viên)
     */
    studentId?: string
    /**
     * Lọc theo trạng thái
     */
    status?: "PENDING" | "EVALUATED" | "FAILED"
    /**
     * Số trang (bắt đầu từ 0)
     */
    page?: string
    /**
     * Số lượng phần tử mỗi trang
     */
    size?: string
  }
  url: "/api/v1/submissions"
}

export type SubmissionServiceGetAllSubmissionsErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: SubmissionServiceProblemDetail
}

export type SubmissionServiceGetAllSubmissionsError =
  SubmissionServiceGetAllSubmissionsErrors[keyof SubmissionServiceGetAllSubmissionsErrors]

export type SubmissionServiceGetAllSubmissionsResponses = {
  /**
   * OK
   */
  200: SubmissionServicePageResponseSubmissionResponse
}

export type SubmissionServiceGetAllSubmissionsResponse =
  SubmissionServiceGetAllSubmissionsResponses[keyof SubmissionServiceGetAllSubmissionsResponses]

export type SubmissionServiceCreateSubmissionData = {
  body: SubmissionServiceCreateSubmissionRequest
  path?: never
  query?: never
  url: "/api/v1/submissions"
}

export type SubmissionServiceCreateSubmissionErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: SubmissionServiceProblemDetail
}

export type SubmissionServiceCreateSubmissionError =
  SubmissionServiceCreateSubmissionErrors[keyof SubmissionServiceCreateSubmissionErrors]

export type SubmissionServiceCreateSubmissionResponses = {
  /**
   * Created
   */
  201: SubmissionServiceSubmissionResponse
}

export type SubmissionServiceCreateSubmissionResponse =
  SubmissionServiceCreateSubmissionResponses[keyof SubmissionServiceCreateSubmissionResponses]

export type SubmissionServiceProvideFeedbackData = {
  body: SubmissionServiceSubmissionFeedbackRequest
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/submissions/{id}/feedback"
}

export type SubmissionServiceProvideFeedbackErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: SubmissionServiceProblemDetail
}

export type SubmissionServiceProvideFeedbackError =
  SubmissionServiceProvideFeedbackErrors[keyof SubmissionServiceProvideFeedbackErrors]

export type SubmissionServiceProvideFeedbackResponses = {
  /**
   * OK
   */
  200: SubmissionServiceSubmissionResponse
}

export type SubmissionServiceProvideFeedbackResponse =
  SubmissionServiceProvideFeedbackResponses[keyof SubmissionServiceProvideFeedbackResponses]

export type SubmissionServiceGetSubmissionByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: "/api/v1/submissions/{id}"
}

export type SubmissionServiceGetSubmissionByIdErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: SubmissionServiceProblemDetail
}

export type SubmissionServiceGetSubmissionByIdError =
  SubmissionServiceGetSubmissionByIdErrors[keyof SubmissionServiceGetSubmissionByIdErrors]

export type SubmissionServiceGetSubmissionByIdResponses = {
  /**
   * OK
   */
  200: SubmissionServiceSubmissionResponse
}

export type SubmissionServiceGetSubmissionByIdResponse =
  SubmissionServiceGetSubmissionByIdResponses[keyof SubmissionServiceGetSubmissionByIdResponses]

export type EvaluationServiceGetSupportedRuntimesData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/runtimes"
}

export type EvaluationServiceGetSupportedRuntimesErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: EvaluationServiceProblemDetail
}

export type EvaluationServiceGetSupportedRuntimesError =
  EvaluationServiceGetSupportedRuntimesErrors[keyof EvaluationServiceGetSupportedRuntimesErrors]

export type EvaluationServiceGetSupportedRuntimesResponses = {
  /**
   * OK
   */
  200: Array<EvaluationServiceRuntimeResponse>
}

export type EvaluationServiceGetSupportedRuntimesResponse =
  EvaluationServiceGetSupportedRuntimesResponses[keyof EvaluationServiceGetSupportedRuntimesResponses]

export type SupportServiceListSessionsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Số trang (bắt đầu từ 0)
     */
    page?: string
    /**
     * Số lượng phần tử mỗi trang
     */
    size?: string
    userId?: string
    email?: string
    firstName?: string
    lastName?: string
    role?: string
    isActive?: boolean
  }
  url: "/api/v1/support/sessions"
}

export type SupportServiceListSessionsErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: SupportServiceProblemDetail
}

export type SupportServiceListSessionsError = SupportServiceListSessionsErrors[keyof SupportServiceListSessionsErrors]

export type SupportServiceListSessionsResponses = {
  /**
   * OK
   */
  200: SupportServicePageResponseSupportSessionDto
}

export type SupportServiceListSessionsResponse =
  SupportServiceListSessionsResponses[keyof SupportServiceListSessionsResponses]

export type SupportServiceCreateSessionData = {
  body: SupportServiceCreateSupportSessionRequest
  path?: never
  query?: {
    userId?: string
    email?: string
    firstName?: string
    lastName?: string
    role?: string
    isActive?: boolean
  }
  url: "/api/v1/support/sessions"
}

export type SupportServiceCreateSessionErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: SupportServiceProblemDetail
}

export type SupportServiceCreateSessionError =
  SupportServiceCreateSessionErrors[keyof SupportServiceCreateSessionErrors]

export type SupportServiceCreateSessionResponses = {
  /**
   * Created
   */
  201: SupportServiceSupportSessionDto
}

export type SupportServiceCreateSessionResponse =
  SupportServiceCreateSessionResponses[keyof SupportServiceCreateSessionResponses]

export type SupportServiceCloseSessionData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    userId?: string
    email?: string
    firstName?: string
    lastName?: string
    role?: string
    isActive?: boolean
  }
  url: "/api/v1/support/sessions/{id}/close"
}

export type SupportServiceCloseSessionErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: SupportServiceProblemDetail
}

export type SupportServiceCloseSessionError = SupportServiceCloseSessionErrors[keyof SupportServiceCloseSessionErrors]

export type SupportServiceCloseSessionResponses = {
  /**
   * OK
   */
  200: SupportServiceSupportSessionDto
}

export type SupportServiceCloseSessionResponse =
  SupportServiceCloseSessionResponses[keyof SupportServiceCloseSessionResponses]

export type SupportServiceGetSessionByIdData = {
  body?: never
  path: {
    id: string
  }
  query?: {
    userId?: string
    email?: string
    firstName?: string
    lastName?: string
    role?: string
    isActive?: boolean
  }
  url: "/api/v1/support/sessions/{id}"
}

export type SupportServiceGetSessionByIdErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: SupportServiceProblemDetail
}

export type SupportServiceGetSessionByIdError =
  SupportServiceGetSessionByIdErrors[keyof SupportServiceGetSessionByIdErrors]

export type SupportServiceGetSessionByIdResponses = {
  /**
   * OK
   */
  200: SupportServiceSupportSessionDto
}

export type SupportServiceGetSessionByIdResponse =
  SupportServiceGetSessionByIdResponses[keyof SupportServiceGetSessionByIdResponses]

export type NotificationServiceGetPreferencesData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/preferences"
}

export type NotificationServiceGetPreferencesErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: NotificationServiceProblemDetail
}

export type NotificationServiceGetPreferencesError =
  NotificationServiceGetPreferencesErrors[keyof NotificationServiceGetPreferencesErrors]

export type NotificationServiceGetPreferencesResponses = {
  /**
   * OK
   */
  200: NotificationServiceNotificationPreferencesResponse
}

export type NotificationServiceGetPreferencesResponse =
  NotificationServiceGetPreferencesResponses[keyof NotificationServiceGetPreferencesResponses]

export type NotificationServiceUpdatePreferencesData = {
  body: NotificationServiceNotificationPreferencesRequest
  path?: never
  query?: never
  url: "/api/v1/preferences"
}

export type NotificationServiceUpdatePreferencesErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: NotificationServiceProblemDetail
}

export type NotificationServiceUpdatePreferencesError =
  NotificationServiceUpdatePreferencesErrors[keyof NotificationServiceUpdatePreferencesErrors]

export type NotificationServiceUpdatePreferencesResponses = {
  /**
   * OK
   */
  200: NotificationServiceNotificationPreferencesResponse
}

export type NotificationServiceUpdatePreferencesResponse =
  NotificationServiceUpdatePreferencesResponses[keyof NotificationServiceUpdatePreferencesResponses]

export type NotificationServiceRegisterDeviceData = {
  body: NotificationServiceRegisterDeviceRequest
  path?: never
  query?: never
  url: "/api/v1/devices/register"
}

export type NotificationServiceRegisterDeviceErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: NotificationServiceProblemDetail
}

export type NotificationServiceRegisterDeviceError =
  NotificationServiceRegisterDeviceErrors[keyof NotificationServiceRegisterDeviceErrors]

export type NotificationServiceRegisterDeviceResponses = {
  /**
   * Created
   */
  201: NotificationServiceDeviceTokenResponse
}

export type NotificationServiceRegisterDeviceResponse =
  NotificationServiceRegisterDeviceResponses[keyof NotificationServiceRegisterDeviceResponses]

export type NotificationServiceGetUserDevicesData = {
  body?: never
  path?: never
  query?: never
  url: "/api/v1/devices"
}

export type NotificationServiceGetUserDevicesErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: NotificationServiceProblemDetail
}

export type NotificationServiceGetUserDevicesError =
  NotificationServiceGetUserDevicesErrors[keyof NotificationServiceGetUserDevicesErrors]

export type NotificationServiceGetUserDevicesResponses = {
  /**
   * OK
   */
  200: Array<NotificationServiceDeviceTokenResponse>
}

export type NotificationServiceGetUserDevicesResponse =
  NotificationServiceGetUserDevicesResponses[keyof NotificationServiceGetUserDevicesResponses]

export type NotificationServiceRemoveDeviceData = {
  body?: never
  path: {
    token: string
  }
  query?: never
  url: "/api/v1/devices/{token}"
}

export type NotificationServiceRemoveDeviceErrors = {
  /**
   * Phản hồi lỗi mặc định
   */
  default: NotificationServiceProblemDetail
}

export type NotificationServiceRemoveDeviceError =
  NotificationServiceRemoveDeviceErrors[keyof NotificationServiceRemoveDeviceErrors]

export type NotificationServiceRemoveDeviceResponses = {
  /**
   * No Content
   */
  204: void
}

export type NotificationServiceRemoveDeviceResponse =
  NotificationServiceRemoveDeviceResponses[keyof NotificationServiceRemoveDeviceResponses]
