// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod"

export const zIdentityServiceCreateUserRequest = z.object({
  email: z.email().min(1),
  password: z.string().min(8).max(2147483647),
  firstName: z.string().min(0).max(100),
  lastName: z.string().min(0).max(100),
  role: z.optional(z.enum(["STUDENT", "INSTRUCTOR", "CONTENT_PROVIDER", "ADMIN"])),
  isActive: z.optional(z.boolean()),
  isEmailVerified: z.optional(z.boolean()),
})

export const zIdentityServiceUserResponse = z.object({
  id: z.optional(z.uuid()),
  email: z.optional(z.string()),
  firstName: z.optional(z.string()),
  lastName: z.optional(z.string()),
  role: z.optional(z.enum(["STUDENT", "INSTRUCTOR", "CONTENT_PROVIDER", "ADMIN"])),
  isActive: z.optional(z.boolean()),
  isEmailVerified: z.optional(z.boolean()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
})

export const zIdentityServiceChangePasswordRequest = z.object({
  currentPassword: z.string().min(1),
  newPassword: z.string().min(8).max(2147483647),
})

export const zIdentityServiceTokenRequest = z.object({
  token: z.string().min(1),
})

export const zIdentityServiceResetPasswordRequest = z.object({
  token: z.string().min(1),
  newPassword: z.string().min(8).max(2147483647),
})

export const zIdentityServiceEmailRequest = z.object({
  email: z.email().min(1),
})

export const zIdentityServiceRegisterRequest = z.object({
  email: z.email().min(1),
  password: z.string().min(8).max(2147483647),
  firstName: z.string().min(0).max(100),
  lastName: z.string().min(0).max(100),
})

export const zIdentityServiceAuthResponse = z.object({
  token: z.optional(z.string()),
  type: z.optional(z.string()),
  user: z.optional(zIdentityServiceUserResponse),
})

export const zIdentityServiceLoginRequest = z.object({
  email: z.email().min(1),
  password: z.string().min(1),
})

export const zIdentityServiceUpdateProfileRequest = z.object({
  firstName: z.optional(z.string().min(0).max(100)),
  lastName: z.optional(z.string().min(0).max(100)),
})

/**
 * Lớp bọc phản hồi phân trang
 */
export const zIdentityServicePageResponseUserResponse = z.object({
  content: z.optional(z.array(zIdentityServiceUserResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export const zIdentityServiceProblemDetail = z.object({
  type: z.optional(z.unknown()),
  title: z.optional(z.unknown()),
  status: z.optional(z.unknown()),
  detail: z.optional(z.unknown()),
  instance: z.optional(z.unknown()),
})

export const zContentServiceCreateTutorialRequest = z.object({
  title: z.string().min(0).max(255),
  content: z.string().min(1),
  tags: z.optional(z.array(z.string())),
})

export const zContentServiceTutorialResponse = z.object({
  id: z.optional(z.uuid()),
  title: z.optional(z.string()),
  content: z.optional(z.string()),
  creatorId: z.optional(z.uuid()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
  tags: z.optional(z.array(z.string())),
})

export const zContentServiceCreateSkillRequest = z.object({
  name: z.string().min(0).max(255),
  description: z.optional(z.string()),
})

export const zContentServiceSkillResponse = z.object({
  id: z.optional(z.uuid()),
  name: z.optional(z.string()),
  description: z.optional(z.string()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
})

export const zContentServiceTestCase = z.object({
  order: z.optional(z.int()),
  description: z.optional(z.string()),
  hidden: z.optional(z.boolean()),
  weight: z.optional(z.number()),
  input: z.optional(z.string()),
  output: z.optional(z.string()),
  timeout: z.optional(z.int()),
  memoryLimit: z.optional(z.int()),
})

export const zContentServiceCreateAssignmentRequest = z.object({
  title: z.string().min(0).max(255),
  description: z.string().min(1),
  difficultyLevel: z.enum(["EASY", "MEDIUM", "HARD"]),
  startDate: z.optional(z.iso.datetime()),
  dueDate: z.optional(z.iso.datetime()),
  maxScore: z.number().gte(0).lte(999.99),
  languages: z.array(z.string()).min(1).max(2147483647),
  testCases: z.array(zContentServiceTestCase).min(1).max(2147483647),
  skillIds: z.optional(z.array(z.uuid())),
  tutorialIds: z.optional(z.array(z.uuid())),
})

export const zContentServiceAssignmentResponse = z.object({
  id: z.optional(z.uuid()),
  title: z.optional(z.string()),
  description: z.optional(z.string()),
  difficultyLevel: z.optional(z.enum(["EASY", "MEDIUM", "HARD"])),
  creatorId: z.optional(z.uuid()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
  startDate: z.optional(z.iso.datetime()),
  dueDate: z.optional(z.iso.datetime()),
  maxScore: z.optional(z.number()),
  status: z.optional(z.enum(["DRAFT", "PUBLISHED", "ARCHIVED"])),
  languages: z.optional(z.array(z.string())),
  testCases: z.optional(z.array(zContentServiceTestCase)),
  skills: z.optional(z.array(zContentServiceSkillResponse)),
  tutorials: z.optional(z.array(zContentServiceTutorialResponse)),
})

export const zContentServiceUpdateTutorialRequest = z.object({
  title: z.optional(z.string().min(0).max(255)),
  content: z.optional(z.string()),
  tags: z.optional(z.array(z.string())),
})

export const zContentServiceUpdateSkillRequest = z.object({
  name: z.optional(z.string().min(0).max(255)),
  description: z.optional(z.string()),
})

export const zContentServiceUpdateAssignmentRequest = z.object({
  title: z.optional(z.string().min(0).max(255)),
  description: z.optional(z.string()),
  difficultyLevel: z.optional(z.enum(["EASY", "MEDIUM", "HARD"])),
  startDate: z.optional(z.iso.datetime()),
  dueDate: z.optional(z.iso.datetime()),
  maxScore: z.optional(z.number().gte(0).lte(999.99)),
  languages: z.optional(z.array(z.string()).min(1).max(2147483647)),
  testCases: z.optional(z.array(zContentServiceTestCase).min(1).max(2147483647)),
  skillIds: z.optional(z.array(z.uuid())),
  tutorialIds: z.optional(z.array(z.uuid())),
})

export const zContentServiceUpdateAssignmentScheduleRequest = z.object({
  startDate: z.iso.datetime(),
  dueDate: z.iso.datetime(),
})

/**
 * Lớp bọc phản hồi phân trang
 */
export const zContentServicePageResponseTutorialResponse = z.object({
  content: z.optional(z.array(zContentServiceTutorialResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

/**
 * Lớp bọc phản hồi phân trang
 */
export const zContentServicePageResponseSkillResponse = z.object({
  content: z.optional(z.array(zContentServiceSkillResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

/**
 * Lớp bọc phản hồi phân trang
 */
export const zContentServicePageResponseAssignmentResponse = z.object({
  content: z.optional(z.array(zContentServiceAssignmentResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export const zContentServiceProblemDetail = z.object({
  type: z.optional(z.unknown()),
  title: z.optional(z.unknown()),
  status: z.optional(z.unknown()),
  detail: z.optional(z.unknown()),
  instance: z.optional(z.unknown()),
})

/**
 * Yêu cầu tạo bài nộp
 */
export const zSubmissionServiceCreateSubmissionRequest = z.object({
  assignmentId: z.uuid(),
  code: z.string().min(1),
  language: z.string().min(1),
})

export const zSubmissionServiceTestCaseResultResponse = z.object({
  order: z.optional(z.int()),
  description: z.optional(z.string()),
  hidden: z.optional(z.boolean()),
  weight: z.optional(z.number()),
  input: z.optional(z.string()),
  output: z.optional(z.string()),
  timeout: z.optional(z.int()),
  memoryLimit: z.optional(z.int()),
  passed: z.optional(z.boolean()),
  actualOutput: z.optional(z.string()),
  errorMessage: z.optional(z.string()),
  executionTime: z.optional(z.number()),
  memoryUsed: z.optional(z.number()),
})

export const zSubmissionServiceSubmissionResponse = z.object({
  id: z.optional(z.uuid()),
  assignmentId: z.optional(z.uuid()),
  studentId: z.optional(z.uuid()),
  submittedAt: z.optional(z.iso.datetime()),
  status: z.optional(z.enum(["PENDING", "EVALUATED", "FAILED"])),
  code: z.optional(z.string()),
  language: z.optional(z.string()),
  result: z.optional(z.enum(["PASSED", "FAILED", "PARTIAL"])),
  score: z.optional(z.number()),
  testCaseResults: z.optional(z.array(zSubmissionServiceTestCaseResultResponse)),
  evaluatedAt: z.optional(z.iso.datetime()),
  feedback: z.optional(z.string()),
})

export const zSubmissionServiceSubmissionFeedbackRequest = z.object({
  feedback: z.string().min(1),
})

/**
 * Lớp bọc phản hồi phân trang
 */
export const zSubmissionServicePageResponseSubmissionResponse = z.object({
  content: z.optional(z.array(zSubmissionServiceSubmissionResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export const zSubmissionServiceProblemDetail = z.object({
  type: z.optional(z.unknown()),
  title: z.optional(z.unknown()),
  status: z.optional(z.unknown()),
  detail: z.optional(z.unknown()),
  instance: z.optional(z.unknown()),
})

/**
 * Thông tin runtime của ngôn ngữ lập trình được hỗ trợ
 */
export const zEvaluationServiceRuntimeResponse = z.object({
  language: z.optional(z.string()),
  version: z.optional(z.string()),
  aliases: z.optional(z.array(z.string())),
  runtime: z.optional(z.string()),
})

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export const zEvaluationServiceProblemDetail = z.object({
  type: z.optional(z.unknown()),
  title: z.optional(z.unknown()),
  status: z.optional(z.unknown()),
  detail: z.optional(z.unknown()),
  instance: z.optional(z.unknown()),
})

export const zSupportServiceCreateSupportSessionRequest = z.object({
  initialMessage: z.string().min(1),
})

export const zSupportServiceSupportMessageResponse = z.object({
  id: z.optional(z.uuid()),
  sessionId: z.optional(z.uuid()),
  senderId: z.optional(z.uuid()),
  content: z.optional(z.string()),
  isInstructor: z.optional(z.boolean()),
  isRead: z.optional(z.boolean()),
  createdAt: z.optional(z.iso.datetime()),
})

export const zSupportServiceSupportSessionResponse = z.object({
  id: z.optional(z.uuid()),
  studentId: z.optional(z.uuid()),
  instructorId: z.optional(z.uuid()),
  isClosed: z.optional(z.boolean()),
  createdAt: z.optional(z.iso.datetime()),
  closedAt: z.optional(z.iso.datetime()),
  messages: z.optional(z.array(zSupportServiceSupportMessageResponse)),
})

export const zSupportServiceSendMessageRequest = z.object({
  content: z.string().min(1),
})

/**
 * Lớp bọc phản hồi phân trang
 */
export const zSupportServicePageResponseSupportSessionResponse = z.object({
  content: z.optional(z.array(zSupportServiceSupportSessionResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export const zSupportServiceProblemDetail = z.object({
  type: z.optional(z.unknown()),
  title: z.optional(z.unknown()),
  status: z.optional(z.unknown()),
  detail: z.optional(z.unknown()),
  instance: z.optional(z.unknown()),
})

export const zNotificationServiceRegisterDeviceRequest = z.object({
  token: z.string().min(1),
  deviceType: z.string().min(1),
  userAgent: z.optional(z.string()),
})

export const zNotificationServiceDeviceTokenResponse = z.object({
  id: z.optional(z.uuid()),
  token: z.optional(z.string()),
  deviceType: z.optional(z.string()),
  userAgent: z.optional(z.string()),
  isActive: z.optional(z.boolean()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
})

export const zNotificationServiceNotificationPreferencesRequest = z.object({
  emailEnabled: z.optional(z.boolean()),
  pushEnabled: z.optional(z.boolean()),
  emailAssignmentPublished: z.optional(z.boolean()),
  emailSubmissionEvaluated: z.optional(z.boolean()),
  pushAssignmentPublished: z.optional(z.boolean()),
  pushSubmissionEvaluated: z.optional(z.boolean()),
})

export const zNotificationServiceNotificationPreferencesResponse = z.object({
  id: z.optional(z.uuid()),
  userId: z.optional(z.uuid()),
  emailEnabled: z.optional(z.boolean()),
  pushEnabled: z.optional(z.boolean()),
  emailAssignmentPublished: z.optional(z.boolean()),
  emailSubmissionEvaluated: z.optional(z.boolean()),
  pushAssignmentPublished: z.optional(z.boolean()),
  pushSubmissionEvaluated: z.optional(z.boolean()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
})

/**
 * Chi tiết lỗi theo chuẩn RFC 9457
 */
export const zNotificationServiceProblemDetail = z.object({
  type: z.optional(z.unknown()),
  title: z.optional(z.unknown()),
  status: z.optional(z.unknown()),
  detail: z.optional(z.unknown()),
  instance: z.optional(z.unknown()),
})

export const zIdentityServiceGetAllUsersData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zIdentityServiceGetAllUsersResponse = zIdentityServicePageResponseUserResponse

export const zIdentityServiceCreateUserData = z.object({
  body: zIdentityServiceCreateUserRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Created
 */
export const zIdentityServiceCreateUserResponse = zIdentityServiceUserResponse

export const zIdentityServiceDeactivateUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zIdentityServiceDeactivateUserResponse = z.void()

export const zIdentityServiceActivateUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zIdentityServiceActivateUserResponse = z.void()

export const zIdentityServiceChangePasswordData = z.object({
  body: zIdentityServiceChangePasswordRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zIdentityServiceChangePasswordResponse = z.void()

export const zIdentityServiceVerifyEmailData = z.object({
  body: zIdentityServiceTokenRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zIdentityServiceVerifyEmailResponse = z.void()

export const zIdentityServiceResetPasswordData = z.object({
  body: zIdentityServiceResetPasswordRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zIdentityServiceResetPasswordResponse = z.void()

export const zIdentityServiceResendVerificationEmailData = z.object({
  body: zIdentityServiceEmailRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zIdentityServiceResendVerificationEmailResponse = z.void()

export const zIdentityServiceRegisterData = z.object({
  body: zIdentityServiceRegisterRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Created
 */
export const zIdentityServiceRegisterResponse = zIdentityServiceAuthResponse

export const zIdentityServiceLoginData = z.object({
  body: zIdentityServiceLoginRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceLoginResponse = zIdentityServiceAuthResponse

export const zIdentityServiceRequestPasswordResetData = z.object({
  body: zIdentityServiceEmailRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zIdentityServiceRequestPasswordResetResponse = z.void()

export const zIdentityServiceGetCurrentUserData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceGetCurrentUserResponse = zIdentityServiceUserResponse

export const zIdentityServiceUpdateCurrentUserProfileData = z.object({
  body: zIdentityServiceUpdateProfileRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceUpdateCurrentUserProfileResponse = zIdentityServiceUserResponse

export const zIdentityServiceDeleteUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zIdentityServiceDeleteUserResponse = z.void()

export const zIdentityServiceGetUserByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceGetUserByIdResponse = zIdentityServiceUserResponse

export const zIdentityServiceGetUsersByRoleData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    role: z.enum(["STUDENT", "INSTRUCTOR", "CONTENT_PROVIDER", "ADMIN"]),
  }),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zIdentityServiceGetUsersByRoleResponse = zIdentityServicePageResponseUserResponse

export const zContentServiceGetAllTutorialsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zContentServiceGetAllTutorialsResponse = zContentServicePageResponseTutorialResponse

export const zContentServiceCreateTutorialData = z.object({
  body: zContentServiceCreateTutorialRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Created
 */
export const zContentServiceCreateTutorialResponse = zContentServiceTutorialResponse

export const zContentServiceGetAllSkillsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zContentServiceGetAllSkillsResponse = zContentServicePageResponseSkillResponse

export const zContentServiceCreateSkillData = z.object({
  body: zContentServiceCreateSkillRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Created
 */
export const zContentServiceCreateSkillResponse = zContentServiceSkillResponse

export const zContentServiceGetAllAssignmentsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zContentServiceGetAllAssignmentsResponse = zContentServicePageResponseAssignmentResponse

export const zContentServiceCreateAssignmentData = z.object({
  body: zContentServiceCreateAssignmentRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Created
 */
export const zContentServiceCreateAssignmentResponse = zContentServiceAssignmentResponse

export const zContentServicePublishAssignmentData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServicePublishAssignmentResponse = zContentServiceAssignmentResponse

export const zContentServiceArchiveAssignmentData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceArchiveAssignmentResponse = zContentServiceAssignmentResponse

export const zContentServiceDeleteTutorialData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zContentServiceDeleteTutorialResponse = z.void()

export const zContentServiceGetTutorialByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceGetTutorialByIdResponse = zContentServiceTutorialResponse

export const zContentServiceUpdateTutorialData = z.object({
  body: zContentServiceUpdateTutorialRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceUpdateTutorialResponse = zContentServiceTutorialResponse

export const zContentServiceDeleteSkillData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zContentServiceDeleteSkillResponse = z.void()

export const zContentServiceGetSkillByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceGetSkillByIdResponse = zContentServiceSkillResponse

export const zContentServiceUpdateSkillData = z.object({
  body: zContentServiceUpdateSkillRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceUpdateSkillResponse = zContentServiceSkillResponse

export const zContentServiceDeleteAssignmentData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zContentServiceDeleteAssignmentResponse = z.void()

export const zContentServiceGetAssignmentByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceGetAssignmentByIdResponse = zContentServiceAssignmentResponse

export const zContentServiceUpdateAssignmentData = z.object({
  body: zContentServiceUpdateAssignmentRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceUpdateAssignmentResponse = zContentServiceAssignmentResponse

export const zContentServiceUpdateAssignmentScheduleData = z.object({
  body: zContentServiceUpdateAssignmentScheduleRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceUpdateAssignmentScheduleResponse = zContentServiceAssignmentResponse

export const zSubmissionServiceGetAllSubmissionsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      assignmentId: z.optional(z.uuid()),
      studentId: z.optional(z.uuid()),
      status: z.optional(z.enum(["PENDING", "EVALUATED", "FAILED"])),
      page: z.optional(z.string()),
      size: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zSubmissionServiceGetAllSubmissionsResponse = zSubmissionServicePageResponseSubmissionResponse

export const zSubmissionServiceCreateSubmissionData = z.object({
  body: zSubmissionServiceCreateSubmissionRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Created
 */
export const zSubmissionServiceCreateSubmissionResponse = zSubmissionServiceSubmissionResponse

export const zSubmissionServiceProvideFeedbackData = z.object({
  body: zSubmissionServiceSubmissionFeedbackRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zSubmissionServiceProvideFeedbackResponse = zSubmissionServiceSubmissionResponse

export const zSubmissionServiceGetSubmissionByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zSubmissionServiceGetSubmissionByIdResponse = zSubmissionServiceSubmissionResponse

export const zEvaluationServiceGetSupportedRuntimesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zEvaluationServiceGetSupportedRuntimesResponse = z.array(zEvaluationServiceRuntimeResponse)

export const zSupportServiceListSessionsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
      userId: z.optional(z.uuid()),
      email: z.optional(z.string()),
      firstName: z.optional(z.string()),
      lastName: z.optional(z.string()),
      role: z.optional(z.string()),
      isActive: z.optional(z.boolean()),
    }),
  ),
})

/**
 * OK
 */
export const zSupportServiceListSessionsResponse = zSupportServicePageResponseSupportSessionResponse

export const zSupportServiceCreateSessionData = z.object({
  body: zSupportServiceCreateSupportSessionRequest,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      userId: z.optional(z.uuid()),
      email: z.optional(z.string()),
      firstName: z.optional(z.string()),
      lastName: z.optional(z.string()),
      role: z.optional(z.string()),
      isActive: z.optional(z.boolean()),
    }),
  ),
})

/**
 * Created
 */
export const zSupportServiceCreateSessionResponse = zSupportServiceSupportSessionResponse

export const zSupportServiceSendMessageData = z.object({
  body: zSupportServiceSendMessageRequest,
  path: z.object({
    sessionId: z.uuid(),
  }),
  query: z.optional(
    z.object({
      userId: z.optional(z.uuid()),
      email: z.optional(z.string()),
      firstName: z.optional(z.string()),
      lastName: z.optional(z.string()),
      role: z.optional(z.string()),
      isActive: z.optional(z.boolean()),
    }),
  ),
})

/**
 * Created
 */
export const zSupportServiceSendMessageResponse = zSupportServiceSupportSessionResponse

export const zSupportServiceCloseSessionData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    sessionId: z.uuid(),
  }),
  query: z.optional(
    z.object({
      userId: z.optional(z.uuid()),
      email: z.optional(z.string()),
      firstName: z.optional(z.string()),
      lastName: z.optional(z.string()),
      role: z.optional(z.string()),
      isActive: z.optional(z.boolean()),
    }),
  ),
})

/**
 * OK
 */
export const zSupportServiceCloseSessionResponse = zSupportServiceSupportSessionResponse

export const zSupportServiceGetSessionByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    sessionId: z.uuid(),
  }),
  query: z.optional(
    z.object({
      userId: z.optional(z.uuid()),
      email: z.optional(z.string()),
      firstName: z.optional(z.string()),
      lastName: z.optional(z.string()),
      role: z.optional(z.string()),
      isActive: z.optional(z.boolean()),
    }),
  ),
})

/**
 * OK
 */
export const zSupportServiceGetSessionByIdResponse = zSupportServiceSupportSessionResponse

export const zNotificationServiceRegisterDeviceData = z.object({
  body: zNotificationServiceRegisterDeviceRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Created
 */
export const zNotificationServiceRegisterDeviceResponse = zNotificationServiceDeviceTokenResponse

export const zNotificationServiceGetPreferencesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zNotificationServiceGetPreferencesResponse = zNotificationServiceNotificationPreferencesResponse

export const zNotificationServiceUpdatePreferencesData = z.object({
  body: zNotificationServiceNotificationPreferencesRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zNotificationServiceUpdatePreferencesResponse = zNotificationServiceNotificationPreferencesResponse

export const zNotificationServiceGetUserDevicesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zNotificationServiceGetUserDevicesResponse = z.array(zNotificationServiceDeviceTokenResponse)

export const zNotificationServiceRemoveDeviceData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    token: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * No Content
 */
export const zNotificationServiceRemoveDeviceResponse = z.void()
