// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod"

export const zIdentityServiceUpdateProfileRequest = z.object({
  firstName: z.optional(z.string().min(0).max(100)),
  lastName: z.optional(z.string().min(0).max(100)),
})

export const zIdentityServiceUserResponse = z.object({
  id: z.optional(z.uuid()),
  email: z.optional(z.string()),
  firstName: z.optional(z.string()),
  lastName: z.optional(z.string()),
  role: z.optional(z.enum(["STUDENT", "INSTRUCTOR", "CONTENT_PROVIDER", "ADMIN"])),
  isActive: z.optional(z.boolean()),
  isEmailVerified: z.optional(z.boolean()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
})

export const zIdentityServiceCreateUserRequest = z.object({
  email: z.email().min(1),
  password: z.string().min(8).max(2147483647),
  firstName: z.string().min(0).max(100),
  lastName: z.string().min(0).max(100),
  role: z.optional(z.enum(["STUDENT", "INSTRUCTOR", "CONTENT_PROVIDER", "ADMIN"])),
  isActive: z.optional(z.boolean()),
  isEmailVerified: z.optional(z.boolean()),
})

export const zIdentityServiceChangePasswordRequest = z.object({
  currentPassword: z.string().min(1),
  newPassword: z.string().min(8).max(2147483647),
})

export const zIdentityServiceTokenRequest = z.object({
  token: z.string().min(1),
})

export const zIdentityServiceResetPasswordRequest = z.object({
  token: z.string().min(1),
  newPassword: z.string().min(8).max(2147483647),
})

export const zIdentityServiceEmailRequest = z.object({
  email: z.email().min(1),
})

export const zIdentityServiceRegisterRequest = z.object({
  email: z.email().min(1),
  password: z.string().min(8).max(2147483647),
  firstName: z.string().min(0).max(100),
  lastName: z.string().min(0).max(100),
})

export const zIdentityServiceAuthResponse = z.object({
  token: z.optional(z.string()),
  type: z.optional(z.string()),
  user: z.optional(zIdentityServiceUserResponse),
})

export const zIdentityServiceLoginRequest = z.object({
  email: z.email().min(1),
  password: z.string().min(1),
})

/**
 * Paginated response wrapper
 */
export const zIdentityServicePageResponseUserResponse = z.object({
  content: z.optional(z.array(zIdentityServiceUserResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

export const zContentServiceCreateTutorialRequest = z.object({
  title: z.string().min(0).max(255),
  content: z.string().min(1),
  tags: z.optional(z.array(z.string())),
})

export const zContentServiceTutorialResponse = z.object({
  id: z.optional(z.uuid()),
  title: z.optional(z.string()),
  content: z.optional(z.string()),
  creatorId: z.optional(z.uuid()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
  tags: z.optional(z.array(z.string())),
})

export const zContentServiceCreateSkillRequest = z.object({
  name: z.string().min(0).max(255),
  description: z.optional(z.string()),
})

export const zContentServiceSkillResponse = z.object({
  id: z.optional(z.uuid()),
  name: z.optional(z.string()),
  description: z.optional(z.string()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
})

export const zContentServiceTestCase = z.object({
  order: z.optional(z.int()),
  description: z.optional(z.string()),
  hidden: z.optional(z.boolean()),
  weight: z.optional(z.number()),
  input: z.optional(z.string()),
  output: z.optional(z.string()),
  timeout: z.optional(z.int()),
  memoryLimit: z.optional(z.int()),
})

export const zContentServiceCreateAssignmentRequest = z.object({
  title: z.string().min(0).max(255),
  description: z.string().min(1),
  difficultyLevel: z.enum(["EASY", "MEDIUM", "HARD"]),
  startDate: z.optional(z.iso.datetime()),
  dueDate: z.optional(z.iso.datetime()),
  maxScore: z.number().gte(0).lte(999.99),
  languages: z.array(z.string()).min(1).max(2147483647),
  testCases: z.array(zContentServiceTestCase).min(1).max(2147483647),
  skillIds: z.optional(z.array(z.uuid())),
  tutorialIds: z.optional(z.array(z.uuid())),
})

export const zContentServiceAssignmentResponse = z.object({
  id: z.optional(z.uuid()),
  title: z.optional(z.string()),
  description: z.optional(z.string()),
  difficultyLevel: z.optional(z.enum(["EASY", "MEDIUM", "HARD"])),
  creatorId: z.optional(z.uuid()),
  createdAt: z.optional(z.iso.datetime()),
  updatedAt: z.optional(z.iso.datetime()),
  startDate: z.optional(z.iso.datetime()),
  dueDate: z.optional(z.iso.datetime()),
  maxScore: z.optional(z.number()),
  status: z.optional(z.enum(["DRAFT", "PUBLISHED", "ARCHIVED"])),
  languages: z.optional(z.array(z.string())),
  testCases: z.optional(z.array(zContentServiceTestCase)),
  skills: z.optional(z.array(zContentServiceSkillResponse)),
  tutorials: z.optional(z.array(zContentServiceTutorialResponse)),
})

export const zContentServiceUpdateTutorialRequest = z.object({
  title: z.optional(z.string().min(0).max(255)),
  content: z.optional(z.string()),
  tags: z.optional(z.array(z.string())),
})

export const zContentServiceUpdateSkillRequest = z.object({
  name: z.optional(z.string().min(0).max(255)),
  description: z.optional(z.string()),
})

export const zContentServiceUpdateAssignmentRequest = z.object({
  title: z.optional(z.string().min(0).max(255)),
  description: z.optional(z.string()),
  difficultyLevel: z.optional(z.enum(["EASY", "MEDIUM", "HARD"])),
  startDate: z.optional(z.iso.datetime()),
  dueDate: z.optional(z.iso.datetime()),
  maxScore: z.optional(z.number().gte(0).lte(999.99)),
  languages: z.optional(z.array(z.string()).min(1).max(2147483647)),
  testCases: z.optional(z.array(zContentServiceTestCase).min(1).max(2147483647)),
  skillIds: z.optional(z.array(z.uuid())),
  tutorialIds: z.optional(z.array(z.uuid())),
})

export const zContentServiceUpdateAssignmentScheduleRequest = z.object({
  startDate: z.iso.datetime(),
  dueDate: z.iso.datetime(),
})

/**
 * Paginated response wrapper
 */
export const zContentServicePageResponseTutorialResponse = z.object({
  content: z.optional(z.array(zContentServiceTutorialResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

/**
 * Paginated response wrapper
 */
export const zContentServicePageResponseSkillResponse = z.object({
  content: z.optional(z.array(zContentServiceSkillResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

/**
 * Paginated response wrapper
 */
export const zContentServicePageResponseAssignmentResponse = z.object({
  content: z.optional(z.array(zContentServiceAssignmentResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

export const zSubmissionServiceCreateSubmissionRequest = z.object({
  assignmentId: z.uuid(),
  code: z.string().min(1),
  language: z.string().min(1),
})

export const zSubmissionServiceTestCaseResultResponse = z.object({
  order: z.optional(z.int()),
  description: z.optional(z.string()),
  hidden: z.optional(z.boolean()),
  weight: z.optional(z.number()),
  input: z.optional(z.string()),
  output: z.optional(z.string()),
  timeout: z.optional(z.int()),
  memoryLimit: z.optional(z.int()),
  passed: z.optional(z.boolean()),
  actualOutput: z.optional(z.string()),
  errorMessage: z.optional(z.string()),
  executionTime: z.optional(z.number()),
  memoryUsed: z.optional(z.number()),
})

export const zSubmissionServiceSubmissionResponse = z.object({
  id: z.optional(z.uuid()),
  assignmentId: z.optional(z.uuid()),
  studentId: z.optional(z.uuid()),
  submittedAt: z.optional(z.iso.datetime()),
  status: z.optional(z.enum(["PENDING", "EVALUATED", "FAILED"])),
  code: z.optional(z.string()),
  language: z.optional(z.string()),
  result: z.optional(z.enum(["PASSED", "FAILED", "PARTIAL"])),
  score: z.optional(z.number()),
  testCaseResults: z.optional(z.array(zSubmissionServiceTestCaseResultResponse)),
  evaluatedAt: z.optional(z.iso.datetime()),
  feedback: z.optional(z.string()),
})

export const zSubmissionServiceSubmissionFeedbackRequest = z.object({
  feedback: z.string().min(1),
})

/**
 * Paginated response wrapper
 */
export const zSubmissionServicePageResponseSubmissionResponse = z.object({
  content: z.optional(z.array(zSubmissionServiceSubmissionResponse)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

/**
 * Supported programming language runtime information
 */
export const zEvaluationServiceRuntimeResponse = z.object({
  language: z.optional(z.string()),
  version: z.optional(z.string()),
  aliases: z.optional(z.array(z.string())),
  runtime: z.optional(z.string()),
})

export const zSupportServiceCreateSupportSessionRequest = z.object({
  initialMessage: z.string().min(1),
})

export const zSupportServiceSupportMessageDto = z.object({
  id: z.optional(z.uuid()),
  senderId: z.optional(z.uuid()),
  content: z.optional(z.string()),
  isInstructor: z.optional(z.boolean()),
  isRead: z.optional(z.boolean()),
  createdAt: z.optional(z.iso.datetime()),
})

export const zSupportServiceSupportSessionDto = z.object({
  id: z.optional(z.uuid()),
  studentId: z.optional(z.uuid()),
  instructorId: z.optional(z.uuid()),
  isClosed: z.optional(z.boolean()),
  createdAt: z.optional(z.iso.datetime()),
  closedAt: z.optional(z.iso.datetime()),
  messages: z.optional(z.array(zSupportServiceSupportMessageDto)),
})

/**
 * Paginated response wrapper
 */
export const zSupportServicePageResponseSupportSessionDto = z.object({
  content: z.optional(z.array(zSupportServiceSupportSessionDto)),
  pageNumber: z.optional(z.int()),
  pageSize: z.optional(z.int()),
  totalElements: z.optional(z.coerce.bigint()),
  totalPages: z.optional(z.int()),
  first: z.optional(z.boolean()),
  last: z.optional(z.boolean()),
  hasNext: z.optional(z.boolean()),
  hasPrevious: z.optional(z.boolean()),
})

export const zIdentityServiceDeactivateUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceDeactivateUserResponse = z.record(z.string(), z.string())

export const zIdentityServiceActivateUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceActivateUserResponse = z.record(z.string(), z.string())

export const zIdentityServiceGetCurrentUserData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceGetCurrentUserResponse = zIdentityServiceUserResponse

export const zIdentityServiceUpdateCurrentUserProfileData = z.object({
  body: zIdentityServiceUpdateProfileRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceUpdateCurrentUserProfileResponse = zIdentityServiceUserResponse

export const zIdentityServiceGetAllUsersData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
      sort: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zIdentityServiceGetAllUsersResponse = zIdentityServicePageResponseUserResponse

export const zIdentityServiceCreateUserData = z.object({
  body: zIdentityServiceCreateUserRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceCreateUserResponse = zIdentityServiceUserResponse

export const zIdentityServiceChangePasswordData = z.object({
  body: zIdentityServiceChangePasswordRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceChangePasswordResponse = z.record(z.string(), z.string())

export const zIdentityServiceVerifyEmailData = z.object({
  body: zIdentityServiceTokenRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceVerifyEmailResponse = z.record(z.string(), z.string())

export const zIdentityServiceResetPasswordData = z.object({
  body: zIdentityServiceResetPasswordRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceResetPasswordResponse = z.record(z.string(), z.string())

export const zIdentityServiceResendVerificationEmailData = z.object({
  body: zIdentityServiceEmailRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceResendVerificationEmailResponse = z.record(z.string(), z.string())

export const zIdentityServiceRegisterData = z.object({
  body: zIdentityServiceRegisterRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceRegisterResponse = zIdentityServiceAuthResponse

export const zIdentityServiceLoginData = z.object({
  body: zIdentityServiceLoginRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceLoginResponse = zIdentityServiceAuthResponse

export const zIdentityServiceRequestPasswordResetData = z.object({
  body: zIdentityServiceEmailRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceRequestPasswordResetResponse = z.record(z.string(), z.string())

export const zIdentityServiceDeleteUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceDeleteUserResponse = z.record(z.string(), z.string())

export const zIdentityServiceGetUserByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zIdentityServiceGetUserByIdResponse = zIdentityServiceUserResponse

export const zIdentityServiceGetUsersByRoleData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    role: z.enum(["STUDENT", "INSTRUCTOR", "CONTENT_PROVIDER", "ADMIN"]),
  }),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
      sort: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zIdentityServiceGetUsersByRoleResponse = zIdentityServicePageResponseUserResponse

export const zContentServiceGetAllTutorialsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
      sort: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zContentServiceGetAllTutorialsResponse = zContentServicePageResponseTutorialResponse

export const zContentServiceCreateTutorialData = z.object({
  body: zContentServiceCreateTutorialRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceCreateTutorialResponse = zContentServiceTutorialResponse

export const zContentServiceGetAllSkillsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
      sort: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zContentServiceGetAllSkillsResponse = zContentServicePageResponseSkillResponse

export const zContentServiceCreateSkillData = z.object({
  body: zContentServiceCreateSkillRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceCreateSkillResponse = zContentServiceSkillResponse

export const zContentServiceGetAllAssignmentsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
      sort: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zContentServiceGetAllAssignmentsResponse = zContentServicePageResponseAssignmentResponse

export const zContentServiceCreateAssignmentData = z.object({
  body: zContentServiceCreateAssignmentRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceCreateAssignmentResponse = zContentServiceAssignmentResponse

export const zContentServicePublishAssignmentData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServicePublishAssignmentResponse = zContentServiceAssignmentResponse

export const zContentServiceArchiveAssignmentData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceArchiveAssignmentResponse = zContentServiceAssignmentResponse

export const zContentServiceDeleteTutorialData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceDeleteTutorialResponse = z.record(z.string(), z.string())

export const zContentServiceGetTutorialByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceGetTutorialByIdResponse = zContentServiceTutorialResponse

export const zContentServiceUpdateTutorialData = z.object({
  body: zContentServiceUpdateTutorialRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceUpdateTutorialResponse = zContentServiceTutorialResponse

export const zContentServiceDeleteSkillData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceDeleteSkillResponse = z.record(z.string(), z.string())

export const zContentServiceGetSkillByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceGetSkillByIdResponse = zContentServiceSkillResponse

export const zContentServiceUpdateSkillData = z.object({
  body: zContentServiceUpdateSkillRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceUpdateSkillResponse = zContentServiceSkillResponse

export const zContentServiceDeleteAssignmentData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceDeleteAssignmentResponse = z.record(z.string(), z.string())

export const zContentServiceGetAssignmentByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceGetAssignmentByIdResponse = zContentServiceAssignmentResponse

export const zContentServiceUpdateAssignmentData = z.object({
  body: zContentServiceUpdateAssignmentRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceUpdateAssignmentResponse = zContentServiceAssignmentResponse

export const zContentServiceUpdateAssignmentScheduleData = z.object({
  body: zContentServiceUpdateAssignmentScheduleRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zContentServiceUpdateAssignmentScheduleResponse = zContentServiceAssignmentResponse

export const zSubmissionServiceGetAllSubmissionsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      assignmentId: z.optional(z.uuid()),
      studentId: z.optional(z.uuid()),
      status: z.optional(z.enum(["PENDING", "EVALUATED", "FAILED"])),
      page: z.optional(z.string()),
      size: z.optional(z.string()),
      sort: z.optional(z.string()),
    }),
  ),
})

/**
 * OK
 */
export const zSubmissionServiceGetAllSubmissionsResponse = zSubmissionServicePageResponseSubmissionResponse

export const zSubmissionServiceCreateSubmissionData = z.object({
  body: zSubmissionServiceCreateSubmissionRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zSubmissionServiceCreateSubmissionResponse = zSubmissionServiceSubmissionResponse

export const zSubmissionServiceProvideFeedbackData = z.object({
  body: zSubmissionServiceSubmissionFeedbackRequest,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zSubmissionServiceProvideFeedbackResponse = zSubmissionServiceSubmissionResponse

export const zSubmissionServiceGetSubmissionByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * OK
 */
export const zSubmissionServiceGetSubmissionByIdResponse = zSubmissionServiceSubmissionResponse

export const zEvaluationServiceGetSupportedRuntimesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successfully retrieved runtimes
 */
export const zEvaluationServiceGetSupportedRuntimesResponse = z.array(zEvaluationServiceRuntimeResponse)

export const zSupportServiceListSessionsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.string()),
      size: z.optional(z.string()),
      sort: z.optional(z.string()),
      userId: z.optional(z.uuid()),
      email: z.optional(z.string()),
      firstName: z.optional(z.string()),
      lastName: z.optional(z.string()),
      role: z.optional(z.string()),
      isActive: z.optional(z.boolean()),
    }),
  ),
})

/**
 * Successfully retrieved sessions
 */
export const zSupportServiceListSessionsResponse = zSupportServicePageResponseSupportSessionDto

export const zSupportServiceCreateSessionData = z.object({
  body: zSupportServiceCreateSupportSessionRequest,
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      userId: z.optional(z.uuid()),
      email: z.optional(z.string()),
      firstName: z.optional(z.string()),
      lastName: z.optional(z.string()),
      role: z.optional(z.string()),
      isActive: z.optional(z.boolean()),
    }),
  ),
})

/**
 * Session created successfully
 */
export const zSupportServiceCreateSessionResponse = zSupportServiceSupportSessionDto

export const zSupportServiceCloseSessionData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(
    z.object({
      userId: z.optional(z.uuid()),
      email: z.optional(z.string()),
      firstName: z.optional(z.string()),
      lastName: z.optional(z.string()),
      role: z.optional(z.string()),
      isActive: z.optional(z.boolean()),
    }),
  ),
})

/**
 * Session closed successfully
 */
export const zSupportServiceCloseSessionResponse = zSupportServiceSupportSessionDto

export const zSupportServiceGetSessionByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(
    z.object({
      userId: z.optional(z.uuid()),
      email: z.optional(z.string()),
      firstName: z.optional(z.string()),
      lastName: z.optional(z.string()),
      role: z.optional(z.string()),
      isActive: z.optional(z.boolean()),
    }),
  ),
})

/**
 * Successfully retrieved session
 */
export const zSupportServiceGetSessionByIdResponse = zSupportServiceSupportSessionDto
