/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as VerifyEmailRouteImport } from "./routes/verify-email"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password"
import { Route as DevRouteImport } from "./routes/dev"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthenticatedProviderRouteImport } from "./routes/_authenticated/provider"
import { Route as AuthenticatedStudentIndexRouteImport } from "./routes/_authenticated/student/index"
import { Route as AuthenticatedProviderIndexRouteImport } from "./routes/_authenticated/provider/index"
import { Route as AuthenticatedInstructorIndexRouteImport } from "./routes/_authenticated/instructor/index"
import { Route as AuthenticatedStudentSupportRouteImport } from "./routes/_authenticated/student/support"
import { Route as AuthenticatedStudentSubmissionsRouteImport } from "./routes/_authenticated/student/submissions"
import { Route as AuthenticatedStudentSettingsRouteImport } from "./routes/_authenticated/student/settings"
import { Route as AuthenticatedStudentResourcesRouteImport } from "./routes/_authenticated/student/resources"
import { Route as AuthenticatedStudentProfileRouteImport } from "./routes/_authenticated/student/profile"
import { Route as AuthenticatedStudentPerformanceRouteImport } from "./routes/_authenticated/student/performance"
import { Route as AuthenticatedStudentDashboardRouteImport } from "./routes/_authenticated/student/dashboard"
import { Route as AuthenticatedStudentAssignmentsRouteImport } from "./routes/_authenticated/student/assignments"
import { Route as AuthenticatedProviderSettingsRouteImport } from "./routes/_authenticated/provider/settings"
import { Route as AuthenticatedProviderProfileRouteImport } from "./routes/_authenticated/provider/profile"
import { Route as AuthenticatedProviderDashboardRouteImport } from "./routes/_authenticated/provider/dashboard"
import { Route as AuthenticatedProviderAssignmentsRouteImport } from "./routes/_authenticated/provider/assignments"
import { Route as AuthenticatedProviderAnalyticsRouteImport } from "./routes/_authenticated/provider/analytics"
import { Route as AuthenticatedInstructorSupportRouteImport } from "./routes/_authenticated/instructor/support"
import { Route as AuthenticatedInstructorSubmissionsRouteImport } from "./routes/_authenticated/instructor/submissions"
import { Route as AuthenticatedInstructorSettingsRouteImport } from "./routes/_authenticated/instructor/settings"
import { Route as AuthenticatedInstructorScheduleRouteImport } from "./routes/_authenticated/instructor/schedule"
import { Route as AuthenticatedInstructorProfileRouteImport } from "./routes/_authenticated/instructor/profile"
import { Route as AuthenticatedInstructorFeedbackRouteImport } from "./routes/_authenticated/instructor/feedback"
import { Route as AuthenticatedInstructorDashboardRouteImport } from "./routes/_authenticated/instructor/dashboard"
import { Route as AuthenticatedInstructorAssignmentsRouteImport } from "./routes/_authenticated/instructor/assignments"
import { Route as AuthenticatedStudentSubmissionsIndexRouteImport } from "./routes/_authenticated/student/submissions/index"
import { Route as AuthenticatedStudentResourcesIndexRouteImport } from "./routes/_authenticated/student/resources/index"
import { Route as AuthenticatedStudentAssignmentsIndexRouteImport } from "./routes/_authenticated/student/assignments/index"
import { Route as AuthenticatedProviderTutorialsIndexRouteImport } from "./routes/_authenticated/provider/tutorials/index"
import { Route as AuthenticatedProviderSkillsIndexRouteImport } from "./routes/_authenticated/provider/skills/index"
import { Route as AuthenticatedProviderAssignmentsIndexRouteImport } from "./routes/_authenticated/provider/assignments/index"
import { Route as AuthenticatedStudentSubmissionsIdRouteImport } from "./routes/_authenticated/student/submissions/$id"
import { Route as AuthenticatedStudentSubmissionIdRouteImport } from "./routes/_authenticated/student/submission/$id"
import { Route as AuthenticatedStudentResourcesSkillsRouteImport } from "./routes/_authenticated/student/resources/skills"
import { Route as AuthenticatedStudentAssignmentsIdRouteImport } from "./routes/_authenticated/student/assignments/$id"
import { Route as AuthenticatedProviderTutorialsCreateRouteImport } from "./routes/_authenticated/provider/tutorials/create"
import { Route as AuthenticatedProviderTutorialsIdRouteImport } from "./routes/_authenticated/provider/tutorials/$id"
import { Route as AuthenticatedProviderSkillsCreateRouteImport } from "./routes/_authenticated/provider/skills/create"
import { Route as AuthenticatedProviderSkillsIdRouteImport } from "./routes/_authenticated/provider/skills/$id"
import { Route as AuthenticatedProviderAssignmentsCreateRouteImport } from "./routes/_authenticated/provider/assignments/create"
import { Route as AuthenticatedProviderAssignmentsIdRouteImport } from "./routes/_authenticated/provider/assignments/$id"
import { Route as AuthenticatedInstructorSubmissionsIdRouteImport } from "./routes/_authenticated/instructor/submissions/$id"
import { Route as AuthenticatedInstructorAssignmentsIdRouteImport } from "./routes/_authenticated/instructor/assignments/$id"
import { Route as AuthenticatedStudentResourcesSkillsIndexRouteImport } from "./routes/_authenticated/student/resources/skills/index"
import { Route as AuthenticatedStudentResourcesTutorialsIdRouteImport } from "./routes/_authenticated/student/resources/tutorials/$id"
import { Route as AuthenticatedStudentResourcesSkillsIdRouteImport } from "./routes/_authenticated/student/resources/skills/$id"
import { Route as AuthenticatedProviderTutorialsIdEditRouteImport } from "./routes/_authenticated/provider/tutorials/$id/edit"
import { Route as AuthenticatedProviderSkillsIdEditRouteImport } from "./routes/_authenticated/provider/skills/$id/edit"

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: "/dev",
  path: "/dev",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: "/provider",
  path: "/provider",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: "/student/",
    path: "/student/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProviderIndexRoute =
  AuthenticatedProviderIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedInstructorIndexRoute =
  AuthenticatedInstructorIndexRouteImport.update({
    id: "/instructor/",
    path: "/instructor/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentSupportRoute =
  AuthenticatedStudentSupportRouteImport.update({
    id: "/student/support",
    path: "/student/support",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentSubmissionsRoute =
  AuthenticatedStudentSubmissionsRouteImport.update({
    id: "/student/submissions",
    path: "/student/submissions",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentSettingsRoute =
  AuthenticatedStudentSettingsRouteImport.update({
    id: "/student/settings",
    path: "/student/settings",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentResourcesRoute =
  AuthenticatedStudentResourcesRouteImport.update({
    id: "/student/resources",
    path: "/student/resources",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: "/student/profile",
    path: "/student/profile",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentPerformanceRoute =
  AuthenticatedStudentPerformanceRouteImport.update({
    id: "/student/performance",
    path: "/student/performance",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: "/student/dashboard",
    path: "/student/dashboard",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAssignmentsRoute =
  AuthenticatedStudentAssignmentsRouteImport.update({
    id: "/student/assignments",
    path: "/student/assignments",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProviderSettingsRoute =
  AuthenticatedProviderSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderProfileRoute =
  AuthenticatedProviderProfileRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderDashboardRoute =
  AuthenticatedProviderDashboardRouteImport.update({
    id: "/dashboard",
    path: "/dashboard",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderAssignmentsRoute =
  AuthenticatedProviderAssignmentsRouteImport.update({
    id: "/assignments",
    path: "/assignments",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderAnalyticsRoute =
  AuthenticatedProviderAnalyticsRouteImport.update({
    id: "/analytics",
    path: "/analytics",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedInstructorSupportRoute =
  AuthenticatedInstructorSupportRouteImport.update({
    id: "/instructor/support",
    path: "/instructor/support",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorSubmissionsRoute =
  AuthenticatedInstructorSubmissionsRouteImport.update({
    id: "/instructor/submissions",
    path: "/instructor/submissions",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorSettingsRoute =
  AuthenticatedInstructorSettingsRouteImport.update({
    id: "/instructor/settings",
    path: "/instructor/settings",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorScheduleRoute =
  AuthenticatedInstructorScheduleRouteImport.update({
    id: "/instructor/schedule",
    path: "/instructor/schedule",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorProfileRoute =
  AuthenticatedInstructorProfileRouteImport.update({
    id: "/instructor/profile",
    path: "/instructor/profile",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorFeedbackRoute =
  AuthenticatedInstructorFeedbackRouteImport.update({
    id: "/instructor/feedback",
    path: "/instructor/feedback",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorDashboardRoute =
  AuthenticatedInstructorDashboardRouteImport.update({
    id: "/instructor/dashboard",
    path: "/instructor/dashboard",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorAssignmentsRoute =
  AuthenticatedInstructorAssignmentsRouteImport.update({
    id: "/instructor/assignments",
    path: "/instructor/assignments",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentSubmissionsIndexRoute =
  AuthenticatedStudentSubmissionsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedStudentSubmissionsRoute,
  } as any)
const AuthenticatedStudentResourcesIndexRoute =
  AuthenticatedStudentResourcesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedStudentResourcesRoute,
  } as any)
const AuthenticatedStudentAssignmentsIndexRoute =
  AuthenticatedStudentAssignmentsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedStudentAssignmentsRoute,
  } as any)
const AuthenticatedProviderTutorialsIndexRoute =
  AuthenticatedProviderTutorialsIndexRouteImport.update({
    id: "/tutorials/",
    path: "/tutorials/",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderSkillsIndexRoute =
  AuthenticatedProviderSkillsIndexRouteImport.update({
    id: "/skills/",
    path: "/skills/",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderAssignmentsIndexRoute =
  AuthenticatedProviderAssignmentsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedProviderAssignmentsRoute,
  } as any)
const AuthenticatedStudentSubmissionsIdRoute =
  AuthenticatedStudentSubmissionsIdRouteImport.update({
    id: "/$id",
    path: "/$id",
    getParentRoute: () => AuthenticatedStudentSubmissionsRoute,
  } as any)
const AuthenticatedStudentSubmissionIdRoute =
  AuthenticatedStudentSubmissionIdRouteImport.update({
    id: "/student/submission/$id",
    path: "/student/submission/$id",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentResourcesSkillsRoute =
  AuthenticatedStudentResourcesSkillsRouteImport.update({
    id: "/skills",
    path: "/skills",
    getParentRoute: () => AuthenticatedStudentResourcesRoute,
  } as any)
const AuthenticatedStudentAssignmentsIdRoute =
  AuthenticatedStudentAssignmentsIdRouteImport.update({
    id: "/$id",
    path: "/$id",
    getParentRoute: () => AuthenticatedStudentAssignmentsRoute,
  } as any)
const AuthenticatedProviderTutorialsCreateRoute =
  AuthenticatedProviderTutorialsCreateRouteImport.update({
    id: "/tutorials/create",
    path: "/tutorials/create",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderTutorialsIdRoute =
  AuthenticatedProviderTutorialsIdRouteImport.update({
    id: "/tutorials/$id",
    path: "/tutorials/$id",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderSkillsCreateRoute =
  AuthenticatedProviderSkillsCreateRouteImport.update({
    id: "/skills/create",
    path: "/skills/create",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderSkillsIdRoute =
  AuthenticatedProviderSkillsIdRouteImport.update({
    id: "/skills/$id",
    path: "/skills/$id",
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderAssignmentsCreateRoute =
  AuthenticatedProviderAssignmentsCreateRouteImport.update({
    id: "/create",
    path: "/create",
    getParentRoute: () => AuthenticatedProviderAssignmentsRoute,
  } as any)
const AuthenticatedProviderAssignmentsIdRoute =
  AuthenticatedProviderAssignmentsIdRouteImport.update({
    id: "/$id",
    path: "/$id",
    getParentRoute: () => AuthenticatedProviderAssignmentsRoute,
  } as any)
const AuthenticatedInstructorSubmissionsIdRoute =
  AuthenticatedInstructorSubmissionsIdRouteImport.update({
    id: "/$id",
    path: "/$id",
    getParentRoute: () => AuthenticatedInstructorSubmissionsRoute,
  } as any)
const AuthenticatedInstructorAssignmentsIdRoute =
  AuthenticatedInstructorAssignmentsIdRouteImport.update({
    id: "/$id",
    path: "/$id",
    getParentRoute: () => AuthenticatedInstructorAssignmentsRoute,
  } as any)
const AuthenticatedStudentResourcesSkillsIndexRoute =
  AuthenticatedStudentResourcesSkillsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedStudentResourcesSkillsRoute,
  } as any)
const AuthenticatedStudentResourcesTutorialsIdRoute =
  AuthenticatedStudentResourcesTutorialsIdRouteImport.update({
    id: "/tutorials/$id",
    path: "/tutorials/$id",
    getParentRoute: () => AuthenticatedStudentResourcesRoute,
  } as any)
const AuthenticatedStudentResourcesSkillsIdRoute =
  AuthenticatedStudentResourcesSkillsIdRouteImport.update({
    id: "/$id",
    path: "/$id",
    getParentRoute: () => AuthenticatedStudentResourcesSkillsRoute,
  } as any)
const AuthenticatedProviderTutorialsIdEditRoute =
  AuthenticatedProviderTutorialsIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => AuthenticatedProviderTutorialsIdRoute,
  } as any)
const AuthenticatedProviderSkillsIdEditRoute =
  AuthenticatedProviderSkillsIdEditRouteImport.update({
    id: "/edit",
    path: "/edit",
    getParentRoute: () => AuthenticatedProviderSkillsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/dev": typeof DevRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/provider": typeof AuthenticatedProviderRouteWithChildren
  "/instructor/assignments": typeof AuthenticatedInstructorAssignmentsRouteWithChildren
  "/instructor/dashboard": typeof AuthenticatedInstructorDashboardRoute
  "/instructor/feedback": typeof AuthenticatedInstructorFeedbackRoute
  "/instructor/profile": typeof AuthenticatedInstructorProfileRoute
  "/instructor/schedule": typeof AuthenticatedInstructorScheduleRoute
  "/instructor/settings": typeof AuthenticatedInstructorSettingsRoute
  "/instructor/submissions": typeof AuthenticatedInstructorSubmissionsRouteWithChildren
  "/instructor/support": typeof AuthenticatedInstructorSupportRoute
  "/provider/analytics": typeof AuthenticatedProviderAnalyticsRoute
  "/provider/assignments": typeof AuthenticatedProviderAssignmentsRouteWithChildren
  "/provider/dashboard": typeof AuthenticatedProviderDashboardRoute
  "/provider/profile": typeof AuthenticatedProviderProfileRoute
  "/provider/settings": typeof AuthenticatedProviderSettingsRoute
  "/student/assignments": typeof AuthenticatedStudentAssignmentsRouteWithChildren
  "/student/dashboard": typeof AuthenticatedStudentDashboardRoute
  "/student/performance": typeof AuthenticatedStudentPerformanceRoute
  "/student/profile": typeof AuthenticatedStudentProfileRoute
  "/student/resources": typeof AuthenticatedStudentResourcesRouteWithChildren
  "/student/settings": typeof AuthenticatedStudentSettingsRoute
  "/student/submissions": typeof AuthenticatedStudentSubmissionsRouteWithChildren
  "/student/support": typeof AuthenticatedStudentSupportRoute
  "/instructor": typeof AuthenticatedInstructorIndexRoute
  "/provider/": typeof AuthenticatedProviderIndexRoute
  "/student": typeof AuthenticatedStudentIndexRoute
  "/instructor/assignments/$id": typeof AuthenticatedInstructorAssignmentsIdRoute
  "/instructor/submissions/$id": typeof AuthenticatedInstructorSubmissionsIdRoute
  "/provider/assignments/$id": typeof AuthenticatedProviderAssignmentsIdRoute
  "/provider/assignments/create": typeof AuthenticatedProviderAssignmentsCreateRoute
  "/provider/skills/$id": typeof AuthenticatedProviderSkillsIdRouteWithChildren
  "/provider/skills/create": typeof AuthenticatedProviderSkillsCreateRoute
  "/provider/tutorials/$id": typeof AuthenticatedProviderTutorialsIdRouteWithChildren
  "/provider/tutorials/create": typeof AuthenticatedProviderTutorialsCreateRoute
  "/student/assignments/$id": typeof AuthenticatedStudentAssignmentsIdRoute
  "/student/resources/skills": typeof AuthenticatedStudentResourcesSkillsRouteWithChildren
  "/student/submission/$id": typeof AuthenticatedStudentSubmissionIdRoute
  "/student/submissions/$id": typeof AuthenticatedStudentSubmissionsIdRoute
  "/provider/assignments/": typeof AuthenticatedProviderAssignmentsIndexRoute
  "/provider/skills": typeof AuthenticatedProviderSkillsIndexRoute
  "/provider/tutorials": typeof AuthenticatedProviderTutorialsIndexRoute
  "/student/assignments/": typeof AuthenticatedStudentAssignmentsIndexRoute
  "/student/resources/": typeof AuthenticatedStudentResourcesIndexRoute
  "/student/submissions/": typeof AuthenticatedStudentSubmissionsIndexRoute
  "/provider/skills/$id/edit": typeof AuthenticatedProviderSkillsIdEditRoute
  "/provider/tutorials/$id/edit": typeof AuthenticatedProviderTutorialsIdEditRoute
  "/student/resources/skills/$id": typeof AuthenticatedStudentResourcesSkillsIdRoute
  "/student/resources/tutorials/$id": typeof AuthenticatedStudentResourcesTutorialsIdRoute
  "/student/resources/skills/": typeof AuthenticatedStudentResourcesSkillsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/dev": typeof DevRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/instructor/assignments": typeof AuthenticatedInstructorAssignmentsRouteWithChildren
  "/instructor/dashboard": typeof AuthenticatedInstructorDashboardRoute
  "/instructor/feedback": typeof AuthenticatedInstructorFeedbackRoute
  "/instructor/profile": typeof AuthenticatedInstructorProfileRoute
  "/instructor/schedule": typeof AuthenticatedInstructorScheduleRoute
  "/instructor/settings": typeof AuthenticatedInstructorSettingsRoute
  "/instructor/submissions": typeof AuthenticatedInstructorSubmissionsRouteWithChildren
  "/instructor/support": typeof AuthenticatedInstructorSupportRoute
  "/provider/analytics": typeof AuthenticatedProviderAnalyticsRoute
  "/provider/dashboard": typeof AuthenticatedProviderDashboardRoute
  "/provider/profile": typeof AuthenticatedProviderProfileRoute
  "/provider/settings": typeof AuthenticatedProviderSettingsRoute
  "/student/dashboard": typeof AuthenticatedStudentDashboardRoute
  "/student/performance": typeof AuthenticatedStudentPerformanceRoute
  "/student/profile": typeof AuthenticatedStudentProfileRoute
  "/student/settings": typeof AuthenticatedStudentSettingsRoute
  "/student/support": typeof AuthenticatedStudentSupportRoute
  "/instructor": typeof AuthenticatedInstructorIndexRoute
  "/provider": typeof AuthenticatedProviderIndexRoute
  "/student": typeof AuthenticatedStudentIndexRoute
  "/instructor/assignments/$id": typeof AuthenticatedInstructorAssignmentsIdRoute
  "/instructor/submissions/$id": typeof AuthenticatedInstructorSubmissionsIdRoute
  "/provider/assignments/$id": typeof AuthenticatedProviderAssignmentsIdRoute
  "/provider/assignments/create": typeof AuthenticatedProviderAssignmentsCreateRoute
  "/provider/skills/$id": typeof AuthenticatedProviderSkillsIdRouteWithChildren
  "/provider/skills/create": typeof AuthenticatedProviderSkillsCreateRoute
  "/provider/tutorials/$id": typeof AuthenticatedProviderTutorialsIdRouteWithChildren
  "/provider/tutorials/create": typeof AuthenticatedProviderTutorialsCreateRoute
  "/student/assignments/$id": typeof AuthenticatedStudentAssignmentsIdRoute
  "/student/submission/$id": typeof AuthenticatedStudentSubmissionIdRoute
  "/student/submissions/$id": typeof AuthenticatedStudentSubmissionsIdRoute
  "/provider/assignments": typeof AuthenticatedProviderAssignmentsIndexRoute
  "/provider/skills": typeof AuthenticatedProviderSkillsIndexRoute
  "/provider/tutorials": typeof AuthenticatedProviderTutorialsIndexRoute
  "/student/assignments": typeof AuthenticatedStudentAssignmentsIndexRoute
  "/student/resources": typeof AuthenticatedStudentResourcesIndexRoute
  "/student/submissions": typeof AuthenticatedStudentSubmissionsIndexRoute
  "/provider/skills/$id/edit": typeof AuthenticatedProviderSkillsIdEditRoute
  "/provider/tutorials/$id/edit": typeof AuthenticatedProviderTutorialsIdEditRoute
  "/student/resources/skills/$id": typeof AuthenticatedStudentResourcesSkillsIdRoute
  "/student/resources/tutorials/$id": typeof AuthenticatedStudentResourcesTutorialsIdRoute
  "/student/resources/skills": typeof AuthenticatedStudentResourcesSkillsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/dev": typeof DevRoute
  "/forgot-password": typeof ForgotPasswordRoute
  "/login": typeof LoginRoute
  "/register": typeof RegisterRoute
  "/reset-password": typeof ResetPasswordRoute
  "/verify-email": typeof VerifyEmailRoute
  "/_authenticated/provider": typeof AuthenticatedProviderRouteWithChildren
  "/_authenticated/instructor/assignments": typeof AuthenticatedInstructorAssignmentsRouteWithChildren
  "/_authenticated/instructor/dashboard": typeof AuthenticatedInstructorDashboardRoute
  "/_authenticated/instructor/feedback": typeof AuthenticatedInstructorFeedbackRoute
  "/_authenticated/instructor/profile": typeof AuthenticatedInstructorProfileRoute
  "/_authenticated/instructor/schedule": typeof AuthenticatedInstructorScheduleRoute
  "/_authenticated/instructor/settings": typeof AuthenticatedInstructorSettingsRoute
  "/_authenticated/instructor/submissions": typeof AuthenticatedInstructorSubmissionsRouteWithChildren
  "/_authenticated/instructor/support": typeof AuthenticatedInstructorSupportRoute
  "/_authenticated/provider/analytics": typeof AuthenticatedProviderAnalyticsRoute
  "/_authenticated/provider/assignments": typeof AuthenticatedProviderAssignmentsRouteWithChildren
  "/_authenticated/provider/dashboard": typeof AuthenticatedProviderDashboardRoute
  "/_authenticated/provider/profile": typeof AuthenticatedProviderProfileRoute
  "/_authenticated/provider/settings": typeof AuthenticatedProviderSettingsRoute
  "/_authenticated/student/assignments": typeof AuthenticatedStudentAssignmentsRouteWithChildren
  "/_authenticated/student/dashboard": typeof AuthenticatedStudentDashboardRoute
  "/_authenticated/student/performance": typeof AuthenticatedStudentPerformanceRoute
  "/_authenticated/student/profile": typeof AuthenticatedStudentProfileRoute
  "/_authenticated/student/resources": typeof AuthenticatedStudentResourcesRouteWithChildren
  "/_authenticated/student/settings": typeof AuthenticatedStudentSettingsRoute
  "/_authenticated/student/submissions": typeof AuthenticatedStudentSubmissionsRouteWithChildren
  "/_authenticated/student/support": typeof AuthenticatedStudentSupportRoute
  "/_authenticated/instructor/": typeof AuthenticatedInstructorIndexRoute
  "/_authenticated/provider/": typeof AuthenticatedProviderIndexRoute
  "/_authenticated/student/": typeof AuthenticatedStudentIndexRoute
  "/_authenticated/instructor/assignments/$id": typeof AuthenticatedInstructorAssignmentsIdRoute
  "/_authenticated/instructor/submissions/$id": typeof AuthenticatedInstructorSubmissionsIdRoute
  "/_authenticated/provider/assignments/$id": typeof AuthenticatedProviderAssignmentsIdRoute
  "/_authenticated/provider/assignments/create": typeof AuthenticatedProviderAssignmentsCreateRoute
  "/_authenticated/provider/skills/$id": typeof AuthenticatedProviderSkillsIdRouteWithChildren
  "/_authenticated/provider/skills/create": typeof AuthenticatedProviderSkillsCreateRoute
  "/_authenticated/provider/tutorials/$id": typeof AuthenticatedProviderTutorialsIdRouteWithChildren
  "/_authenticated/provider/tutorials/create": typeof AuthenticatedProviderTutorialsCreateRoute
  "/_authenticated/student/assignments/$id": typeof AuthenticatedStudentAssignmentsIdRoute
  "/_authenticated/student/resources/skills": typeof AuthenticatedStudentResourcesSkillsRouteWithChildren
  "/_authenticated/student/submission/$id": typeof AuthenticatedStudentSubmissionIdRoute
  "/_authenticated/student/submissions/$id": typeof AuthenticatedStudentSubmissionsIdRoute
  "/_authenticated/provider/assignments/": typeof AuthenticatedProviderAssignmentsIndexRoute
  "/_authenticated/provider/skills/": typeof AuthenticatedProviderSkillsIndexRoute
  "/_authenticated/provider/tutorials/": typeof AuthenticatedProviderTutorialsIndexRoute
  "/_authenticated/student/assignments/": typeof AuthenticatedStudentAssignmentsIndexRoute
  "/_authenticated/student/resources/": typeof AuthenticatedStudentResourcesIndexRoute
  "/_authenticated/student/submissions/": typeof AuthenticatedStudentSubmissionsIndexRoute
  "/_authenticated/provider/skills/$id/edit": typeof AuthenticatedProviderSkillsIdEditRoute
  "/_authenticated/provider/tutorials/$id/edit": typeof AuthenticatedProviderTutorialsIdEditRoute
  "/_authenticated/student/resources/skills/$id": typeof AuthenticatedStudentResourcesSkillsIdRoute
  "/_authenticated/student/resources/tutorials/$id": typeof AuthenticatedStudentResourcesTutorialsIdRoute
  "/_authenticated/student/resources/skills/": typeof AuthenticatedStudentResourcesSkillsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/dev"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/provider"
    | "/instructor/assignments"
    | "/instructor/dashboard"
    | "/instructor/feedback"
    | "/instructor/profile"
    | "/instructor/schedule"
    | "/instructor/settings"
    | "/instructor/submissions"
    | "/instructor/support"
    | "/provider/analytics"
    | "/provider/assignments"
    | "/provider/dashboard"
    | "/provider/profile"
    | "/provider/settings"
    | "/student/assignments"
    | "/student/dashboard"
    | "/student/performance"
    | "/student/profile"
    | "/student/resources"
    | "/student/settings"
    | "/student/submissions"
    | "/student/support"
    | "/instructor"
    | "/provider/"
    | "/student"
    | "/instructor/assignments/$id"
    | "/instructor/submissions/$id"
    | "/provider/assignments/$id"
    | "/provider/assignments/create"
    | "/provider/skills/$id"
    | "/provider/skills/create"
    | "/provider/tutorials/$id"
    | "/provider/tutorials/create"
    | "/student/assignments/$id"
    | "/student/resources/skills"
    | "/student/submission/$id"
    | "/student/submissions/$id"
    | "/provider/assignments/"
    | "/provider/skills"
    | "/provider/tutorials"
    | "/student/assignments/"
    | "/student/resources/"
    | "/student/submissions/"
    | "/provider/skills/$id/edit"
    | "/provider/tutorials/$id/edit"
    | "/student/resources/skills/$id"
    | "/student/resources/tutorials/$id"
    | "/student/resources/skills/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/dev"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/instructor/assignments"
    | "/instructor/dashboard"
    | "/instructor/feedback"
    | "/instructor/profile"
    | "/instructor/schedule"
    | "/instructor/settings"
    | "/instructor/submissions"
    | "/instructor/support"
    | "/provider/analytics"
    | "/provider/dashboard"
    | "/provider/profile"
    | "/provider/settings"
    | "/student/dashboard"
    | "/student/performance"
    | "/student/profile"
    | "/student/settings"
    | "/student/support"
    | "/instructor"
    | "/provider"
    | "/student"
    | "/instructor/assignments/$id"
    | "/instructor/submissions/$id"
    | "/provider/assignments/$id"
    | "/provider/assignments/create"
    | "/provider/skills/$id"
    | "/provider/skills/create"
    | "/provider/tutorials/$id"
    | "/provider/tutorials/create"
    | "/student/assignments/$id"
    | "/student/submission/$id"
    | "/student/submissions/$id"
    | "/provider/assignments"
    | "/provider/skills"
    | "/provider/tutorials"
    | "/student/assignments"
    | "/student/resources"
    | "/student/submissions"
    | "/provider/skills/$id/edit"
    | "/provider/tutorials/$id/edit"
    | "/student/resources/skills/$id"
    | "/student/resources/tutorials/$id"
    | "/student/resources/skills"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/dev"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/verify-email"
    | "/_authenticated/provider"
    | "/_authenticated/instructor/assignments"
    | "/_authenticated/instructor/dashboard"
    | "/_authenticated/instructor/feedback"
    | "/_authenticated/instructor/profile"
    | "/_authenticated/instructor/schedule"
    | "/_authenticated/instructor/settings"
    | "/_authenticated/instructor/submissions"
    | "/_authenticated/instructor/support"
    | "/_authenticated/provider/analytics"
    | "/_authenticated/provider/assignments"
    | "/_authenticated/provider/dashboard"
    | "/_authenticated/provider/profile"
    | "/_authenticated/provider/settings"
    | "/_authenticated/student/assignments"
    | "/_authenticated/student/dashboard"
    | "/_authenticated/student/performance"
    | "/_authenticated/student/profile"
    | "/_authenticated/student/resources"
    | "/_authenticated/student/settings"
    | "/_authenticated/student/submissions"
    | "/_authenticated/student/support"
    | "/_authenticated/instructor/"
    | "/_authenticated/provider/"
    | "/_authenticated/student/"
    | "/_authenticated/instructor/assignments/$id"
    | "/_authenticated/instructor/submissions/$id"
    | "/_authenticated/provider/assignments/$id"
    | "/_authenticated/provider/assignments/create"
    | "/_authenticated/provider/skills/$id"
    | "/_authenticated/provider/skills/create"
    | "/_authenticated/provider/tutorials/$id"
    | "/_authenticated/provider/tutorials/create"
    | "/_authenticated/student/assignments/$id"
    | "/_authenticated/student/resources/skills"
    | "/_authenticated/student/submission/$id"
    | "/_authenticated/student/submissions/$id"
    | "/_authenticated/provider/assignments/"
    | "/_authenticated/provider/skills/"
    | "/_authenticated/provider/tutorials/"
    | "/_authenticated/student/assignments/"
    | "/_authenticated/student/resources/"
    | "/_authenticated/student/submissions/"
    | "/_authenticated/provider/skills/$id/edit"
    | "/_authenticated/provider/tutorials/$id/edit"
    | "/_authenticated/student/resources/skills/$id"
    | "/_authenticated/student/resources/tutorials/$id"
    | "/_authenticated/student/resources/skills/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DevRoute: typeof DevRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email"
      path: "/verify-email"
      fullPath: "/verify-email"
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password": {
      id: "/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password": {
      id: "/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dev": {
      id: "/dev"
      path: "/dev"
      fullPath: "/dev"
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/provider": {
      id: "/_authenticated/provider"
      path: "/provider"
      fullPath: "/provider"
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/": {
      id: "/_authenticated/student/"
      path: "/student"
      fullPath: "/student"
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/provider/": {
      id: "/_authenticated/provider/"
      path: "/"
      fullPath: "/provider/"
      preLoaderRoute: typeof AuthenticatedProviderIndexRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/instructor/": {
      id: "/_authenticated/instructor/"
      path: "/instructor"
      fullPath: "/instructor"
      preLoaderRoute: typeof AuthenticatedInstructorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/support": {
      id: "/_authenticated/student/support"
      path: "/student/support"
      fullPath: "/student/support"
      preLoaderRoute: typeof AuthenticatedStudentSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/submissions": {
      id: "/_authenticated/student/submissions"
      path: "/student/submissions"
      fullPath: "/student/submissions"
      preLoaderRoute: typeof AuthenticatedStudentSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/settings": {
      id: "/_authenticated/student/settings"
      path: "/student/settings"
      fullPath: "/student/settings"
      preLoaderRoute: typeof AuthenticatedStudentSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/resources": {
      id: "/_authenticated/student/resources"
      path: "/student/resources"
      fullPath: "/student/resources"
      preLoaderRoute: typeof AuthenticatedStudentResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/profile": {
      id: "/_authenticated/student/profile"
      path: "/student/profile"
      fullPath: "/student/profile"
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/performance": {
      id: "/_authenticated/student/performance"
      path: "/student/performance"
      fullPath: "/student/performance"
      preLoaderRoute: typeof AuthenticatedStudentPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/dashboard": {
      id: "/_authenticated/student/dashboard"
      path: "/student/dashboard"
      fullPath: "/student/dashboard"
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/assignments": {
      id: "/_authenticated/student/assignments"
      path: "/student/assignments"
      fullPath: "/student/assignments"
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/provider/settings": {
      id: "/_authenticated/provider/settings"
      path: "/settings"
      fullPath: "/provider/settings"
      preLoaderRoute: typeof AuthenticatedProviderSettingsRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/profile": {
      id: "/_authenticated/provider/profile"
      path: "/profile"
      fullPath: "/provider/profile"
      preLoaderRoute: typeof AuthenticatedProviderProfileRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/dashboard": {
      id: "/_authenticated/provider/dashboard"
      path: "/dashboard"
      fullPath: "/provider/dashboard"
      preLoaderRoute: typeof AuthenticatedProviderDashboardRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/assignments": {
      id: "/_authenticated/provider/assignments"
      path: "/assignments"
      fullPath: "/provider/assignments"
      preLoaderRoute: typeof AuthenticatedProviderAssignmentsRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/analytics": {
      id: "/_authenticated/provider/analytics"
      path: "/analytics"
      fullPath: "/provider/analytics"
      preLoaderRoute: typeof AuthenticatedProviderAnalyticsRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/instructor/support": {
      id: "/_authenticated/instructor/support"
      path: "/instructor/support"
      fullPath: "/instructor/support"
      preLoaderRoute: typeof AuthenticatedInstructorSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/instructor/submissions": {
      id: "/_authenticated/instructor/submissions"
      path: "/instructor/submissions"
      fullPath: "/instructor/submissions"
      preLoaderRoute: typeof AuthenticatedInstructorSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/instructor/settings": {
      id: "/_authenticated/instructor/settings"
      path: "/instructor/settings"
      fullPath: "/instructor/settings"
      preLoaderRoute: typeof AuthenticatedInstructorSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/instructor/schedule": {
      id: "/_authenticated/instructor/schedule"
      path: "/instructor/schedule"
      fullPath: "/instructor/schedule"
      preLoaderRoute: typeof AuthenticatedInstructorScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/instructor/profile": {
      id: "/_authenticated/instructor/profile"
      path: "/instructor/profile"
      fullPath: "/instructor/profile"
      preLoaderRoute: typeof AuthenticatedInstructorProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/instructor/feedback": {
      id: "/_authenticated/instructor/feedback"
      path: "/instructor/feedback"
      fullPath: "/instructor/feedback"
      preLoaderRoute: typeof AuthenticatedInstructorFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/instructor/dashboard": {
      id: "/_authenticated/instructor/dashboard"
      path: "/instructor/dashboard"
      fullPath: "/instructor/dashboard"
      preLoaderRoute: typeof AuthenticatedInstructorDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/instructor/assignments": {
      id: "/_authenticated/instructor/assignments"
      path: "/instructor/assignments"
      fullPath: "/instructor/assignments"
      preLoaderRoute: typeof AuthenticatedInstructorAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/submissions/": {
      id: "/_authenticated/student/submissions/"
      path: "/"
      fullPath: "/student/submissions/"
      preLoaderRoute: typeof AuthenticatedStudentSubmissionsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentSubmissionsRoute
    }
    "/_authenticated/student/resources/": {
      id: "/_authenticated/student/resources/"
      path: "/"
      fullPath: "/student/resources/"
      preLoaderRoute: typeof AuthenticatedStudentResourcesIndexRouteImport
      parentRoute: typeof AuthenticatedStudentResourcesRoute
    }
    "/_authenticated/student/assignments/": {
      id: "/_authenticated/student/assignments/"
      path: "/"
      fullPath: "/student/assignments/"
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentAssignmentsRoute
    }
    "/_authenticated/provider/tutorials/": {
      id: "/_authenticated/provider/tutorials/"
      path: "/tutorials"
      fullPath: "/provider/tutorials"
      preLoaderRoute: typeof AuthenticatedProviderTutorialsIndexRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/skills/": {
      id: "/_authenticated/provider/skills/"
      path: "/skills"
      fullPath: "/provider/skills"
      preLoaderRoute: typeof AuthenticatedProviderSkillsIndexRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/assignments/": {
      id: "/_authenticated/provider/assignments/"
      path: "/"
      fullPath: "/provider/assignments/"
      preLoaderRoute: typeof AuthenticatedProviderAssignmentsIndexRouteImport
      parentRoute: typeof AuthenticatedProviderAssignmentsRoute
    }
    "/_authenticated/student/submissions/$id": {
      id: "/_authenticated/student/submissions/$id"
      path: "/$id"
      fullPath: "/student/submissions/$id"
      preLoaderRoute: typeof AuthenticatedStudentSubmissionsIdRouteImport
      parentRoute: typeof AuthenticatedStudentSubmissionsRoute
    }
    "/_authenticated/student/submission/$id": {
      id: "/_authenticated/student/submission/$id"
      path: "/student/submission/$id"
      fullPath: "/student/submission/$id"
      preLoaderRoute: typeof AuthenticatedStudentSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/student/resources/skills": {
      id: "/_authenticated/student/resources/skills"
      path: "/skills"
      fullPath: "/student/resources/skills"
      preLoaderRoute: typeof AuthenticatedStudentResourcesSkillsRouteImport
      parentRoute: typeof AuthenticatedStudentResourcesRoute
    }
    "/_authenticated/student/assignments/$id": {
      id: "/_authenticated/student/assignments/$id"
      path: "/$id"
      fullPath: "/student/assignments/$id"
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentAssignmentsRoute
    }
    "/_authenticated/provider/tutorials/create": {
      id: "/_authenticated/provider/tutorials/create"
      path: "/tutorials/create"
      fullPath: "/provider/tutorials/create"
      preLoaderRoute: typeof AuthenticatedProviderTutorialsCreateRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/tutorials/$id": {
      id: "/_authenticated/provider/tutorials/$id"
      path: "/tutorials/$id"
      fullPath: "/provider/tutorials/$id"
      preLoaderRoute: typeof AuthenticatedProviderTutorialsIdRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/skills/create": {
      id: "/_authenticated/provider/skills/create"
      path: "/skills/create"
      fullPath: "/provider/skills/create"
      preLoaderRoute: typeof AuthenticatedProviderSkillsCreateRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/skills/$id": {
      id: "/_authenticated/provider/skills/$id"
      path: "/skills/$id"
      fullPath: "/provider/skills/$id"
      preLoaderRoute: typeof AuthenticatedProviderSkillsIdRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    "/_authenticated/provider/assignments/create": {
      id: "/_authenticated/provider/assignments/create"
      path: "/create"
      fullPath: "/provider/assignments/create"
      preLoaderRoute: typeof AuthenticatedProviderAssignmentsCreateRouteImport
      parentRoute: typeof AuthenticatedProviderAssignmentsRoute
    }
    "/_authenticated/provider/assignments/$id": {
      id: "/_authenticated/provider/assignments/$id"
      path: "/$id"
      fullPath: "/provider/assignments/$id"
      preLoaderRoute: typeof AuthenticatedProviderAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedProviderAssignmentsRoute
    }
    "/_authenticated/instructor/submissions/$id": {
      id: "/_authenticated/instructor/submissions/$id"
      path: "/$id"
      fullPath: "/instructor/submissions/$id"
      preLoaderRoute: typeof AuthenticatedInstructorSubmissionsIdRouteImport
      parentRoute: typeof AuthenticatedInstructorSubmissionsRoute
    }
    "/_authenticated/instructor/assignments/$id": {
      id: "/_authenticated/instructor/assignments/$id"
      path: "/$id"
      fullPath: "/instructor/assignments/$id"
      preLoaderRoute: typeof AuthenticatedInstructorAssignmentsIdRouteImport
      parentRoute: typeof AuthenticatedInstructorAssignmentsRoute
    }
    "/_authenticated/student/resources/skills/": {
      id: "/_authenticated/student/resources/skills/"
      path: "/"
      fullPath: "/student/resources/skills/"
      preLoaderRoute: typeof AuthenticatedStudentResourcesSkillsIndexRouteImport
      parentRoute: typeof AuthenticatedStudentResourcesSkillsRoute
    }
    "/_authenticated/student/resources/tutorials/$id": {
      id: "/_authenticated/student/resources/tutorials/$id"
      path: "/tutorials/$id"
      fullPath: "/student/resources/tutorials/$id"
      preLoaderRoute: typeof AuthenticatedStudentResourcesTutorialsIdRouteImport
      parentRoute: typeof AuthenticatedStudentResourcesRoute
    }
    "/_authenticated/student/resources/skills/$id": {
      id: "/_authenticated/student/resources/skills/$id"
      path: "/$id"
      fullPath: "/student/resources/skills/$id"
      preLoaderRoute: typeof AuthenticatedStudentResourcesSkillsIdRouteImport
      parentRoute: typeof AuthenticatedStudentResourcesSkillsRoute
    }
    "/_authenticated/provider/tutorials/$id/edit": {
      id: "/_authenticated/provider/tutorials/$id/edit"
      path: "/edit"
      fullPath: "/provider/tutorials/$id/edit"
      preLoaderRoute: typeof AuthenticatedProviderTutorialsIdEditRouteImport
      parentRoute: typeof AuthenticatedProviderTutorialsIdRoute
    }
    "/_authenticated/provider/skills/$id/edit": {
      id: "/_authenticated/provider/skills/$id/edit"
      path: "/edit"
      fullPath: "/provider/skills/$id/edit"
      preLoaderRoute: typeof AuthenticatedProviderSkillsIdEditRouteImport
      parentRoute: typeof AuthenticatedProviderSkillsIdRoute
    }
  }
}

interface AuthenticatedProviderAssignmentsRouteChildren {
  AuthenticatedProviderAssignmentsIdRoute: typeof AuthenticatedProviderAssignmentsIdRoute
  AuthenticatedProviderAssignmentsCreateRoute: typeof AuthenticatedProviderAssignmentsCreateRoute
  AuthenticatedProviderAssignmentsIndexRoute: typeof AuthenticatedProviderAssignmentsIndexRoute
}

const AuthenticatedProviderAssignmentsRouteChildren: AuthenticatedProviderAssignmentsRouteChildren =
  {
    AuthenticatedProviderAssignmentsIdRoute:
      AuthenticatedProviderAssignmentsIdRoute,
    AuthenticatedProviderAssignmentsCreateRoute:
      AuthenticatedProviderAssignmentsCreateRoute,
    AuthenticatedProviderAssignmentsIndexRoute:
      AuthenticatedProviderAssignmentsIndexRoute,
  }

const AuthenticatedProviderAssignmentsRouteWithChildren =
  AuthenticatedProviderAssignmentsRoute._addFileChildren(
    AuthenticatedProviderAssignmentsRouteChildren,
  )

interface AuthenticatedProviderSkillsIdRouteChildren {
  AuthenticatedProviderSkillsIdEditRoute: typeof AuthenticatedProviderSkillsIdEditRoute
}

const AuthenticatedProviderSkillsIdRouteChildren: AuthenticatedProviderSkillsIdRouteChildren =
  {
    AuthenticatedProviderSkillsIdEditRoute:
      AuthenticatedProviderSkillsIdEditRoute,
  }

const AuthenticatedProviderSkillsIdRouteWithChildren =
  AuthenticatedProviderSkillsIdRoute._addFileChildren(
    AuthenticatedProviderSkillsIdRouteChildren,
  )

interface AuthenticatedProviderTutorialsIdRouteChildren {
  AuthenticatedProviderTutorialsIdEditRoute: typeof AuthenticatedProviderTutorialsIdEditRoute
}

const AuthenticatedProviderTutorialsIdRouteChildren: AuthenticatedProviderTutorialsIdRouteChildren =
  {
    AuthenticatedProviderTutorialsIdEditRoute:
      AuthenticatedProviderTutorialsIdEditRoute,
  }

const AuthenticatedProviderTutorialsIdRouteWithChildren =
  AuthenticatedProviderTutorialsIdRoute._addFileChildren(
    AuthenticatedProviderTutorialsIdRouteChildren,
  )

interface AuthenticatedProviderRouteChildren {
  AuthenticatedProviderAnalyticsRoute: typeof AuthenticatedProviderAnalyticsRoute
  AuthenticatedProviderAssignmentsRoute: typeof AuthenticatedProviderAssignmentsRouteWithChildren
  AuthenticatedProviderDashboardRoute: typeof AuthenticatedProviderDashboardRoute
  AuthenticatedProviderProfileRoute: typeof AuthenticatedProviderProfileRoute
  AuthenticatedProviderSettingsRoute: typeof AuthenticatedProviderSettingsRoute
  AuthenticatedProviderIndexRoute: typeof AuthenticatedProviderIndexRoute
  AuthenticatedProviderSkillsIdRoute: typeof AuthenticatedProviderSkillsIdRouteWithChildren
  AuthenticatedProviderSkillsCreateRoute: typeof AuthenticatedProviderSkillsCreateRoute
  AuthenticatedProviderTutorialsIdRoute: typeof AuthenticatedProviderTutorialsIdRouteWithChildren
  AuthenticatedProviderTutorialsCreateRoute: typeof AuthenticatedProviderTutorialsCreateRoute
  AuthenticatedProviderSkillsIndexRoute: typeof AuthenticatedProviderSkillsIndexRoute
  AuthenticatedProviderTutorialsIndexRoute: typeof AuthenticatedProviderTutorialsIndexRoute
}

const AuthenticatedProviderRouteChildren: AuthenticatedProviderRouteChildren = {
  AuthenticatedProviderAnalyticsRoute: AuthenticatedProviderAnalyticsRoute,
  AuthenticatedProviderAssignmentsRoute:
    AuthenticatedProviderAssignmentsRouteWithChildren,
  AuthenticatedProviderDashboardRoute: AuthenticatedProviderDashboardRoute,
  AuthenticatedProviderProfileRoute: AuthenticatedProviderProfileRoute,
  AuthenticatedProviderSettingsRoute: AuthenticatedProviderSettingsRoute,
  AuthenticatedProviderIndexRoute: AuthenticatedProviderIndexRoute,
  AuthenticatedProviderSkillsIdRoute:
    AuthenticatedProviderSkillsIdRouteWithChildren,
  AuthenticatedProviderSkillsCreateRoute:
    AuthenticatedProviderSkillsCreateRoute,
  AuthenticatedProviderTutorialsIdRoute:
    AuthenticatedProviderTutorialsIdRouteWithChildren,
  AuthenticatedProviderTutorialsCreateRoute:
    AuthenticatedProviderTutorialsCreateRoute,
  AuthenticatedProviderSkillsIndexRoute: AuthenticatedProviderSkillsIndexRoute,
  AuthenticatedProviderTutorialsIndexRoute:
    AuthenticatedProviderTutorialsIndexRoute,
}

const AuthenticatedProviderRouteWithChildren =
  AuthenticatedProviderRoute._addFileChildren(
    AuthenticatedProviderRouteChildren,
  )

interface AuthenticatedInstructorAssignmentsRouteChildren {
  AuthenticatedInstructorAssignmentsIdRoute: typeof AuthenticatedInstructorAssignmentsIdRoute
}

const AuthenticatedInstructorAssignmentsRouteChildren: AuthenticatedInstructorAssignmentsRouteChildren =
  {
    AuthenticatedInstructorAssignmentsIdRoute:
      AuthenticatedInstructorAssignmentsIdRoute,
  }

const AuthenticatedInstructorAssignmentsRouteWithChildren =
  AuthenticatedInstructorAssignmentsRoute._addFileChildren(
    AuthenticatedInstructorAssignmentsRouteChildren,
  )

interface AuthenticatedInstructorSubmissionsRouteChildren {
  AuthenticatedInstructorSubmissionsIdRoute: typeof AuthenticatedInstructorSubmissionsIdRoute
}

const AuthenticatedInstructorSubmissionsRouteChildren: AuthenticatedInstructorSubmissionsRouteChildren =
  {
    AuthenticatedInstructorSubmissionsIdRoute:
      AuthenticatedInstructorSubmissionsIdRoute,
  }

const AuthenticatedInstructorSubmissionsRouteWithChildren =
  AuthenticatedInstructorSubmissionsRoute._addFileChildren(
    AuthenticatedInstructorSubmissionsRouteChildren,
  )

interface AuthenticatedStudentAssignmentsRouteChildren {
  AuthenticatedStudentAssignmentsIdRoute: typeof AuthenticatedStudentAssignmentsIdRoute
  AuthenticatedStudentAssignmentsIndexRoute: typeof AuthenticatedStudentAssignmentsIndexRoute
}

const AuthenticatedStudentAssignmentsRouteChildren: AuthenticatedStudentAssignmentsRouteChildren =
  {
    AuthenticatedStudentAssignmentsIdRoute:
      AuthenticatedStudentAssignmentsIdRoute,
    AuthenticatedStudentAssignmentsIndexRoute:
      AuthenticatedStudentAssignmentsIndexRoute,
  }

const AuthenticatedStudentAssignmentsRouteWithChildren =
  AuthenticatedStudentAssignmentsRoute._addFileChildren(
    AuthenticatedStudentAssignmentsRouteChildren,
  )

interface AuthenticatedStudentResourcesSkillsRouteChildren {
  AuthenticatedStudentResourcesSkillsIdRoute: typeof AuthenticatedStudentResourcesSkillsIdRoute
  AuthenticatedStudentResourcesSkillsIndexRoute: typeof AuthenticatedStudentResourcesSkillsIndexRoute
}

const AuthenticatedStudentResourcesSkillsRouteChildren: AuthenticatedStudentResourcesSkillsRouteChildren =
  {
    AuthenticatedStudentResourcesSkillsIdRoute:
      AuthenticatedStudentResourcesSkillsIdRoute,
    AuthenticatedStudentResourcesSkillsIndexRoute:
      AuthenticatedStudentResourcesSkillsIndexRoute,
  }

const AuthenticatedStudentResourcesSkillsRouteWithChildren =
  AuthenticatedStudentResourcesSkillsRoute._addFileChildren(
    AuthenticatedStudentResourcesSkillsRouteChildren,
  )

interface AuthenticatedStudentResourcesRouteChildren {
  AuthenticatedStudentResourcesSkillsRoute: typeof AuthenticatedStudentResourcesSkillsRouteWithChildren
  AuthenticatedStudentResourcesIndexRoute: typeof AuthenticatedStudentResourcesIndexRoute
  AuthenticatedStudentResourcesTutorialsIdRoute: typeof AuthenticatedStudentResourcesTutorialsIdRoute
}

const AuthenticatedStudentResourcesRouteChildren: AuthenticatedStudentResourcesRouteChildren =
  {
    AuthenticatedStudentResourcesSkillsRoute:
      AuthenticatedStudentResourcesSkillsRouteWithChildren,
    AuthenticatedStudentResourcesIndexRoute:
      AuthenticatedStudentResourcesIndexRoute,
    AuthenticatedStudentResourcesTutorialsIdRoute:
      AuthenticatedStudentResourcesTutorialsIdRoute,
  }

const AuthenticatedStudentResourcesRouteWithChildren =
  AuthenticatedStudentResourcesRoute._addFileChildren(
    AuthenticatedStudentResourcesRouteChildren,
  )

interface AuthenticatedStudentSubmissionsRouteChildren {
  AuthenticatedStudentSubmissionsIdRoute: typeof AuthenticatedStudentSubmissionsIdRoute
  AuthenticatedStudentSubmissionsIndexRoute: typeof AuthenticatedStudentSubmissionsIndexRoute
}

const AuthenticatedStudentSubmissionsRouteChildren: AuthenticatedStudentSubmissionsRouteChildren =
  {
    AuthenticatedStudentSubmissionsIdRoute:
      AuthenticatedStudentSubmissionsIdRoute,
    AuthenticatedStudentSubmissionsIndexRoute:
      AuthenticatedStudentSubmissionsIndexRoute,
  }

const AuthenticatedStudentSubmissionsRouteWithChildren =
  AuthenticatedStudentSubmissionsRoute._addFileChildren(
    AuthenticatedStudentSubmissionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRouteWithChildren
  AuthenticatedInstructorAssignmentsRoute: typeof AuthenticatedInstructorAssignmentsRouteWithChildren
  AuthenticatedInstructorDashboardRoute: typeof AuthenticatedInstructorDashboardRoute
  AuthenticatedInstructorFeedbackRoute: typeof AuthenticatedInstructorFeedbackRoute
  AuthenticatedInstructorProfileRoute: typeof AuthenticatedInstructorProfileRoute
  AuthenticatedInstructorScheduleRoute: typeof AuthenticatedInstructorScheduleRoute
  AuthenticatedInstructorSettingsRoute: typeof AuthenticatedInstructorSettingsRoute
  AuthenticatedInstructorSubmissionsRoute: typeof AuthenticatedInstructorSubmissionsRouteWithChildren
  AuthenticatedInstructorSupportRoute: typeof AuthenticatedInstructorSupportRoute
  AuthenticatedStudentAssignmentsRoute: typeof AuthenticatedStudentAssignmentsRouteWithChildren
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentPerformanceRoute: typeof AuthenticatedStudentPerformanceRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentResourcesRoute: typeof AuthenticatedStudentResourcesRouteWithChildren
  AuthenticatedStudentSettingsRoute: typeof AuthenticatedStudentSettingsRoute
  AuthenticatedStudentSubmissionsRoute: typeof AuthenticatedStudentSubmissionsRouteWithChildren
  AuthenticatedStudentSupportRoute: typeof AuthenticatedStudentSupportRoute
  AuthenticatedInstructorIndexRoute: typeof AuthenticatedInstructorIndexRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedStudentSubmissionIdRoute: typeof AuthenticatedStudentSubmissionIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProviderRoute: AuthenticatedProviderRouteWithChildren,
  AuthenticatedInstructorAssignmentsRoute:
    AuthenticatedInstructorAssignmentsRouteWithChildren,
  AuthenticatedInstructorDashboardRoute: AuthenticatedInstructorDashboardRoute,
  AuthenticatedInstructorFeedbackRoute: AuthenticatedInstructorFeedbackRoute,
  AuthenticatedInstructorProfileRoute: AuthenticatedInstructorProfileRoute,
  AuthenticatedInstructorScheduleRoute: AuthenticatedInstructorScheduleRoute,
  AuthenticatedInstructorSettingsRoute: AuthenticatedInstructorSettingsRoute,
  AuthenticatedInstructorSubmissionsRoute:
    AuthenticatedInstructorSubmissionsRouteWithChildren,
  AuthenticatedInstructorSupportRoute: AuthenticatedInstructorSupportRoute,
  AuthenticatedStudentAssignmentsRoute:
    AuthenticatedStudentAssignmentsRouteWithChildren,
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentPerformanceRoute: AuthenticatedStudentPerformanceRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentResourcesRoute:
    AuthenticatedStudentResourcesRouteWithChildren,
  AuthenticatedStudentSettingsRoute: AuthenticatedStudentSettingsRoute,
  AuthenticatedStudentSubmissionsRoute:
    AuthenticatedStudentSubmissionsRouteWithChildren,
  AuthenticatedStudentSupportRoute: AuthenticatedStudentSupportRoute,
  AuthenticatedInstructorIndexRoute: AuthenticatedInstructorIndexRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedStudentSubmissionIdRoute: AuthenticatedStudentSubmissionIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DevRoute: DevRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
