-- Submission Service Seed Data
-- Students: student1, student2, student3, student4 (từ identity service)
-- Assignments: 5 bài tập từ content service (Hello World, Sum, Even/Odd, Max of Three, Factorial)

-- ============================================================================
-- SUBMISSION 1: Hello World - student1 - PASSED
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000001',
        '550e8400-e29b-41d4-a716-446655440001',
        '550e8400-e29b-41d4-a716-446655440011',
        NOW() - INTERVAL '5 days',
        'EVALUATED',
        'print("Hello, World!")',
        'python',
        'PASSED',
        10.00,
        '[
          {
            "order": 1,
            "description": "Test case 1: Basic hello world",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.05,
            "memoryUsed": 2.1
          },
          {
            "order": 2,
            "description": "Test case 2: Verify exact output",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.04,
            "memoryUsed": 2.1
          },
          {
            "order": 3,
            "description": "Test case 3: No extra whitespace",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.04,
            "memoryUsed": 2.1
          },
          {
            "order": 4,
            "description": "Test case 4: Single line output",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.05,
            "memoryUsed": 2.1
          },
          {
            "order": 5,
            "description": "Test case 5: Case sensitive",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.04,
            "memoryUsed": 2.1
          },
          {
            "order": 6,
            "description": "Test case 6: Hidden test 1",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.04,
            "memoryUsed": 2.1
          },
          {
            "order": 7,
            "description": "Test case 7: Hidden test 2",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.05,
            "memoryUsed": 2.1
          },
          {
            "order": 8,
            "description": "Test case 8: Hidden test 3",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.04,
            "memoryUsed": 2.1
          },
          {
            "order": 9,
            "description": "Test case 9: Hidden test 4",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.05,
            "memoryUsed": 2.1
          },
          {
            "order": 10,
            "description": "Test case 10: Hidden test 5",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.04,
            "memoryUsed": 2.1
          },
          {
            "order": 11,
            "description": "Test case 11: Hidden test 6",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.05,
            "memoryUsed": 2.1
          },
          {
            "order": 12,
            "description": "Test case 12: Performance test",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.04,
            "memoryUsed": 2.1
          }
        ]'::jsonb,
        NOW() - INTERVAL '5 days',
        'Perfect solution! All test cases passed.')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- SUBMISSION 2: Sum of Two Numbers - student2 - PASSED
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000002',
        '550e8400-e29b-41d4-a716-446655440002',
        '550e8400-e29b-41d4-a716-446655440012',
        NOW() - INTERVAL '4 days',
        'EVALUATED',
        '#include <stdio.h>\nint main() {\n    int a, b;\n    scanf("%d %d", &a, &b);\n    printf("%d\n", a + b);\n    return 0;\n}',
        'c',
        'PASSED',
        15.00,
        '[
          {
            "order": 1,
            "description": "Basic sum: 5 + 3",
            "hidden": false,
            "weight": 1.0,
            "input": "5 3",
            "output": "8",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "8",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 3.2
          },
          {
            "order": 2,
            "description": "Sum with zero: 10 + 0",
            "hidden": false,
            "weight": 1.0,
            "input": "10 0",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 3.2
          },
          {
            "order": 3,
            "description": "Negative numbers: -5 + 3",
            "hidden": false,
            "weight": 1.0,
            "input": "-5 3",
            "output": "-2",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-2",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 3.2
          },
          {
            "order": 4,
            "description": "Large numbers: 1000000 + 2000000",
            "hidden": false,
            "weight": 1.0,
            "input": "1000000 2000000",
            "output": "3000000",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "3000000",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 3.2
          },
          {
            "order": 5,
            "description": "Two negatives: -10 + -20",
            "hidden": false,
            "weight": 1.0,
            "input": "-10 -20",
            "output": "-30",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-30",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 3.2
          },
          {
            "order": 6,
            "description": "Hidden test 1: 100 + 200",
            "hidden": true,
            "weight": 1.0,
            "input": "100 200",
            "output": "300",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "300",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 3.2
          },
          {
            "order": 7,
            "description": "Hidden test 2: -100 + 100",
            "hidden": true,
            "weight": 1.0,
            "input": "-100 100",
            "output": "0",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "0",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 3.2
          },
          {
            "order": 8,
            "description": "Hidden test 3: 7 + 8",
            "hidden": true,
            "weight": 1.0,
            "input": "7 8",
            "output": "15",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "15",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 3.2
          },
          {
            "order": 9,
            "description": "Hidden test 4: 999 + 1",
            "hidden": true,
            "weight": 1.0,
            "input": "999 1",
            "output": "1000",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "1000",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 3.2
          },
          {
            "order": 10,
            "description": "Hidden test 5: -1 + -1",
            "hidden": true,
            "weight": 1.0,
            "input": "-1 -1",
            "output": "-2",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-2",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 3.2
          },
          {
            "order": 11,
            "description": "Hidden test 6: 50 + 50",
            "hidden": true,
            "weight": 1.0,
            "input": "50 50",
            "output": "100",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "100",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 3.2
          },
          {
            "order": 12,
            "description": "Hidden test 7: 333 + 667",
            "hidden": true,
            "weight": 1.0,
            "input": "333 667",
            "output": "1000",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "1000",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 3.2
          }
        ]'::jsonb,
        NOW() - INTERVAL '4 days',
        'Excellent! Clean and efficient code.')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- SUBMISSION 3: Even or Odd - student3 - PARTIAL
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000003',
        '550e8400-e29b-41d4-a716-446655440003',
        '550e8400-e29b-41d4-a716-446655440013',
        NOW() - INTERVAL '3 days',
        'EVALUATED',
        'n = int(input())\nif n % 2 == 0:\n    print("Even")\nelse:\n    print("Odd")',
        'javascript',
        'PARTIAL',
        9.00,
        '[
          {
            "order": 1,
            "description": "Test even: 4",
            "hidden": false,
            "weight": 1.0,
            "input": "4",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 2,
            "description": "Test odd: 7",
            "hidden": false,
            "weight": 1.0,
            "input": "7",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 3,
            "description": "Zero: 0",
            "hidden": false,
            "weight": 1.0,
            "input": "0",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 4,
            "description": "One: 1",
            "hidden": false,
            "weight": 1.0,
            "input": "1",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 5,
            "description": "Negative even: -10",
            "hidden": false,
            "weight": 1.0,
            "input": "-10",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 6,
            "description": "Negative odd: -15",
            "hidden": false,
            "weight": 1.0,
            "input": "-15",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 7,
            "description": "Hidden test 1: 100",
            "hidden": true,
            "weight": 1.0,
            "input": "100",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "Even",
            "errorMessage": "Timeout exceeded",
            "executionTime": 5.5,
            "memoryUsed": 512
          },
          {
            "order": 8,
            "description": "Hidden test 2: 99",
            "hidden": true,
            "weight": 1.0,
            "input": "99",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 9,
            "description": "Hidden test 3: -2",
            "hidden": true,
            "weight": 1.0,
            "input": "-2",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 10,
            "description": "Hidden test 4: 1001",
            "hidden": true,
            "weight": 1.0,
            "input": "1001",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 11,
            "description": "Hidden test 5: 2000",
            "hidden": true,
            "weight": 1.0,
            "input": "2000",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          },
          {
            "order": 12,
            "description": "Hidden test 6: -777",
            "hidden": true,
            "weight": 1.0,
            "input": "-777",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.5
          }
        ]'::jsonb,
        NOW() - INTERVAL '3 days',
        '11 out of 12 tests passed. Watch out for timeout issues.')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- SUBMISSION 4: Maximum of Three Numbers - student4 - PASSED
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000004',
        '550e8400-e29b-41d4-a716-446655440004',
        '550e8400-e29b-41d4-a716-446655440014',
        NOW() - INTERVAL '2 days',
        'EVALUATED',
        'import java.util.Scanner;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int a = sc.nextInt(), b = sc.nextInt(), c = sc.nextInt();\n        System.out.println(Math.max(Math.max(a, b), c));\n    }\n}',
        'java',
        'PASSED',
        20.00,
        '[
          {
            "order": 1,
            "description": "Max in middle: 5 10 3",
            "hidden": false,
            "weight": 1.0,
            "input": "5 10 3",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.12,
            "memoryUsed": 25.5
          },
          {
            "order": 2,
            "description": "Max at end: 3 5 10",
            "hidden": false,
            "weight": 1.0,
            "input": "3 5 10",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.11,
            "memoryUsed": 25.5
          },
          {
            "order": 3,
            "description": "Max at start: 10 5 3",
            "hidden": false,
            "weight": 1.0,
            "input": "10 5 3",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.12,
            "memoryUsed": 25.5
          },
          {
            "order": 4,
            "description": "All equal: 5 5 5",
            "hidden": false,
            "weight": 1.0,
            "input": "5 5 5",
            "output": "5",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "5",
            "errorMessage": null,
            "executionTime": 0.11,
            "memoryUsed": 25.5
          },
          {
            "order": 5,
            "description": "Negative numbers: -5 -10 -3",
            "hidden": false,
            "weight": 1.0,
            "input": "-5 -10 -3",
            "output": "-3",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-3",
            "errorMessage": null,
            "executionTime": 0.12,
            "memoryUsed": 25.5
          },
          {
            "order": 6,
            "description": "Mixed signs: -5 0 10",
            "hidden": false,
            "weight": 1.0,
            "input": "-5 0 10",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.11,
            "memoryUsed": 25.5
          },
          {
            "order": 7,
            "description": "Hidden test 1: 100 50 75",
            "hidden": true,
            "weight": 1.0,
            "input": "100 50 75",
            "output": "100",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "100",
            "errorMessage": null,
            "executionTime": 0.12,
            "memoryUsed": 25.5
          },
          {
            "order": 8,
            "description": "Hidden test 2: 1 1 2",
            "hidden": true,
            "weight": 1.0,
            "input": "1 1 2",
            "output": "2",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "2",
            "errorMessage": null,
            "executionTime": 0.11,
            "memoryUsed": 25.5
          },
          {
            "order": 9,
            "description": "Hidden test 3: -100 -50 -200",
            "hidden": true,
            "weight": 1.0,
            "input": "-100 -50 -200",
            "output": "-50",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-50",
            "errorMessage": null,
            "executionTime": 0.12,
            "memoryUsed": 25.5
          },
          {
            "order": 10,
            "description": "Hidden test 4: 0 0 0",
            "hidden": true,
            "weight": 1.0,
            "input": "0 0 0",
            "output": "0",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "0",
            "errorMessage": null,
            "executionTime": 0.11,
            "memoryUsed": 25.5
          },
          {
            "order": 11,
            "description": "Hidden test 5: 999 500 750",
            "hidden": true,
            "weight": 1.0,
            "input": "999 500 750",
            "output": "999",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "999",
            "errorMessage": null,
            "executionTime": 0.12,
            "memoryUsed": 25.5
          },
          {
            "order": 12,
            "description": "Hidden test 6: -1 -2 -3",
            "hidden": true,
            "weight": 1.0,
            "input": "-1 -2 -3",
            "output": "-1",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-1",
            "errorMessage": null,
            "executionTime": 0.11,
            "memoryUsed": 25.5
          }
        ]'::jsonb,
        NOW() - INTERVAL '2 days',
        'Perfect implementation using built-in Math library!')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- SUBMISSION 5: Factorial - student1 - FAILED (incomplete solution)
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000005',
        '550e8400-e29b-41d4-a716-446655440005',
        '550e8400-e29b-41d4-a716-446655440011',
        NOW() - INTERVAL '1 day',
        'EVALUATED',
        'def factorial(n):\n    if n == 0:\n        return 1\n    else:\n        return n * factorial(n-1)',
        'python',
        'FAILED',
        0.00,
        '[
          {
            "order": 1,
            "description": "Basic: 5!",
            "hidden": false,
            "weight": 1.0,
            "input": "5",
            "output": "120",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 2,
            "description": "Base case: 0!",
            "hidden": false,
            "weight": 1.0,
            "input": "0",
            "output": "1",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 3,
            "description": "Simple: 1!",
            "hidden": false,
            "weight": 1.0,
            "input": "1",
            "output": "1",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 4,
            "description": "Another: 3!",
            "hidden": false,
            "weight": 1.0,
            "input": "3",
            "output": "6",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 5,
            "description": "4!",
            "hidden": false,
            "weight": 1.0,
            "input": "4",
            "output": "24",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 6,
            "description": "6!",
            "hidden": false,
            "weight": 1.0,
            "input": "6",
            "output": "720",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 7,
            "description": "Hidden test 1: 2!",
            "hidden": true,
            "weight": 1.0,
            "input": "2",
            "output": "2",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 8,
            "description": "Hidden test 2: 7!",
            "hidden": true,
            "weight": 1.0,
            "input": "7",
            "output": "5040",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 9,
            "description": "Hidden test 3: 8!",
            "hidden": true,
            "weight": 1.0,
            "input": "8",
            "output": "40320",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 10,
            "description": "Hidden test 4: 10!",
            "hidden": true,
            "weight": 1.0,
            "input": "10",
            "output": "3628800",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 11,
            "description": "Hidden test 5: 9!",
            "hidden": true,
            "weight": 1.0,
            "input": "9",
            "output": "362880",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          },
          {
            "order": 12,
            "description": "Hidden test 6: 12!",
            "hidden": true,
            "weight": 1.0,
            "input": "12",
            "output": "479001600",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": false,
            "actualOutput": "",
            "errorMessage": "No output produced",
            "executionTime": 0.0,
            "memoryUsed": 0
          }
        ]'::jsonb,
        NOW() - INTERVAL '1 day',
        'Missing I/O. Need to read input and print result.')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- SUBMISSION 6: Hello World - student2 - PASSED
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000006',
        '550e8400-e29b-41d4-a716-446655440001',
        '550e8400-e29b-41d4-a716-446655440012',
        NOW() - INTERVAL '6 days',
        'EVALUATED',
        '#include <stdio.h>\nint main() {\n    printf("Hello, World!\n");\n    return 0;\n}',
        'cpp',
        'PASSED',
        10.00,
        '[
          {
            "order": 1,
            "description": "Test case 1: Basic hello world",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 5.2
          },
          {
            "order": 2,
            "description": "Test case 2: Verify exact output",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 5.2
          },
          {
            "order": 3,
            "description": "Test case 3: No extra whitespace",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 5.2
          },
          {
            "order": 4,
            "description": "Test case 4: Single line output",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 5.2
          },
          {
            "order": 5,
            "description": "Test case 5: Case sensitive",
            "hidden": false,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 5.2
          },
          {
            "order": 6,
            "description": "Test case 6: Hidden test 1",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 5.2
          },
          {
            "order": 7,
            "description": "Test case 7: Hidden test 2",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 5.2
          },
          {
            "order": 8,
            "description": "Test case 8: Hidden test 3",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 5.2
          },
          {
            "order": 9,
            "description": "Test case 9: Hidden test 4",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 5.2
          },
          {
            "order": 10,
            "description": "Test case 10: Hidden test 5",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 5.2
          },
          {
            "order": 11,
            "description": "Test case 11: Hidden test 6",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 5.2
          },
          {
            "order": 12,
            "description": "Test case 12: Performance test",
            "hidden": true,
            "weight": 1.0,
            "input": null,
            "output": "Hello, World!",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Hello, World!",
            "errorMessage": null,
            "executionTime": 0.08,
            "memoryUsed": 5.2
          }
        ]'::jsonb,
        NOW() - INTERVAL '6 days',
        'Great C++ solution!')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- SUBMISSION 7: Sum of Two Numbers - student3 - PASSED
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000007',
        '550e8400-e29b-41d4-a716-446655440002',
        '550e8400-e29b-41d4-a716-446655440013',
        NOW() - INTERVAL '5 days',
        'EVALUATED',
        'let a = parseInt(readLine());\nlet b = parseInt(readLine());\nconsole.log(a + b);',
        'javascript',
        'PASSED',
        15.00,
        '[
          {
            "order": 1,
            "description": "Basic sum: 5 + 3",
            "hidden": false,
            "weight": 1.0,
            "input": "5 3",
            "output": "8",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "8",
            "errorMessage": null,
            "executionTime": 0.15,
            "memoryUsed": 8.3
          },
          {
            "order": 2,
            "description": "Sum with zero: 10 + 0",
            "hidden": false,
            "weight": 1.0,
            "input": "10 0",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.14,
            "memoryUsed": 8.3
          },
          {
            "order": 3,
            "description": "Negative numbers: -5 + 3",
            "hidden": false,
            "weight": 1.0,
            "input": "-5 3",
            "output": "-2",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-2",
            "errorMessage": null,
            "executionTime": 0.15,
            "memoryUsed": 8.3
          },
          {
            "order": 4,
            "description": "Large numbers: 1000000 + 2000000",
            "hidden": false,
            "weight": 1.0,
            "input": "1000000 2000000",
            "output": "3000000",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "3000000",
            "errorMessage": null,
            "executionTime": 0.14,
            "memoryUsed": 8.3
          },
          {
            "order": 5,
            "description": "Two negatives: -10 + -20",
            "hidden": false,
            "weight": 1.0,
            "input": "-10 -20",
            "output": "-30",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-30",
            "errorMessage": null,
            "executionTime": 0.15,
            "memoryUsed": 8.3
          },
          {
            "order": 6,
            "description": "Hidden test 1: 100 + 200",
            "hidden": true,
            "weight": 1.0,
            "input": "100 200",
            "output": "300",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "300",
            "errorMessage": null,
            "executionTime": 0.14,
            "memoryUsed": 8.3
          },
          {
            "order": 7,
            "description": "Hidden test 2: -100 + 100",
            "hidden": true,
            "weight": 1.0,
            "input": "-100 100",
            "output": "0",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "0",
            "errorMessage": null,
            "executionTime": 0.15,
            "memoryUsed": 8.3
          },
          {
            "order": 8,
            "description": "Hidden test 3: 7 + 8",
            "hidden": true,
            "weight": 1.0,
            "input": "7 8",
            "output": "15",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "15",
            "errorMessage": null,
            "executionTime": 0.14,
            "memoryUsed": 8.3
          },
          {
            "order": 9,
            "description": "Hidden test 4: 999 + 1",
            "hidden": true,
            "weight": 1.0,
            "input": "999 1",
            "output": "1000",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "1000",
            "errorMessage": null,
            "executionTime": 0.15,
            "memoryUsed": 8.3
          },
          {
            "order": 10,
            "description": "Hidden test 5: -1 + -1",
            "hidden": true,
            "weight": 1.0,
            "input": "-1 -1",
            "output": "-2",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-2",
            "errorMessage": null,
            "executionTime": 0.14,
            "memoryUsed": 8.3
          },
          {
            "order": 11,
            "description": "Hidden test 6: 50 + 50",
            "hidden": true,
            "weight": 1.0,
            "input": "50 50",
            "output": "100",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "100",
            "errorMessage": null,
            "executionTime": 0.15,
            "memoryUsed": 8.3
          },
          {
            "order": 12,
            "description": "Hidden test 7: 333 + 667",
            "hidden": true,
            "weight": 1.0,
            "input": "333 667",
            "output": "1000",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "1000",
            "errorMessage": null,
            "executionTime": 0.14,
            "memoryUsed": 8.3
          }
        ]'::jsonb,
        NOW() - INTERVAL '5 days',
        'Well-written JavaScript solution!')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- SUBMISSION 8: Even or Odd - student4 - PASSED
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000008',
        '550e8400-e29b-41d4-a716-446655440003',
        '550e8400-e29b-41d4-a716-446655440014',
        NOW() - INTERVAL '4 days',
        'EVALUATED',
        'fun main() {\n    val num = readLine()!!.toInt()\n    if (num % 2 == 0) println("Even") else println("Odd")\n}',
        'kotlin',
        'PASSED',
        15.00,
        '[
          {
            "order": 1,
            "description": "Test even: 4",
            "hidden": false,
            "weight": 1.0,
            "input": "4",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.18,
            "memoryUsed": 32.1
          },
          {
            "order": 2,
            "description": "Test odd: 7",
            "hidden": false,
            "weight": 1.0,
            "input": "7",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.17,
            "memoryUsed": 32.1
          },
          {
            "order": 3,
            "description": "Zero: 0",
            "hidden": false,
            "weight": 1.0,
            "input": "0",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.18,
            "memoryUsed": 32.1
          },
          {
            "order": 4,
            "description": "One: 1",
            "hidden": false,
            "weight": 1.0,
            "input": "1",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.17,
            "memoryUsed": 32.1
          },
          {
            "order": 5,
            "description": "Negative even: -10",
            "hidden": false,
            "weight": 1.0,
            "input": "-10",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.18,
            "memoryUsed": 32.1
          },
          {
            "order": 6,
            "description": "Negative odd: -15",
            "hidden": false,
            "weight": 1.0,
            "input": "-15",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.17,
            "memoryUsed": 32.1
          },
          {
            "order": 7,
            "description": "Hidden test 1: 100",
            "hidden": true,
            "weight": 1.0,
            "input": "100",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.18,
            "memoryUsed": 32.1
          },
          {
            "order": 8,
            "description": "Hidden test 2: 99",
            "hidden": true,
            "weight": 1.0,
            "input": "99",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.17,
            "memoryUsed": 32.1
          },
          {
            "order": 9,
            "description": "Hidden test 3: -2",
            "hidden": true,
            "weight": 1.0,
            "input": "-2",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.18,
            "memoryUsed": 32.1
          },
          {
            "order": 10,
            "description": "Hidden test 4: 1001",
            "hidden": true,
            "weight": 1.0,
            "input": "1001",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.17,
            "memoryUsed": 32.1
          },
          {
            "order": 11,
            "description": "Hidden test 5: 2000",
            "hidden": true,
            "weight": 1.0,
            "input": "2000",
            "output": "Even",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Even",
            "errorMessage": null,
            "executionTime": 0.18,
            "memoryUsed": 32.1
          },
          {
            "order": 12,
            "description": "Hidden test 6: -777",
            "hidden": true,
            "weight": 1.0,
            "input": "-777",
            "output": "Odd",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "Odd",
            "errorMessage": null,
            "executionTime": 0.17,
            "memoryUsed": 32.1
          }
        ]'::jsonb,
        NOW() - INTERVAL '4 days',
        'Perfect Kotlin solution!')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- SUBMISSION 9: Factorial - student2 - PASSED
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000009',
        '550e8400-e29b-41d4-a716-446655440005',
        '550e8400-e29b-41d4-a716-446655440012',
        NOW() - INTERVAL '2 days',
        'EVALUATED',
        '#include <stdio.h>\nint main() {\n    int n;\n    scanf("%d", &n);\n    long long result = 1;\n    for (int i = 2; i <= n; i++) {\n        result *= i;\n    }\n    printf("%lld\n", result);\n    return 0;\n}',
        'c',
        'PASSED',
        25.00,
        '[
          {
            "order": 1,
            "description": "Basic: 5!",
            "hidden": false,
            "weight": 1.0,
            "input": "5",
            "output": "120",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "120",
            "errorMessage": null,
            "executionTime": 0.1,
            "memoryUsed": 4.2
          },
          {
            "order": 2,
            "description": "Base case: 0!",
            "hidden": false,
            "weight": 1.0,
            "input": "0",
            "output": "1",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "1",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 4.2
          },
          {
            "order": 3,
            "description": "Simple: 1!",
            "hidden": false,
            "weight": 1.0,
            "input": "1",
            "output": "1",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "1",
            "errorMessage": null,
            "executionTime": 0.1,
            "memoryUsed": 4.2
          },
          {
            "order": 4,
            "description": "Another: 3!",
            "hidden": false,
            "weight": 1.0,
            "input": "3",
            "output": "6",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "6",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 4.2
          },
          {
            "order": 5,
            "description": "4!",
            "hidden": false,
            "weight": 1.0,
            "input": "4",
            "output": "24",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "24",
            "errorMessage": null,
            "executionTime": 0.1,
            "memoryUsed": 4.2
          },
          {
            "order": 6,
            "description": "6!",
            "hidden": false,
            "weight": 1.0,
            "input": "6",
            "output": "720",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "720",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 4.2
          },
          {
            "order": 7,
            "description": "Hidden test 1: 2!",
            "hidden": true,
            "weight": 1.0,
            "input": "2",
            "output": "2",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "2",
            "errorMessage": null,
            "executionTime": 0.1,
            "memoryUsed": 4.2
          },
          {
            "order": 8,
            "description": "Hidden test 2: 7!",
            "hidden": true,
            "weight": 1.0,
            "input": "7",
            "output": "5040",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "5040",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 4.2
          },
          {
            "order": 9,
            "description": "Hidden test 3: 8!",
            "hidden": true,
            "weight": 1.0,
            "input": "8",
            "output": "40320",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "40320",
            "errorMessage": null,
            "executionTime": 0.1,
            "memoryUsed": 4.2
          },
          {
            "order": 10,
            "description": "Hidden test 4: 10!",
            "hidden": true,
            "weight": 1.0,
            "input": "10",
            "output": "3628800",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "3628800",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 4.2
          },
          {
            "order": 11,
            "description": "Hidden test 5: 9!",
            "hidden": true,
            "weight": 1.0,
            "input": "9",
            "output": "362880",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "362880",
            "errorMessage": null,
            "executionTime": 0.1,
            "memoryUsed": 4.2
          },
          {
            "order": 12,
            "description": "Hidden test 6: 12!",
            "hidden": true,
            "weight": 1.0,
            "input": "12",
            "output": "479001600",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "479001600",
            "errorMessage": null,
            "executionTime": 0.09,
            "memoryUsed": 4.2
          }
        ]'::jsonb,
        NOW() - INTERVAL '2 days',
        'Excellent! Used long long to handle large factorials.')
ON CONFLICT (id) DO NOTHING;

-- ============================================================================
-- SUBMISSION 10: Maximum of Three Numbers - student3 - PASSED
-- ============================================================================
INSERT INTO submission.submissions (id, assignment_id, student_id, submitted_at, status, code,
                                    language,
                                    result, score, test_case_results, evaluated_at, feedback)
VALUES ('80000000-0000-0000-0000-000000000010',
        '550e8400-e29b-41d4-a716-446655440004',
        '550e8400-e29b-41d4-a716-446655440013',
        NOW() - INTERVAL '1 day',
        'EVALUATED',
        'a, b, c = map(int, input().split())\nprint(max(a, b, c))',
        'python',
        'PASSED',
        20.00,
        '[
          {
            "order": 1,
            "description": "Max in middle: 5 10 3",
            "hidden": false,
            "weight": 1.0,
            "input": "5 10 3",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 2.8
          },
          {
            "order": 2,
            "description": "Max at end: 3 5 10",
            "hidden": false,
            "weight": 1.0,
            "input": "3 5 10",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.8
          },
          {
            "order": 3,
            "description": "Max at start: 10 5 3",
            "hidden": false,
            "weight": 1.0,
            "input": "10 5 3",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 2.8
          },
          {
            "order": 4,
            "description": "All equal: 5 5 5",
            "hidden": false,
            "weight": 1.0,
            "input": "5 5 5",
            "output": "5",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "5",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.8
          },
          {
            "order": 5,
            "description": "Negative numbers: -5 -10 -3",
            "hidden": false,
            "weight": 1.0,
            "input": "-5 -10 -3",
            "output": "-3",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-3",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 2.8
          },
          {
            "order": 6,
            "description": "Mixed signs: -5 0 10",
            "hidden": false,
            "weight": 1.0,
            "input": "-5 0 10",
            "output": "10",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "10",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.8
          },
          {
            "order": 7,
            "description": "Hidden test 1: 100 50 75",
            "hidden": true,
            "weight": 1.0,
            "input": "100 50 75",
            "output": "100",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "100",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 2.8
          },
          {
            "order": 8,
            "description": "Hidden test 2: 1 1 2",
            "hidden": true,
            "weight": 1.0,
            "input": "1 1 2",
            "output": "2",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "2",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.8
          },
          {
            "order": 9,
            "description": "Hidden test 3: -100 -50 -200",
            "hidden": true,
            "weight": 1.0,
            "input": "-100 -50 -200",
            "output": "-50",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-50",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 2.8
          },
          {
            "order": 10,
            "description": "Hidden test 4: 0 0 0",
            "hidden": true,
            "weight": 1.0,
            "input": "0 0 0",
            "output": "0",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "0",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.8
          },
          {
            "order": 11,
            "description": "Hidden test 5: 999 500 750",
            "hidden": true,
            "weight": 1.0,
            "input": "999 500 750",
            "output": "999",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "999",
            "errorMessage": null,
            "executionTime": 0.07,
            "memoryUsed": 2.8
          },
          {
            "order": 12,
            "description": "Hidden test 6: -1 -2 -3",
            "hidden": true,
            "weight": 1.0,
            "input": "-1 -2 -3",
            "output": "-1",
            "timeout": 2000,
            "memoryLimit": 256,
            "passed": true,
            "actualOutput": "-1",
            "errorMessage": null,
            "executionTime": 0.06,
            "memoryUsed": 2.8
          }
        ]'::jsonb,
        NOW() - INTERVAL '1 day',
        'Clean and concise Python solution!')
ON CONFLICT (id) DO NOTHING;
