// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  contentServiceArchiveAssignment,
  contentServiceCreateAssignment,
  contentServiceCreateSkill,
  contentServiceCreateTutorial,
  contentServiceDeleteAssignment,
  contentServiceDeleteSkill,
  contentServiceDeleteTutorial,
  contentServiceGetAllAssignments,
  contentServiceGetAllSkills,
  contentServiceGetAllTutorials,
  contentServiceGetAssignmentById,
  contentServiceGetSkillById,
  contentServiceGetTutorialById,
  contentServicePublishAssignment,
  contentServiceUpdateAssignment,
  contentServiceUpdateAssignmentSchedule,
  contentServiceUpdateSkill,
  contentServiceUpdateTutorial,
  evaluationServiceGetSupportedRuntimes,
  identityServiceActivateUser,
  identityServiceChangePassword,
  identityServiceCreateUser,
  identityServiceDeactivateUser,
  identityServiceDeleteUser,
  identityServiceGetAllUsers,
  identityServiceGetCurrentUser,
  identityServiceGetUserById,
  identityServiceGetUsersByRole,
  identityServiceLogin,
  identityServiceRegister,
  identityServiceRequestPasswordReset,
  identityServiceResendVerificationEmail,
  identityServiceResetPassword,
  identityServiceUpdateCurrentUserProfile,
  identityServiceVerifyEmail,
  type Options,
  submissionServiceCreateSubmission,
  submissionServiceGetAllSubmissions,
  submissionServiceGetSubmissionById,
  submissionServiceProvideFeedback,
  supportServiceCloseSession,
  supportServiceCreateSession,
  supportServiceGetSessionById,
  supportServiceListSessions,
} from "../sdk.gen"
import type {
  ContentServiceArchiveAssignmentData,
  ContentServiceArchiveAssignmentResponse,
  ContentServiceCreateAssignmentData,
  ContentServiceCreateAssignmentResponse,
  ContentServiceCreateSkillData,
  ContentServiceCreateSkillResponse,
  ContentServiceCreateTutorialData,
  ContentServiceCreateTutorialResponse,
  ContentServiceDeleteAssignmentData,
  ContentServiceDeleteAssignmentResponse,
  ContentServiceDeleteSkillData,
  ContentServiceDeleteSkillResponse,
  ContentServiceDeleteTutorialData,
  ContentServiceDeleteTutorialResponse,
  ContentServiceGetAllAssignmentsData,
  ContentServiceGetAllAssignmentsResponse,
  ContentServiceGetAllSkillsData,
  ContentServiceGetAllSkillsResponse,
  ContentServiceGetAllTutorialsData,
  ContentServiceGetAllTutorialsResponse,
  ContentServiceGetAssignmentByIdData,
  ContentServiceGetSkillByIdData,
  ContentServiceGetTutorialByIdData,
  ContentServicePublishAssignmentData,
  ContentServicePublishAssignmentResponse,
  ContentServiceUpdateAssignmentData,
  ContentServiceUpdateAssignmentResponse,
  ContentServiceUpdateAssignmentScheduleData,
  ContentServiceUpdateAssignmentScheduleResponse,
  ContentServiceUpdateSkillData,
  ContentServiceUpdateSkillResponse,
  ContentServiceUpdateTutorialData,
  ContentServiceUpdateTutorialResponse,
  EvaluationServiceGetSupportedRuntimesData,
  IdentityServiceActivateUserData,
  IdentityServiceActivateUserResponse,
  IdentityServiceChangePasswordData,
  IdentityServiceChangePasswordResponse,
  IdentityServiceCreateUserData,
  IdentityServiceCreateUserResponse,
  IdentityServiceDeactivateUserData,
  IdentityServiceDeactivateUserResponse,
  IdentityServiceDeleteUserData,
  IdentityServiceDeleteUserResponse,
  IdentityServiceGetAllUsersData,
  IdentityServiceGetAllUsersResponse,
  IdentityServiceGetCurrentUserData,
  IdentityServiceGetUserByIdData,
  IdentityServiceGetUsersByRoleData,
  IdentityServiceGetUsersByRoleResponse,
  IdentityServiceLoginData,
  IdentityServiceLoginResponse,
  IdentityServiceRegisterData,
  IdentityServiceRegisterResponse,
  IdentityServiceRequestPasswordResetData,
  IdentityServiceRequestPasswordResetResponse,
  IdentityServiceResendVerificationEmailData,
  IdentityServiceResendVerificationEmailResponse,
  IdentityServiceResetPasswordData,
  IdentityServiceResetPasswordResponse,
  IdentityServiceUpdateCurrentUserProfileData,
  IdentityServiceUpdateCurrentUserProfileResponse,
  IdentityServiceVerifyEmailData,
  IdentityServiceVerifyEmailResponse,
  SubmissionServiceCreateSubmissionData,
  SubmissionServiceCreateSubmissionResponse,
  SubmissionServiceGetAllSubmissionsData,
  SubmissionServiceGetAllSubmissionsResponse,
  SubmissionServiceGetSubmissionByIdData,
  SubmissionServiceProvideFeedbackData,
  SubmissionServiceProvideFeedbackResponse,
  SupportServiceCloseSessionData,
  SupportServiceCloseSessionError,
  SupportServiceCloseSessionResponse,
  SupportServiceCreateSessionData,
  SupportServiceCreateSessionError,
  SupportServiceCreateSessionResponse,
  SupportServiceGetSessionByIdData,
  SupportServiceListSessionsData,
  SupportServiceListSessionsResponse,
} from "../types.gen"

/**
 * Deactivate user
 * Deactivate a user account (Admin only)
 */
export const identityServiceDeactivateUserMutation = (
  options?: Partial<Options<IdentityServiceDeactivateUserData>>,
): UseMutationOptions<
  IdentityServiceDeactivateUserResponse,
  DefaultError,
  Options<IdentityServiceDeactivateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceDeactivateUserResponse,
    DefaultError,
    Options<IdentityServiceDeactivateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceDeactivateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Activate user
 * Activate a user account (Admin only)
 */
export const identityServiceActivateUserMutation = (
  options?: Partial<Options<IdentityServiceActivateUserData>>,
): UseMutationOptions<IdentityServiceActivateUserResponse, DefaultError, Options<IdentityServiceActivateUserData>> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceActivateUserResponse,
    DefaultError,
    Options<IdentityServiceActivateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceActivateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const identityServiceGetCurrentUserQueryKey = (options?: Options<IdentityServiceGetCurrentUserData>) =>
  createQueryKey("identityServiceGetCurrentUser", options)

/**
 * Get current user profile
 * Get the profile of the currently authenticated user
 */
export const identityServiceGetCurrentUserOptions = (options?: Options<IdentityServiceGetCurrentUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await identityServiceGetCurrentUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: identityServiceGetCurrentUserQueryKey(options),
  })
}

/**
 * Update current user profile
 * Update the profile of the currently authenticated user
 */
export const identityServiceUpdateCurrentUserProfileMutation = (
  options?: Partial<Options<IdentityServiceUpdateCurrentUserProfileData>>,
): UseMutationOptions<
  IdentityServiceUpdateCurrentUserProfileResponse,
  DefaultError,
  Options<IdentityServiceUpdateCurrentUserProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceUpdateCurrentUserProfileResponse,
    DefaultError,
    Options<IdentityServiceUpdateCurrentUserProfileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceUpdateCurrentUserProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const identityServiceGetAllUsersQueryKey = (options?: Options<IdentityServiceGetAllUsersData>) =>
  createQueryKey("identityServiceGetAllUsers", options)

/**
 * Get all users
 * Get all users with pagination and sorting (Admin only)
 */
export const identityServiceGetAllUsersOptions = (options?: Options<IdentityServiceGetAllUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await identityServiceGetAllUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: identityServiceGetAllUsersQueryKey(options),
  })
}

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const identityServiceGetAllUsersInfiniteQueryKey = (
  options?: Options<IdentityServiceGetAllUsersData>,
): QueryKey<Options<IdentityServiceGetAllUsersData>> => createQueryKey("identityServiceGetAllUsers", options, true)

/**
 * Get all users
 * Get all users with pagination and sorting (Admin only)
 */
export const identityServiceGetAllUsersInfiniteOptions = (options?: Options<IdentityServiceGetAllUsersData>) => {
  return infiniteQueryOptions<
    IdentityServiceGetAllUsersResponse,
    DefaultError,
    InfiniteData<IdentityServiceGetAllUsersResponse>,
    QueryKey<Options<IdentityServiceGetAllUsersData>>,
    string | Pick<QueryKey<Options<IdentityServiceGetAllUsersData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<IdentityServiceGetAllUsersData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await identityServiceGetAllUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: identityServiceGetAllUsersInfiniteQueryKey(options),
    },
  )
}

/**
 * Create user
 * Create a new user (Admin only)
 */
export const identityServiceCreateUserMutation = (
  options?: Partial<Options<IdentityServiceCreateUserData>>,
): UseMutationOptions<IdentityServiceCreateUserResponse, DefaultError, Options<IdentityServiceCreateUserData>> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceCreateUserResponse,
    DefaultError,
    Options<IdentityServiceCreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceCreateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Change password
 * Change password for the currently authenticated user
 */
export const identityServiceChangePasswordMutation = (
  options?: Partial<Options<IdentityServiceChangePasswordData>>,
): UseMutationOptions<
  IdentityServiceChangePasswordResponse,
  DefaultError,
  Options<IdentityServiceChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceChangePasswordResponse,
    DefaultError,
    Options<IdentityServiceChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceChangePassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Verify email
 * Verify user email with token
 */
export const identityServiceVerifyEmailMutation = (
  options?: Partial<Options<IdentityServiceVerifyEmailData>>,
): UseMutationOptions<IdentityServiceVerifyEmailResponse, DefaultError, Options<IdentityServiceVerifyEmailData>> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceVerifyEmailResponse,
    DefaultError,
    Options<IdentityServiceVerifyEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceVerifyEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Reset password
 * Reset password with token
 */
export const identityServiceResetPasswordMutation = (
  options?: Partial<Options<IdentityServiceResetPasswordData>>,
): UseMutationOptions<
  IdentityServiceResetPasswordResponse,
  DefaultError,
  Options<IdentityServiceResetPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceResetPasswordResponse,
    DefaultError,
    Options<IdentityServiceResetPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceResetPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Resend verification email
 * Resend email verification link
 */
export const identityServiceResendVerificationEmailMutation = (
  options?: Partial<Options<IdentityServiceResendVerificationEmailData>>,
): UseMutationOptions<
  IdentityServiceResendVerificationEmailResponse,
  DefaultError,
  Options<IdentityServiceResendVerificationEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceResendVerificationEmailResponse,
    DefaultError,
    Options<IdentityServiceResendVerificationEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceResendVerificationEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Register a new user
 * Register a new user account with student role
 */
export const identityServiceRegisterMutation = (
  options?: Partial<Options<IdentityServiceRegisterData>>,
): UseMutationOptions<IdentityServiceRegisterResponse, DefaultError, Options<IdentityServiceRegisterData>> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceRegisterResponse,
    DefaultError,
    Options<IdentityServiceRegisterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceRegister({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Login
 * Authenticate user and return JWT token
 */
export const identityServiceLoginMutation = (
  options?: Partial<Options<IdentityServiceLoginData>>,
): UseMutationOptions<IdentityServiceLoginResponse, DefaultError, Options<IdentityServiceLoginData>> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceLoginResponse,
    DefaultError,
    Options<IdentityServiceLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Request password reset
 * Request password reset link
 */
export const identityServiceRequestPasswordResetMutation = (
  options?: Partial<Options<IdentityServiceRequestPasswordResetData>>,
): UseMutationOptions<
  IdentityServiceRequestPasswordResetResponse,
  DefaultError,
  Options<IdentityServiceRequestPasswordResetData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceRequestPasswordResetResponse,
    DefaultError,
    Options<IdentityServiceRequestPasswordResetData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceRequestPasswordReset({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete user
 * Delete a user account (Admin only)
 */
export const identityServiceDeleteUserMutation = (
  options?: Partial<Options<IdentityServiceDeleteUserData>>,
): UseMutationOptions<IdentityServiceDeleteUserResponse, DefaultError, Options<IdentityServiceDeleteUserData>> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceDeleteUserResponse,
    DefaultError,
    Options<IdentityServiceDeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceDeleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const identityServiceGetUserByIdQueryKey = (options: Options<IdentityServiceGetUserByIdData>) =>
  createQueryKey("identityServiceGetUserById", options)

/**
 * Get user by ID
 * Get user details by ID (Admin and Instructor only)
 */
export const identityServiceGetUserByIdOptions = (options: Options<IdentityServiceGetUserByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await identityServiceGetUserById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: identityServiceGetUserByIdQueryKey(options),
  })
}

export const identityServiceGetUsersByRoleQueryKey = (options: Options<IdentityServiceGetUsersByRoleData>) =>
  createQueryKey("identityServiceGetUsersByRole", options)

/**
 * Get users by role
 * Get users by role with pagination and sorting (Admin and Instructor only)
 */
export const identityServiceGetUsersByRoleOptions = (options: Options<IdentityServiceGetUsersByRoleData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await identityServiceGetUsersByRole({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: identityServiceGetUsersByRoleQueryKey(options),
  })
}

export const identityServiceGetUsersByRoleInfiniteQueryKey = (
  options: Options<IdentityServiceGetUsersByRoleData>,
): QueryKey<Options<IdentityServiceGetUsersByRoleData>> =>
  createQueryKey("identityServiceGetUsersByRole", options, true)

/**
 * Get users by role
 * Get users by role with pagination and sorting (Admin and Instructor only)
 */
export const identityServiceGetUsersByRoleInfiniteOptions = (options: Options<IdentityServiceGetUsersByRoleData>) => {
  return infiniteQueryOptions<
    IdentityServiceGetUsersByRoleResponse,
    DefaultError,
    InfiniteData<IdentityServiceGetUsersByRoleResponse>,
    QueryKey<Options<IdentityServiceGetUsersByRoleData>>,
    string | Pick<QueryKey<Options<IdentityServiceGetUsersByRoleData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<IdentityServiceGetUsersByRoleData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await identityServiceGetUsersByRole({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: identityServiceGetUsersByRoleInfiniteQueryKey(options),
    },
  )
}

export const contentServiceGetAllTutorialsQueryKey = (options?: Options<ContentServiceGetAllTutorialsData>) =>
  createQueryKey("contentServiceGetAllTutorials", options)

/**
 * Get all tutorials
 * Get all available tutorials with pagination and sorting
 */
export const contentServiceGetAllTutorialsOptions = (options?: Options<ContentServiceGetAllTutorialsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetAllTutorials({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetAllTutorialsQueryKey(options),
  })
}

export const contentServiceGetAllTutorialsInfiniteQueryKey = (
  options?: Options<ContentServiceGetAllTutorialsData>,
): QueryKey<Options<ContentServiceGetAllTutorialsData>> =>
  createQueryKey("contentServiceGetAllTutorials", options, true)

/**
 * Get all tutorials
 * Get all available tutorials with pagination and sorting
 */
export const contentServiceGetAllTutorialsInfiniteOptions = (options?: Options<ContentServiceGetAllTutorialsData>) => {
  return infiniteQueryOptions<
    ContentServiceGetAllTutorialsResponse,
    DefaultError,
    InfiniteData<ContentServiceGetAllTutorialsResponse>,
    QueryKey<Options<ContentServiceGetAllTutorialsData>>,
    string | Pick<QueryKey<Options<ContentServiceGetAllTutorialsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ContentServiceGetAllTutorialsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await contentServiceGetAllTutorials({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: contentServiceGetAllTutorialsInfiniteQueryKey(options),
    },
  )
}

/**
 * Create a new tutorial
 * Create a new tutorial (Content Provider only)
 */
export const contentServiceCreateTutorialMutation = (
  options?: Partial<Options<ContentServiceCreateTutorialData>>,
): UseMutationOptions<
  ContentServiceCreateTutorialResponse,
  DefaultError,
  Options<ContentServiceCreateTutorialData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceCreateTutorialResponse,
    DefaultError,
    Options<ContentServiceCreateTutorialData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceCreateTutorial({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetAllSkillsQueryKey = (options?: Options<ContentServiceGetAllSkillsData>) =>
  createQueryKey("contentServiceGetAllSkills", options)

/**
 * Get all skills
 * Get all available skills with pagination and sorting
 */
export const contentServiceGetAllSkillsOptions = (options?: Options<ContentServiceGetAllSkillsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetAllSkills({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetAllSkillsQueryKey(options),
  })
}

export const contentServiceGetAllSkillsInfiniteQueryKey = (
  options?: Options<ContentServiceGetAllSkillsData>,
): QueryKey<Options<ContentServiceGetAllSkillsData>> => createQueryKey("contentServiceGetAllSkills", options, true)

/**
 * Get all skills
 * Get all available skills with pagination and sorting
 */
export const contentServiceGetAllSkillsInfiniteOptions = (options?: Options<ContentServiceGetAllSkillsData>) => {
  return infiniteQueryOptions<
    ContentServiceGetAllSkillsResponse,
    DefaultError,
    InfiniteData<ContentServiceGetAllSkillsResponse>,
    QueryKey<Options<ContentServiceGetAllSkillsData>>,
    string | Pick<QueryKey<Options<ContentServiceGetAllSkillsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ContentServiceGetAllSkillsData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await contentServiceGetAllSkills({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: contentServiceGetAllSkillsInfiniteQueryKey(options),
    },
  )
}

/**
 * Create a new skill
 * Create a new skill (Content Provider only)
 */
export const contentServiceCreateSkillMutation = (
  options?: Partial<Options<ContentServiceCreateSkillData>>,
): UseMutationOptions<ContentServiceCreateSkillResponse, DefaultError, Options<ContentServiceCreateSkillData>> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceCreateSkillResponse,
    DefaultError,
    Options<ContentServiceCreateSkillData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceCreateSkill({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetAllAssignmentsQueryKey = (options?: Options<ContentServiceGetAllAssignmentsData>) =>
  createQueryKey("contentServiceGetAllAssignments", options)

/**
 * Get all assignments
 * Get all available assignments with pagination and sorting
 */
export const contentServiceGetAllAssignmentsOptions = (options?: Options<ContentServiceGetAllAssignmentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetAllAssignments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetAllAssignmentsQueryKey(options),
  })
}

export const contentServiceGetAllAssignmentsInfiniteQueryKey = (
  options?: Options<ContentServiceGetAllAssignmentsData>,
): QueryKey<Options<ContentServiceGetAllAssignmentsData>> =>
  createQueryKey("contentServiceGetAllAssignments", options, true)

/**
 * Get all assignments
 * Get all available assignments with pagination and sorting
 */
export const contentServiceGetAllAssignmentsInfiniteOptions = (
  options?: Options<ContentServiceGetAllAssignmentsData>,
) => {
  return infiniteQueryOptions<
    ContentServiceGetAllAssignmentsResponse,
    DefaultError,
    InfiniteData<ContentServiceGetAllAssignmentsResponse>,
    QueryKey<Options<ContentServiceGetAllAssignmentsData>>,
    string | Pick<QueryKey<Options<ContentServiceGetAllAssignmentsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ContentServiceGetAllAssignmentsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await contentServiceGetAllAssignments({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: contentServiceGetAllAssignmentsInfiniteQueryKey(options),
    },
  )
}

/**
 * Create a new assignment
 * Create a new assignment (Content Provider only)
 */
export const contentServiceCreateAssignmentMutation = (
  options?: Partial<Options<ContentServiceCreateAssignmentData>>,
): UseMutationOptions<
  ContentServiceCreateAssignmentResponse,
  DefaultError,
  Options<ContentServiceCreateAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceCreateAssignmentResponse,
    DefaultError,
    Options<ContentServiceCreateAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceCreateAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Publish an assignment
 * Publish a draft assignment (Content Provider only)
 */
export const contentServicePublishAssignmentMutation = (
  options?: Partial<Options<ContentServicePublishAssignmentData>>,
): UseMutationOptions<
  ContentServicePublishAssignmentResponse,
  DefaultError,
  Options<ContentServicePublishAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServicePublishAssignmentResponse,
    DefaultError,
    Options<ContentServicePublishAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServicePublishAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Archive an assignment
 * Archive an assignment (Content Provider only)
 */
export const contentServiceArchiveAssignmentMutation = (
  options?: Partial<Options<ContentServiceArchiveAssignmentData>>,
): UseMutationOptions<
  ContentServiceArchiveAssignmentResponse,
  DefaultError,
  Options<ContentServiceArchiveAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceArchiveAssignmentResponse,
    DefaultError,
    Options<ContentServiceArchiveAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceArchiveAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete tutorial
 * Delete a tutorial (Content Provider only)
 */
export const contentServiceDeleteTutorialMutation = (
  options?: Partial<Options<ContentServiceDeleteTutorialData>>,
): UseMutationOptions<
  ContentServiceDeleteTutorialResponse,
  DefaultError,
  Options<ContentServiceDeleteTutorialData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceDeleteTutorialResponse,
    DefaultError,
    Options<ContentServiceDeleteTutorialData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceDeleteTutorial({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetTutorialByIdQueryKey = (options: Options<ContentServiceGetTutorialByIdData>) =>
  createQueryKey("contentServiceGetTutorialById", options)

/**
 * Get tutorial by ID
 * Get tutorial details by ID
 */
export const contentServiceGetTutorialByIdOptions = (options: Options<ContentServiceGetTutorialByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetTutorialById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetTutorialByIdQueryKey(options),
  })
}

/**
 * Update tutorial
 * Update tutorial details (Content Provider only)
 */
export const contentServiceUpdateTutorialMutation = (
  options?: Partial<Options<ContentServiceUpdateTutorialData>>,
): UseMutationOptions<
  ContentServiceUpdateTutorialResponse,
  DefaultError,
  Options<ContentServiceUpdateTutorialData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceUpdateTutorialResponse,
    DefaultError,
    Options<ContentServiceUpdateTutorialData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceUpdateTutorial({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete skill
 * Delete a skill (Content Provider only)
 */
export const contentServiceDeleteSkillMutation = (
  options?: Partial<Options<ContentServiceDeleteSkillData>>,
): UseMutationOptions<ContentServiceDeleteSkillResponse, DefaultError, Options<ContentServiceDeleteSkillData>> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceDeleteSkillResponse,
    DefaultError,
    Options<ContentServiceDeleteSkillData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceDeleteSkill({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetSkillByIdQueryKey = (options: Options<ContentServiceGetSkillByIdData>) =>
  createQueryKey("contentServiceGetSkillById", options)

/**
 * Get skill by ID
 * Get skill details by ID
 */
export const contentServiceGetSkillByIdOptions = (options: Options<ContentServiceGetSkillByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetSkillById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetSkillByIdQueryKey(options),
  })
}

/**
 * Update skill
 * Update skill details (Content Provider only)
 */
export const contentServiceUpdateSkillMutation = (
  options?: Partial<Options<ContentServiceUpdateSkillData>>,
): UseMutationOptions<ContentServiceUpdateSkillResponse, DefaultError, Options<ContentServiceUpdateSkillData>> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceUpdateSkillResponse,
    DefaultError,
    Options<ContentServiceUpdateSkillData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceUpdateSkill({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete assignment
 * Delete an assignment (Content Provider only)
 */
export const contentServiceDeleteAssignmentMutation = (
  options?: Partial<Options<ContentServiceDeleteAssignmentData>>,
): UseMutationOptions<
  ContentServiceDeleteAssignmentResponse,
  DefaultError,
  Options<ContentServiceDeleteAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceDeleteAssignmentResponse,
    DefaultError,
    Options<ContentServiceDeleteAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceDeleteAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetAssignmentByIdQueryKey = (options: Options<ContentServiceGetAssignmentByIdData>) =>
  createQueryKey("contentServiceGetAssignmentById", options)

/**
 * Get assignment by ID
 * Get assignment details by ID
 */
export const contentServiceGetAssignmentByIdOptions = (options: Options<ContentServiceGetAssignmentByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetAssignmentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetAssignmentByIdQueryKey(options),
  })
}

/**
 * Update assignment
 * Update assignment details (Content Provider only)
 */
export const contentServiceUpdateAssignmentMutation = (
  options?: Partial<Options<ContentServiceUpdateAssignmentData>>,
): UseMutationOptions<
  ContentServiceUpdateAssignmentResponse,
  DefaultError,
  Options<ContentServiceUpdateAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceUpdateAssignmentResponse,
    DefaultError,
    Options<ContentServiceUpdateAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceUpdateAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update assignment schedule
 * Update assignment schedule (start_date, due_date) (Instructor only)
 */
export const contentServiceUpdateAssignmentScheduleMutation = (
  options?: Partial<Options<ContentServiceUpdateAssignmentScheduleData>>,
): UseMutationOptions<
  ContentServiceUpdateAssignmentScheduleResponse,
  DefaultError,
  Options<ContentServiceUpdateAssignmentScheduleData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceUpdateAssignmentScheduleResponse,
    DefaultError,
    Options<ContentServiceUpdateAssignmentScheduleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceUpdateAssignmentSchedule({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const submissionServiceGetAllSubmissionsQueryKey = (options?: Options<SubmissionServiceGetAllSubmissionsData>) =>
  createQueryKey("submissionServiceGetAllSubmissions", options)

/**
 * Get all submissions
 * Get all submissions with pagination and sorting. Students see only their own, instructors can filter by assignment and student
 */
export const submissionServiceGetAllSubmissionsOptions = (
  options?: Options<SubmissionServiceGetAllSubmissionsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await submissionServiceGetAllSubmissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: submissionServiceGetAllSubmissionsQueryKey(options),
  })
}

export const submissionServiceGetAllSubmissionsInfiniteQueryKey = (
  options?: Options<SubmissionServiceGetAllSubmissionsData>,
): QueryKey<Options<SubmissionServiceGetAllSubmissionsData>> =>
  createQueryKey("submissionServiceGetAllSubmissions", options, true)

/**
 * Get all submissions
 * Get all submissions with pagination and sorting. Students see only their own, instructors can filter by assignment and student
 */
export const submissionServiceGetAllSubmissionsInfiniteOptions = (
  options?: Options<SubmissionServiceGetAllSubmissionsData>,
) => {
  return infiniteQueryOptions<
    SubmissionServiceGetAllSubmissionsResponse,
    DefaultError,
    InfiniteData<SubmissionServiceGetAllSubmissionsResponse>,
    QueryKey<Options<SubmissionServiceGetAllSubmissionsData>>,
    string | Pick<QueryKey<Options<SubmissionServiceGetAllSubmissionsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<SubmissionServiceGetAllSubmissionsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await submissionServiceGetAllSubmissions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: submissionServiceGetAllSubmissionsInfiniteQueryKey(options),
    },
  )
}

/**
 * Create a new submission
 * Submit a solution for an assignment (Students only)
 */
export const submissionServiceCreateSubmissionMutation = (
  options?: Partial<Options<SubmissionServiceCreateSubmissionData>>,
): UseMutationOptions<
  SubmissionServiceCreateSubmissionResponse,
  DefaultError,
  Options<SubmissionServiceCreateSubmissionData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmissionServiceCreateSubmissionResponse,
    DefaultError,
    Options<SubmissionServiceCreateSubmissionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await submissionServiceCreateSubmission({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Provide feedback for a submission
 * Add instructor feedback to a submission (Instructors only)
 */
export const submissionServiceProvideFeedbackMutation = (
  options?: Partial<Options<SubmissionServiceProvideFeedbackData>>,
): UseMutationOptions<
  SubmissionServiceProvideFeedbackResponse,
  DefaultError,
  Options<SubmissionServiceProvideFeedbackData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmissionServiceProvideFeedbackResponse,
    DefaultError,
    Options<SubmissionServiceProvideFeedbackData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await submissionServiceProvideFeedback({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const submissionServiceGetSubmissionByIdQueryKey = (options: Options<SubmissionServiceGetSubmissionByIdData>) =>
  createQueryKey("submissionServiceGetSubmissionById", options)

/**
 * Get submission by ID
 * Get submission details by ID. Students can only view their own, instructors can view all
 */
export const submissionServiceGetSubmissionByIdOptions = (options: Options<SubmissionServiceGetSubmissionByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await submissionServiceGetSubmissionById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: submissionServiceGetSubmissionByIdQueryKey(options),
  })
}

export const evaluationServiceGetSupportedRuntimesQueryKey = (
  options?: Options<EvaluationServiceGetSupportedRuntimesData>,
) => createQueryKey("evaluationServiceGetSupportedRuntimes", options)

/**
 * Get supported runtimes
 * Returns list of all supported programming languages and their versions
 */
export const evaluationServiceGetSupportedRuntimesOptions = (
  options?: Options<EvaluationServiceGetSupportedRuntimesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await evaluationServiceGetSupportedRuntimes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: evaluationServiceGetSupportedRuntimesQueryKey(options),
  })
}

export const supportServiceListSessionsQueryKey = (options?: Options<SupportServiceListSessionsData>) =>
  createQueryKey("supportServiceListSessions", options)

/**
 * List all support sessions
 * Instructors view all sessions with pagination, students view their own
 */
export const supportServiceListSessionsOptions = (options?: Options<SupportServiceListSessionsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await supportServiceListSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: supportServiceListSessionsQueryKey(options),
  })
}

export const supportServiceListSessionsInfiniteQueryKey = (
  options?: Options<SupportServiceListSessionsData>,
): QueryKey<Options<SupportServiceListSessionsData>> => createQueryKey("supportServiceListSessions", options, true)

/**
 * List all support sessions
 * Instructors view all sessions with pagination, students view their own
 */
export const supportServiceListSessionsInfiniteOptions = (options?: Options<SupportServiceListSessionsData>) => {
  return infiniteQueryOptions<
    SupportServiceListSessionsResponse,
    DefaultError,
    InfiniteData<SupportServiceListSessionsResponse>,
    QueryKey<Options<SupportServiceListSessionsData>>,
    string | Pick<QueryKey<Options<SupportServiceListSessionsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<SupportServiceListSessionsData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await supportServiceListSessions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: supportServiceListSessionsInfiniteQueryKey(options),
    },
  )
}

/**
 * Create a new support session
 * Students can create support sessions
 */
export const supportServiceCreateSessionMutation = (
  options?: Partial<Options<SupportServiceCreateSessionData>>,
): UseMutationOptions<
  SupportServiceCreateSessionResponse,
  SupportServiceCreateSessionError,
  Options<SupportServiceCreateSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    SupportServiceCreateSessionResponse,
    SupportServiceCreateSessionError,
    Options<SupportServiceCreateSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await supportServiceCreateSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Close a support session
 * Only the student who created the session can close it
 */
export const supportServiceCloseSessionMutation = (
  options?: Partial<Options<SupportServiceCloseSessionData>>,
): UseMutationOptions<
  SupportServiceCloseSessionResponse,
  SupportServiceCloseSessionError,
  Options<SupportServiceCloseSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    SupportServiceCloseSessionResponse,
    SupportServiceCloseSessionError,
    Options<SupportServiceCloseSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await supportServiceCloseSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const supportServiceGetSessionByIdQueryKey = (options: Options<SupportServiceGetSessionByIdData>) =>
  createQueryKey("supportServiceGetSessionById", options)

/**
 * Get support session by ID
 * Instructors can view all, students can view their own
 */
export const supportServiceGetSessionByIdOptions = (options: Options<SupportServiceGetSessionByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await supportServiceGetSessionById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: supportServiceGetSessionByIdQueryKey(options),
  })
}
