// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  contentServiceArchiveAssignment,
  contentServiceCreateAssignment,
  contentServiceCreateSkill,
  contentServiceCreateTutorial,
  contentServiceDeleteAssignment,
  contentServiceDeleteSkill,
  contentServiceDeleteTutorial,
  contentServiceGetAllAssignments,
  contentServiceGetAllSkills,
  contentServiceGetAllTutorials,
  contentServiceGetAssignmentById,
  contentServiceGetSkillById,
  contentServiceGetTutorialById,
  contentServicePublishAssignment,
  contentServiceUpdateAssignment,
  contentServiceUpdateAssignmentSchedule,
  contentServiceUpdateSkill,
  contentServiceUpdateTutorial,
  evaluationServiceGetSupportedRuntimes,
  identityServiceActivateUser,
  identityServiceChangePassword,
  identityServiceCreateUser,
  identityServiceDeactivateUser,
  identityServiceDeleteUser,
  identityServiceGetAllUsers,
  identityServiceGetCurrentUser,
  identityServiceGetUserById,
  identityServiceGetUsersByRole,
  identityServiceLogin,
  identityServiceRegister,
  identityServiceRequestPasswordReset,
  identityServiceResendVerificationEmail,
  identityServiceResetPassword,
  identityServiceUpdateCurrentUserProfile,
  identityServiceVerifyEmail,
  notificationServiceGetPreferences,
  notificationServiceGetUserDevices,
  notificationServiceRegisterDevice,
  notificationServiceRemoveDevice,
  notificationServiceUpdatePreferences,
  type Options,
  submissionServiceCreateSubmission,
  submissionServiceGetAllSubmissions,
  submissionServiceGetSubmissionById,
  submissionServiceProvideFeedback,
  supportServiceCloseSession,
  supportServiceCreateSession,
  supportServiceGetSessionById,
  supportServiceListSessions,
  supportServiceSendMessage,
} from "../sdk.gen"
import type {
  ContentServiceArchiveAssignmentData,
  ContentServiceArchiveAssignmentError,
  ContentServiceArchiveAssignmentResponse,
  ContentServiceCreateAssignmentData,
  ContentServiceCreateAssignmentError,
  ContentServiceCreateAssignmentResponse,
  ContentServiceCreateSkillData,
  ContentServiceCreateSkillError,
  ContentServiceCreateSkillResponse,
  ContentServiceCreateTutorialData,
  ContentServiceCreateTutorialError,
  ContentServiceCreateTutorialResponse,
  ContentServiceDeleteAssignmentData,
  ContentServiceDeleteAssignmentError,
  ContentServiceDeleteAssignmentResponse,
  ContentServiceDeleteSkillData,
  ContentServiceDeleteSkillError,
  ContentServiceDeleteSkillResponse,
  ContentServiceDeleteTutorialData,
  ContentServiceDeleteTutorialError,
  ContentServiceDeleteTutorialResponse,
  ContentServiceGetAllAssignmentsData,
  ContentServiceGetAllAssignmentsError,
  ContentServiceGetAllAssignmentsResponse,
  ContentServiceGetAllSkillsData,
  ContentServiceGetAllSkillsError,
  ContentServiceGetAllSkillsResponse,
  ContentServiceGetAllTutorialsData,
  ContentServiceGetAllTutorialsError,
  ContentServiceGetAllTutorialsResponse,
  ContentServiceGetAssignmentByIdData,
  ContentServiceGetSkillByIdData,
  ContentServiceGetTutorialByIdData,
  ContentServicePublishAssignmentData,
  ContentServicePublishAssignmentError,
  ContentServicePublishAssignmentResponse,
  ContentServiceUpdateAssignmentData,
  ContentServiceUpdateAssignmentError,
  ContentServiceUpdateAssignmentResponse,
  ContentServiceUpdateAssignmentScheduleData,
  ContentServiceUpdateAssignmentScheduleError,
  ContentServiceUpdateAssignmentScheduleResponse,
  ContentServiceUpdateSkillData,
  ContentServiceUpdateSkillError,
  ContentServiceUpdateSkillResponse,
  ContentServiceUpdateTutorialData,
  ContentServiceUpdateTutorialError,
  ContentServiceUpdateTutorialResponse,
  EvaluationServiceGetSupportedRuntimesData,
  IdentityServiceActivateUserData,
  IdentityServiceActivateUserError,
  IdentityServiceActivateUserResponse,
  IdentityServiceChangePasswordData,
  IdentityServiceChangePasswordError,
  IdentityServiceChangePasswordResponse,
  IdentityServiceCreateUserData,
  IdentityServiceCreateUserError,
  IdentityServiceCreateUserResponse,
  IdentityServiceDeactivateUserData,
  IdentityServiceDeactivateUserError,
  IdentityServiceDeactivateUserResponse,
  IdentityServiceDeleteUserData,
  IdentityServiceDeleteUserError,
  IdentityServiceDeleteUserResponse,
  IdentityServiceGetAllUsersData,
  IdentityServiceGetAllUsersError,
  IdentityServiceGetAllUsersResponse,
  IdentityServiceGetCurrentUserData,
  IdentityServiceGetUserByIdData,
  IdentityServiceGetUsersByRoleData,
  IdentityServiceGetUsersByRoleError,
  IdentityServiceGetUsersByRoleResponse,
  IdentityServiceLoginData,
  IdentityServiceLoginError,
  IdentityServiceLoginResponse,
  IdentityServiceRegisterData,
  IdentityServiceRegisterError,
  IdentityServiceRegisterResponse,
  IdentityServiceRequestPasswordResetData,
  IdentityServiceRequestPasswordResetError,
  IdentityServiceRequestPasswordResetResponse,
  IdentityServiceResendVerificationEmailData,
  IdentityServiceResendVerificationEmailError,
  IdentityServiceResendVerificationEmailResponse,
  IdentityServiceResetPasswordData,
  IdentityServiceResetPasswordError,
  IdentityServiceResetPasswordResponse,
  IdentityServiceUpdateCurrentUserProfileData,
  IdentityServiceUpdateCurrentUserProfileError,
  IdentityServiceUpdateCurrentUserProfileResponse,
  IdentityServiceVerifyEmailData,
  IdentityServiceVerifyEmailError,
  IdentityServiceVerifyEmailResponse,
  NotificationServiceGetPreferencesData,
  NotificationServiceGetUserDevicesData,
  NotificationServiceRegisterDeviceData,
  NotificationServiceRegisterDeviceError,
  NotificationServiceRegisterDeviceResponse,
  NotificationServiceRemoveDeviceData,
  NotificationServiceRemoveDeviceError,
  NotificationServiceRemoveDeviceResponse,
  NotificationServiceUpdatePreferencesData,
  NotificationServiceUpdatePreferencesError,
  NotificationServiceUpdatePreferencesResponse,
  SubmissionServiceCreateSubmissionData,
  SubmissionServiceCreateSubmissionError,
  SubmissionServiceCreateSubmissionResponse,
  SubmissionServiceGetAllSubmissionsData,
  SubmissionServiceGetAllSubmissionsError,
  SubmissionServiceGetAllSubmissionsResponse,
  SubmissionServiceGetSubmissionByIdData,
  SubmissionServiceProvideFeedbackData,
  SubmissionServiceProvideFeedbackError,
  SubmissionServiceProvideFeedbackResponse,
  SupportServiceCloseSessionData,
  SupportServiceCloseSessionError,
  SupportServiceCloseSessionResponse,
  SupportServiceCreateSessionData,
  SupportServiceCreateSessionError,
  SupportServiceCreateSessionResponse,
  SupportServiceGetSessionByIdData,
  SupportServiceListSessionsData,
  SupportServiceListSessionsError,
  SupportServiceListSessionsResponse,
  SupportServiceSendMessageData,
  SupportServiceSendMessageError,
  SupportServiceSendMessageResponse,
} from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const identityServiceGetAllUsersQueryKey = (options?: Options<IdentityServiceGetAllUsersData>) =>
  createQueryKey("identityServiceGetAllUsers", options)

/**
 * Lấy tất cả người dùng
 *
 * Lấy danh sách người dùng có phân trang và sắp xếp (chỉ Admin)
 */
export const identityServiceGetAllUsersOptions = (options?: Options<IdentityServiceGetAllUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await identityServiceGetAllUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: identityServiceGetAllUsersQueryKey(options),
  })
}

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const identityServiceGetAllUsersInfiniteQueryKey = (
  options?: Options<IdentityServiceGetAllUsersData>,
): QueryKey<Options<IdentityServiceGetAllUsersData>> => createQueryKey("identityServiceGetAllUsers", options, true)

/**
 * Lấy tất cả người dùng
 *
 * Lấy danh sách người dùng có phân trang và sắp xếp (chỉ Admin)
 */
export const identityServiceGetAllUsersInfiniteOptions = (options?: Options<IdentityServiceGetAllUsersData>) => {
  return infiniteQueryOptions<
    IdentityServiceGetAllUsersResponse,
    IdentityServiceGetAllUsersError,
    InfiniteData<IdentityServiceGetAllUsersResponse>,
    QueryKey<Options<IdentityServiceGetAllUsersData>>,
    string | Pick<QueryKey<Options<IdentityServiceGetAllUsersData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<IdentityServiceGetAllUsersData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await identityServiceGetAllUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: identityServiceGetAllUsersInfiniteQueryKey(options),
    },
  )
}

/**
 * Tạo người dùng
 *
 * Tạo mới người dùng (chỉ Admin)
 */
export const identityServiceCreateUserMutation = (
  options?: Partial<Options<IdentityServiceCreateUserData>>,
): UseMutationOptions<
  IdentityServiceCreateUserResponse,
  IdentityServiceCreateUserError,
  Options<IdentityServiceCreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceCreateUserResponse,
    IdentityServiceCreateUserError,
    Options<IdentityServiceCreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceCreateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Vô hiệu hóa người dùng
 *
 * Vô hiệu hóa tài khoản người dùng (chỉ Admin)
 */
export const identityServiceDeactivateUserMutation = (
  options?: Partial<Options<IdentityServiceDeactivateUserData>>,
): UseMutationOptions<
  IdentityServiceDeactivateUserResponse,
  IdentityServiceDeactivateUserError,
  Options<IdentityServiceDeactivateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceDeactivateUserResponse,
    IdentityServiceDeactivateUserError,
    Options<IdentityServiceDeactivateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceDeactivateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Kích hoạt người dùng
 *
 * Kích hoạt tài khoản người dùng (chỉ Admin)
 */
export const identityServiceActivateUserMutation = (
  options?: Partial<Options<IdentityServiceActivateUserData>>,
): UseMutationOptions<
  IdentityServiceActivateUserResponse,
  IdentityServiceActivateUserError,
  Options<IdentityServiceActivateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceActivateUserResponse,
    IdentityServiceActivateUserError,
    Options<IdentityServiceActivateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceActivateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Đổi mật khẩu
 *
 * Đổi mật khẩu cho người dùng đang đăng nhập
 */
export const identityServiceChangePasswordMutation = (
  options?: Partial<Options<IdentityServiceChangePasswordData>>,
): UseMutationOptions<
  IdentityServiceChangePasswordResponse,
  IdentityServiceChangePasswordError,
  Options<IdentityServiceChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceChangePasswordResponse,
    IdentityServiceChangePasswordError,
    Options<IdentityServiceChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceChangePassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Xác thực email
 *
 * Xác thực email người dùng bằng mã token
 */
export const identityServiceVerifyEmailMutation = (
  options?: Partial<Options<IdentityServiceVerifyEmailData>>,
): UseMutationOptions<
  IdentityServiceVerifyEmailResponse,
  IdentityServiceVerifyEmailError,
  Options<IdentityServiceVerifyEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceVerifyEmailResponse,
    IdentityServiceVerifyEmailError,
    Options<IdentityServiceVerifyEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceVerifyEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Đặt lại mật khẩu
 *
 * Đặt lại mật khẩu bằng mã token
 */
export const identityServiceResetPasswordMutation = (
  options?: Partial<Options<IdentityServiceResetPasswordData>>,
): UseMutationOptions<
  IdentityServiceResetPasswordResponse,
  IdentityServiceResetPasswordError,
  Options<IdentityServiceResetPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceResetPasswordResponse,
    IdentityServiceResetPasswordError,
    Options<IdentityServiceResetPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceResetPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Gửi lại email xác thực
 *
 * Gửi lại liên kết xác thực email
 */
export const identityServiceResendVerificationEmailMutation = (
  options?: Partial<Options<IdentityServiceResendVerificationEmailData>>,
): UseMutationOptions<
  IdentityServiceResendVerificationEmailResponse,
  IdentityServiceResendVerificationEmailError,
  Options<IdentityServiceResendVerificationEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceResendVerificationEmailResponse,
    IdentityServiceResendVerificationEmailError,
    Options<IdentityServiceResendVerificationEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceResendVerificationEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Đăng ký người dùng mới
 *
 * Đăng ký tài khoản mới với vai trò sinh viên
 */
export const identityServiceRegisterMutation = (
  options?: Partial<Options<IdentityServiceRegisterData>>,
): UseMutationOptions<
  IdentityServiceRegisterResponse,
  IdentityServiceRegisterError,
  Options<IdentityServiceRegisterData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceRegisterResponse,
    IdentityServiceRegisterError,
    Options<IdentityServiceRegisterData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceRegister({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Đăng nhập
 *
 * Xác thực người dùng và trả về JWT token
 */
export const identityServiceLoginMutation = (
  options?: Partial<Options<IdentityServiceLoginData>>,
): UseMutationOptions<IdentityServiceLoginResponse, IdentityServiceLoginError, Options<IdentityServiceLoginData>> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceLoginResponse,
    IdentityServiceLoginError,
    Options<IdentityServiceLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Yêu cầu đặt lại mật khẩu
 *
 * Yêu cầu gửi liên kết đặt lại mật khẩu qua email
 */
export const identityServiceRequestPasswordResetMutation = (
  options?: Partial<Options<IdentityServiceRequestPasswordResetData>>,
): UseMutationOptions<
  IdentityServiceRequestPasswordResetResponse,
  IdentityServiceRequestPasswordResetError,
  Options<IdentityServiceRequestPasswordResetData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceRequestPasswordResetResponse,
    IdentityServiceRequestPasswordResetError,
    Options<IdentityServiceRequestPasswordResetData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceRequestPasswordReset({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const identityServiceGetCurrentUserQueryKey = (options?: Options<IdentityServiceGetCurrentUserData>) =>
  createQueryKey("identityServiceGetCurrentUser", options)

/**
 * Lấy hồ sơ người dùng hiện tại
 *
 * Lấy thông tin hồ sơ của người dùng đang đăng nhập
 */
export const identityServiceGetCurrentUserOptions = (options?: Options<IdentityServiceGetCurrentUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await identityServiceGetCurrentUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: identityServiceGetCurrentUserQueryKey(options),
  })
}

/**
 * Cập nhật hồ sơ người dùng
 *
 * Cập nhật thông tin hồ sơ của người dùng đang đăng nhập
 */
export const identityServiceUpdateCurrentUserProfileMutation = (
  options?: Partial<Options<IdentityServiceUpdateCurrentUserProfileData>>,
): UseMutationOptions<
  IdentityServiceUpdateCurrentUserProfileResponse,
  IdentityServiceUpdateCurrentUserProfileError,
  Options<IdentityServiceUpdateCurrentUserProfileData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceUpdateCurrentUserProfileResponse,
    IdentityServiceUpdateCurrentUserProfileError,
    Options<IdentityServiceUpdateCurrentUserProfileData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceUpdateCurrentUserProfile({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Xóa người dùng
 *
 * Xóa tài khoản người dùng (chỉ Admin)
 */
export const identityServiceDeleteUserMutation = (
  options?: Partial<Options<IdentityServiceDeleteUserData>>,
): UseMutationOptions<
  IdentityServiceDeleteUserResponse,
  IdentityServiceDeleteUserError,
  Options<IdentityServiceDeleteUserData>
> => {
  const mutationOptions: UseMutationOptions<
    IdentityServiceDeleteUserResponse,
    IdentityServiceDeleteUserError,
    Options<IdentityServiceDeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await identityServiceDeleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const identityServiceGetUserByIdQueryKey = (options: Options<IdentityServiceGetUserByIdData>) =>
  createQueryKey("identityServiceGetUserById", options)

/**
 * Lấy người dùng theo ID
 *
 * Lấy thông tin người dùng theo ID (chỉ Admin và Giảng viên)
 */
export const identityServiceGetUserByIdOptions = (options: Options<IdentityServiceGetUserByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await identityServiceGetUserById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: identityServiceGetUserByIdQueryKey(options),
  })
}

export const identityServiceGetUsersByRoleQueryKey = (options: Options<IdentityServiceGetUsersByRoleData>) =>
  createQueryKey("identityServiceGetUsersByRole", options)

/**
 * Lấy người dùng theo vai trò
 *
 * Lấy danh sách người dùng theo vai trò có phân trang và sắp xếp (chỉ Admin và Giảng viên)
 */
export const identityServiceGetUsersByRoleOptions = (options: Options<IdentityServiceGetUsersByRoleData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await identityServiceGetUsersByRole({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: identityServiceGetUsersByRoleQueryKey(options),
  })
}

export const identityServiceGetUsersByRoleInfiniteQueryKey = (
  options: Options<IdentityServiceGetUsersByRoleData>,
): QueryKey<Options<IdentityServiceGetUsersByRoleData>> =>
  createQueryKey("identityServiceGetUsersByRole", options, true)

/**
 * Lấy người dùng theo vai trò
 *
 * Lấy danh sách người dùng theo vai trò có phân trang và sắp xếp (chỉ Admin và Giảng viên)
 */
export const identityServiceGetUsersByRoleInfiniteOptions = (options: Options<IdentityServiceGetUsersByRoleData>) => {
  return infiniteQueryOptions<
    IdentityServiceGetUsersByRoleResponse,
    IdentityServiceGetUsersByRoleError,
    InfiniteData<IdentityServiceGetUsersByRoleResponse>,
    QueryKey<Options<IdentityServiceGetUsersByRoleData>>,
    string | Pick<QueryKey<Options<IdentityServiceGetUsersByRoleData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<IdentityServiceGetUsersByRoleData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await identityServiceGetUsersByRole({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: identityServiceGetUsersByRoleInfiniteQueryKey(options),
    },
  )
}

export const contentServiceGetAllTutorialsQueryKey = (options?: Options<ContentServiceGetAllTutorialsData>) =>
  createQueryKey("contentServiceGetAllTutorials", options)

/**
 * Lấy tất cả hướng dẫn
 *
 * Lấy danh sách hướng dẫn có phân trang và sắp xếp
 */
export const contentServiceGetAllTutorialsOptions = (options?: Options<ContentServiceGetAllTutorialsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetAllTutorials({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetAllTutorialsQueryKey(options),
  })
}

export const contentServiceGetAllTutorialsInfiniteQueryKey = (
  options?: Options<ContentServiceGetAllTutorialsData>,
): QueryKey<Options<ContentServiceGetAllTutorialsData>> =>
  createQueryKey("contentServiceGetAllTutorials", options, true)

/**
 * Lấy tất cả hướng dẫn
 *
 * Lấy danh sách hướng dẫn có phân trang và sắp xếp
 */
export const contentServiceGetAllTutorialsInfiniteOptions = (options?: Options<ContentServiceGetAllTutorialsData>) => {
  return infiniteQueryOptions<
    ContentServiceGetAllTutorialsResponse,
    ContentServiceGetAllTutorialsError,
    InfiniteData<ContentServiceGetAllTutorialsResponse>,
    QueryKey<Options<ContentServiceGetAllTutorialsData>>,
    string | Pick<QueryKey<Options<ContentServiceGetAllTutorialsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ContentServiceGetAllTutorialsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await contentServiceGetAllTutorials({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: contentServiceGetAllTutorialsInfiniteQueryKey(options),
    },
  )
}

/**
 * Tạo hướng dẫn mới
 *
 * Tạo mới hướng dẫn (chỉ Content Provider)
 */
export const contentServiceCreateTutorialMutation = (
  options?: Partial<Options<ContentServiceCreateTutorialData>>,
): UseMutationOptions<
  ContentServiceCreateTutorialResponse,
  ContentServiceCreateTutorialError,
  Options<ContentServiceCreateTutorialData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceCreateTutorialResponse,
    ContentServiceCreateTutorialError,
    Options<ContentServiceCreateTutorialData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceCreateTutorial({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetAllSkillsQueryKey = (options?: Options<ContentServiceGetAllSkillsData>) =>
  createQueryKey("contentServiceGetAllSkills", options)

/**
 * Lấy tất cả kỹ năng
 *
 * Lấy danh sách kỹ năng có phân trang và sắp xếp
 */
export const contentServiceGetAllSkillsOptions = (options?: Options<ContentServiceGetAllSkillsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetAllSkills({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetAllSkillsQueryKey(options),
  })
}

export const contentServiceGetAllSkillsInfiniteQueryKey = (
  options?: Options<ContentServiceGetAllSkillsData>,
): QueryKey<Options<ContentServiceGetAllSkillsData>> => createQueryKey("contentServiceGetAllSkills", options, true)

/**
 * Lấy tất cả kỹ năng
 *
 * Lấy danh sách kỹ năng có phân trang và sắp xếp
 */
export const contentServiceGetAllSkillsInfiniteOptions = (options?: Options<ContentServiceGetAllSkillsData>) => {
  return infiniteQueryOptions<
    ContentServiceGetAllSkillsResponse,
    ContentServiceGetAllSkillsError,
    InfiniteData<ContentServiceGetAllSkillsResponse>,
    QueryKey<Options<ContentServiceGetAllSkillsData>>,
    string | Pick<QueryKey<Options<ContentServiceGetAllSkillsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ContentServiceGetAllSkillsData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await contentServiceGetAllSkills({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: contentServiceGetAllSkillsInfiniteQueryKey(options),
    },
  )
}

/**
 * Tạo kỹ năng mới
 *
 * Tạo mới kỹ năng (chỉ Content Provider)
 */
export const contentServiceCreateSkillMutation = (
  options?: Partial<Options<ContentServiceCreateSkillData>>,
): UseMutationOptions<
  ContentServiceCreateSkillResponse,
  ContentServiceCreateSkillError,
  Options<ContentServiceCreateSkillData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceCreateSkillResponse,
    ContentServiceCreateSkillError,
    Options<ContentServiceCreateSkillData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceCreateSkill({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetAllAssignmentsQueryKey = (options?: Options<ContentServiceGetAllAssignmentsData>) =>
  createQueryKey("contentServiceGetAllAssignments", options)

/**
 * Lấy tất cả bài tập
 *
 * Lấy danh sách bài tập có phân trang và sắp xếp
 */
export const contentServiceGetAllAssignmentsOptions = (options?: Options<ContentServiceGetAllAssignmentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetAllAssignments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetAllAssignmentsQueryKey(options),
  })
}

export const contentServiceGetAllAssignmentsInfiniteQueryKey = (
  options?: Options<ContentServiceGetAllAssignmentsData>,
): QueryKey<Options<ContentServiceGetAllAssignmentsData>> =>
  createQueryKey("contentServiceGetAllAssignments", options, true)

/**
 * Lấy tất cả bài tập
 *
 * Lấy danh sách bài tập có phân trang và sắp xếp
 */
export const contentServiceGetAllAssignmentsInfiniteOptions = (
  options?: Options<ContentServiceGetAllAssignmentsData>,
) => {
  return infiniteQueryOptions<
    ContentServiceGetAllAssignmentsResponse,
    ContentServiceGetAllAssignmentsError,
    InfiniteData<ContentServiceGetAllAssignmentsResponse>,
    QueryKey<Options<ContentServiceGetAllAssignmentsData>>,
    string | Pick<QueryKey<Options<ContentServiceGetAllAssignmentsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ContentServiceGetAllAssignmentsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await contentServiceGetAllAssignments({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: contentServiceGetAllAssignmentsInfiniteQueryKey(options),
    },
  )
}

/**
 * Tạo bài tập mới
 *
 * Tạo mới bài tập (chỉ Content Provider)
 */
export const contentServiceCreateAssignmentMutation = (
  options?: Partial<Options<ContentServiceCreateAssignmentData>>,
): UseMutationOptions<
  ContentServiceCreateAssignmentResponse,
  ContentServiceCreateAssignmentError,
  Options<ContentServiceCreateAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceCreateAssignmentResponse,
    ContentServiceCreateAssignmentError,
    Options<ContentServiceCreateAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceCreateAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Xuất bản bài tập
 *
 * Xuất bản bài tập nháp (chỉ Content Provider)
 */
export const contentServicePublishAssignmentMutation = (
  options?: Partial<Options<ContentServicePublishAssignmentData>>,
): UseMutationOptions<
  ContentServicePublishAssignmentResponse,
  ContentServicePublishAssignmentError,
  Options<ContentServicePublishAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServicePublishAssignmentResponse,
    ContentServicePublishAssignmentError,
    Options<ContentServicePublishAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServicePublishAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Lưu trữ bài tập
 *
 * Lưu trữ bài tập (chỉ Content Provider)
 */
export const contentServiceArchiveAssignmentMutation = (
  options?: Partial<Options<ContentServiceArchiveAssignmentData>>,
): UseMutationOptions<
  ContentServiceArchiveAssignmentResponse,
  ContentServiceArchiveAssignmentError,
  Options<ContentServiceArchiveAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceArchiveAssignmentResponse,
    ContentServiceArchiveAssignmentError,
    Options<ContentServiceArchiveAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceArchiveAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Xóa hướng dẫn
 *
 * Xóa hướng dẫn (chỉ Content Provider)
 */
export const contentServiceDeleteTutorialMutation = (
  options?: Partial<Options<ContentServiceDeleteTutorialData>>,
): UseMutationOptions<
  ContentServiceDeleteTutorialResponse,
  ContentServiceDeleteTutorialError,
  Options<ContentServiceDeleteTutorialData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceDeleteTutorialResponse,
    ContentServiceDeleteTutorialError,
    Options<ContentServiceDeleteTutorialData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceDeleteTutorial({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetTutorialByIdQueryKey = (options: Options<ContentServiceGetTutorialByIdData>) =>
  createQueryKey("contentServiceGetTutorialById", options)

/**
 * Lấy hướng dẫn theo ID
 *
 * Lấy chi tiết hướng dẫn theo ID
 */
export const contentServiceGetTutorialByIdOptions = (options: Options<ContentServiceGetTutorialByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetTutorialById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetTutorialByIdQueryKey(options),
  })
}

/**
 * Cập nhật hướng dẫn
 *
 * Cập nhật thông tin hướng dẫn (chỉ Content Provider)
 */
export const contentServiceUpdateTutorialMutation = (
  options?: Partial<Options<ContentServiceUpdateTutorialData>>,
): UseMutationOptions<
  ContentServiceUpdateTutorialResponse,
  ContentServiceUpdateTutorialError,
  Options<ContentServiceUpdateTutorialData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceUpdateTutorialResponse,
    ContentServiceUpdateTutorialError,
    Options<ContentServiceUpdateTutorialData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceUpdateTutorial({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Xóa kỹ năng
 *
 * Xóa kỹ năng (chỉ Content Provider)
 */
export const contentServiceDeleteSkillMutation = (
  options?: Partial<Options<ContentServiceDeleteSkillData>>,
): UseMutationOptions<
  ContentServiceDeleteSkillResponse,
  ContentServiceDeleteSkillError,
  Options<ContentServiceDeleteSkillData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceDeleteSkillResponse,
    ContentServiceDeleteSkillError,
    Options<ContentServiceDeleteSkillData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceDeleteSkill({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetSkillByIdQueryKey = (options: Options<ContentServiceGetSkillByIdData>) =>
  createQueryKey("contentServiceGetSkillById", options)

/**
 * Lấy kỹ năng theo ID
 *
 * Lấy chi tiết kỹ năng theo ID
 */
export const contentServiceGetSkillByIdOptions = (options: Options<ContentServiceGetSkillByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetSkillById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetSkillByIdQueryKey(options),
  })
}

/**
 * Cập nhật kỹ năng
 *
 * Cập nhật thông tin kỹ năng (chỉ Content Provider)
 */
export const contentServiceUpdateSkillMutation = (
  options?: Partial<Options<ContentServiceUpdateSkillData>>,
): UseMutationOptions<
  ContentServiceUpdateSkillResponse,
  ContentServiceUpdateSkillError,
  Options<ContentServiceUpdateSkillData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceUpdateSkillResponse,
    ContentServiceUpdateSkillError,
    Options<ContentServiceUpdateSkillData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceUpdateSkill({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Xóa bài tập
 *
 * Xóa bài tập (chỉ Content Provider)
 */
export const contentServiceDeleteAssignmentMutation = (
  options?: Partial<Options<ContentServiceDeleteAssignmentData>>,
): UseMutationOptions<
  ContentServiceDeleteAssignmentResponse,
  ContentServiceDeleteAssignmentError,
  Options<ContentServiceDeleteAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceDeleteAssignmentResponse,
    ContentServiceDeleteAssignmentError,
    Options<ContentServiceDeleteAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceDeleteAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const contentServiceGetAssignmentByIdQueryKey = (options: Options<ContentServiceGetAssignmentByIdData>) =>
  createQueryKey("contentServiceGetAssignmentById", options)

/**
 * Lấy bài tập theo ID
 *
 * Lấy chi tiết bài tập theo ID
 */
export const contentServiceGetAssignmentByIdOptions = (options: Options<ContentServiceGetAssignmentByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await contentServiceGetAssignmentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: contentServiceGetAssignmentByIdQueryKey(options),
  })
}

/**
 * Cập nhật bài tập
 *
 * Cập nhật thông tin bài tập (chỉ Content Provider)
 */
export const contentServiceUpdateAssignmentMutation = (
  options?: Partial<Options<ContentServiceUpdateAssignmentData>>,
): UseMutationOptions<
  ContentServiceUpdateAssignmentResponse,
  ContentServiceUpdateAssignmentError,
  Options<ContentServiceUpdateAssignmentData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceUpdateAssignmentResponse,
    ContentServiceUpdateAssignmentError,
    Options<ContentServiceUpdateAssignmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceUpdateAssignment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Cập nhật lịch bài tập
 *
 * Cập nhật lịch bài tập (start_date, due_date) (chỉ Giảng viên)
 */
export const contentServiceUpdateAssignmentScheduleMutation = (
  options?: Partial<Options<ContentServiceUpdateAssignmentScheduleData>>,
): UseMutationOptions<
  ContentServiceUpdateAssignmentScheduleResponse,
  ContentServiceUpdateAssignmentScheduleError,
  Options<ContentServiceUpdateAssignmentScheduleData>
> => {
  const mutationOptions: UseMutationOptions<
    ContentServiceUpdateAssignmentScheduleResponse,
    ContentServiceUpdateAssignmentScheduleError,
    Options<ContentServiceUpdateAssignmentScheduleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await contentServiceUpdateAssignmentSchedule({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const submissionServiceGetAllSubmissionsQueryKey = (options?: Options<SubmissionServiceGetAllSubmissionsData>) =>
  createQueryKey("submissionServiceGetAllSubmissions", options)

/**
 * Lấy tất cả bài nộp
 *
 * Lấy danh sách bài nộp với phân trang và sắp xếp. Sinh viên chỉ xem bài của mình, giảng viên có thể lọc theo bài tập và sinh viên.
 */
export const submissionServiceGetAllSubmissionsOptions = (
  options?: Options<SubmissionServiceGetAllSubmissionsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await submissionServiceGetAllSubmissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: submissionServiceGetAllSubmissionsQueryKey(options),
  })
}

export const submissionServiceGetAllSubmissionsInfiniteQueryKey = (
  options?: Options<SubmissionServiceGetAllSubmissionsData>,
): QueryKey<Options<SubmissionServiceGetAllSubmissionsData>> =>
  createQueryKey("submissionServiceGetAllSubmissions", options, true)

/**
 * Lấy tất cả bài nộp
 *
 * Lấy danh sách bài nộp với phân trang và sắp xếp. Sinh viên chỉ xem bài của mình, giảng viên có thể lọc theo bài tập và sinh viên.
 */
export const submissionServiceGetAllSubmissionsInfiniteOptions = (
  options?: Options<SubmissionServiceGetAllSubmissionsData>,
) => {
  return infiniteQueryOptions<
    SubmissionServiceGetAllSubmissionsResponse,
    SubmissionServiceGetAllSubmissionsError,
    InfiniteData<SubmissionServiceGetAllSubmissionsResponse>,
    QueryKey<Options<SubmissionServiceGetAllSubmissionsData>>,
    string | Pick<QueryKey<Options<SubmissionServiceGetAllSubmissionsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<SubmissionServiceGetAllSubmissionsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await submissionServiceGetAllSubmissions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: submissionServiceGetAllSubmissionsInfiniteQueryKey(options),
    },
  )
}

/**
 * Tạo bài nộp mới
 *
 * Nộp bài giải cho một bài tập (chỉ sinh viên)
 */
export const submissionServiceCreateSubmissionMutation = (
  options?: Partial<Options<SubmissionServiceCreateSubmissionData>>,
): UseMutationOptions<
  SubmissionServiceCreateSubmissionResponse,
  SubmissionServiceCreateSubmissionError,
  Options<SubmissionServiceCreateSubmissionData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmissionServiceCreateSubmissionResponse,
    SubmissionServiceCreateSubmissionError,
    Options<SubmissionServiceCreateSubmissionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await submissionServiceCreateSubmission({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Thêm nhận xét cho bài nộp
 *
 * Thêm nhận xét của giảng viên cho bài nộp (chỉ giảng viên)
 */
export const submissionServiceProvideFeedbackMutation = (
  options?: Partial<Options<SubmissionServiceProvideFeedbackData>>,
): UseMutationOptions<
  SubmissionServiceProvideFeedbackResponse,
  SubmissionServiceProvideFeedbackError,
  Options<SubmissionServiceProvideFeedbackData>
> => {
  const mutationOptions: UseMutationOptions<
    SubmissionServiceProvideFeedbackResponse,
    SubmissionServiceProvideFeedbackError,
    Options<SubmissionServiceProvideFeedbackData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await submissionServiceProvideFeedback({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const submissionServiceGetSubmissionByIdQueryKey = (options: Options<SubmissionServiceGetSubmissionByIdData>) =>
  createQueryKey("submissionServiceGetSubmissionById", options)

/**
 * Lấy bài nộp theo ID
 *
 * Lấy chi tiết bài nộp theo ID. Sinh viên chỉ xem bài của mình, giảng viên xem được tất cả.
 */
export const submissionServiceGetSubmissionByIdOptions = (options: Options<SubmissionServiceGetSubmissionByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await submissionServiceGetSubmissionById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: submissionServiceGetSubmissionByIdQueryKey(options),
  })
}

export const evaluationServiceGetSupportedRuntimesQueryKey = (
  options?: Options<EvaluationServiceGetSupportedRuntimesData>,
) => createQueryKey("evaluationServiceGetSupportedRuntimes", options)

/**
 * Lấy danh sách runtime hỗ trợ
 *
 * Trả về danh sách tất cả ngôn ngữ lập trình và phiên bản được hỗ trợ
 */
export const evaluationServiceGetSupportedRuntimesOptions = (
  options?: Options<EvaluationServiceGetSupportedRuntimesData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await evaluationServiceGetSupportedRuntimes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: evaluationServiceGetSupportedRuntimesQueryKey(options),
  })
}

export const supportServiceListSessionsQueryKey = (options?: Options<SupportServiceListSessionsData>) =>
  createQueryKey("supportServiceListSessions", options)

/**
 * Liệt kê các phiên hỗ trợ
 *
 * Giảng viên xem tất cả phiên, sinh viên chỉ xem phiên của mình
 */
export const supportServiceListSessionsOptions = (options?: Options<SupportServiceListSessionsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await supportServiceListSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: supportServiceListSessionsQueryKey(options),
  })
}

export const supportServiceListSessionsInfiniteQueryKey = (
  options?: Options<SupportServiceListSessionsData>,
): QueryKey<Options<SupportServiceListSessionsData>> => createQueryKey("supportServiceListSessions", options, true)

/**
 * Liệt kê các phiên hỗ trợ
 *
 * Giảng viên xem tất cả phiên, sinh viên chỉ xem phiên của mình
 */
export const supportServiceListSessionsInfiniteOptions = (options?: Options<SupportServiceListSessionsData>) => {
  return infiniteQueryOptions<
    SupportServiceListSessionsResponse,
    SupportServiceListSessionsError,
    InfiniteData<SupportServiceListSessionsResponse>,
    QueryKey<Options<SupportServiceListSessionsData>>,
    string | Pick<QueryKey<Options<SupportServiceListSessionsData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<SupportServiceListSessionsData>>[0], "body" | "headers" | "path" | "query"> =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await supportServiceListSessions({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: supportServiceListSessionsInfiniteQueryKey(options),
    },
  )
}

/**
 * Tạo phiên hỗ trợ mới
 *
 * Sinh viên có thể tạo phiên hỗ trợ mới
 */
export const supportServiceCreateSessionMutation = (
  options?: Partial<Options<SupportServiceCreateSessionData>>,
): UseMutationOptions<
  SupportServiceCreateSessionResponse,
  SupportServiceCreateSessionError,
  Options<SupportServiceCreateSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    SupportServiceCreateSessionResponse,
    SupportServiceCreateSessionError,
    Options<SupportServiceCreateSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await supportServiceCreateSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Gửi tin nhắn trong phiên hỗ trợ
 *
 * Gửi tin nhắn trong một phiên hỗ trợ
 */
export const supportServiceSendMessageMutation = (
  options?: Partial<Options<SupportServiceSendMessageData>>,
): UseMutationOptions<
  SupportServiceSendMessageResponse,
  SupportServiceSendMessageError,
  Options<SupportServiceSendMessageData>
> => {
  const mutationOptions: UseMutationOptions<
    SupportServiceSendMessageResponse,
    SupportServiceSendMessageError,
    Options<SupportServiceSendMessageData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await supportServiceSendMessage({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Đóng phiên hỗ trợ
 *
 * Chỉ sinh viên tạo phiên mới được đóng phiên
 */
export const supportServiceCloseSessionMutation = (
  options?: Partial<Options<SupportServiceCloseSessionData>>,
): UseMutationOptions<
  SupportServiceCloseSessionResponse,
  SupportServiceCloseSessionError,
  Options<SupportServiceCloseSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    SupportServiceCloseSessionResponse,
    SupportServiceCloseSessionError,
    Options<SupportServiceCloseSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await supportServiceCloseSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const supportServiceGetSessionByIdQueryKey = (options: Options<SupportServiceGetSessionByIdData>) =>
  createQueryKey("supportServiceGetSessionById", options)

/**
 * Xem chi tiết phiên hỗ trợ
 *
 * Giảng viên xem mọi phiên, sinh viên chỉ xem phiên của mình
 */
export const supportServiceGetSessionByIdOptions = (options: Options<SupportServiceGetSessionByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await supportServiceGetSessionById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: supportServiceGetSessionByIdQueryKey(options),
  })
}

/**
 * Đăng ký token thiết bị FCM
 *
 * Đăng ký token thiết bị Firebase Cloud Messaging để nhận thông báo đẩy
 */
export const notificationServiceRegisterDeviceMutation = (
  options?: Partial<Options<NotificationServiceRegisterDeviceData>>,
): UseMutationOptions<
  NotificationServiceRegisterDeviceResponse,
  NotificationServiceRegisterDeviceError,
  Options<NotificationServiceRegisterDeviceData>
> => {
  const mutationOptions: UseMutationOptions<
    NotificationServiceRegisterDeviceResponse,
    NotificationServiceRegisterDeviceError,
    Options<NotificationServiceRegisterDeviceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await notificationServiceRegisterDevice({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const notificationServiceGetPreferencesQueryKey = (options?: Options<NotificationServiceGetPreferencesData>) =>
  createQueryKey("notificationServiceGetPreferences", options)

/**
 * Lấy tùy chọn thông báo
 *
 * Lấy tùy chọn nhận thông báo của người dùng hiện tại
 */
export const notificationServiceGetPreferencesOptions = (options?: Options<NotificationServiceGetPreferencesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await notificationServiceGetPreferences({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: notificationServiceGetPreferencesQueryKey(options),
  })
}

/**
 * Cập nhật tùy chọn thông báo
 *
 * Cập nhật tùy chọn nhận thông báo của người dùng hiện tại
 */
export const notificationServiceUpdatePreferencesMutation = (
  options?: Partial<Options<NotificationServiceUpdatePreferencesData>>,
): UseMutationOptions<
  NotificationServiceUpdatePreferencesResponse,
  NotificationServiceUpdatePreferencesError,
  Options<NotificationServiceUpdatePreferencesData>
> => {
  const mutationOptions: UseMutationOptions<
    NotificationServiceUpdatePreferencesResponse,
    NotificationServiceUpdatePreferencesError,
    Options<NotificationServiceUpdatePreferencesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await notificationServiceUpdatePreferences({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const notificationServiceGetUserDevicesQueryKey = (options?: Options<NotificationServiceGetUserDevicesData>) =>
  createQueryKey("notificationServiceGetUserDevices", options)

/**
 * Lấy danh sách thiết bị
 *
 * Lấy tất cả thiết bị đã đăng ký của người dùng hiện tại
 */
export const notificationServiceGetUserDevicesOptions = (options?: Options<NotificationServiceGetUserDevicesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await notificationServiceGetUserDevices({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: notificationServiceGetUserDevicesQueryKey(options),
  })
}

/**
 * Xóa token thiết bị
 *
 * Xóa token thiết bị FCM đã đăng ký
 */
export const notificationServiceRemoveDeviceMutation = (
  options?: Partial<Options<NotificationServiceRemoveDeviceData>>,
): UseMutationOptions<
  NotificationServiceRemoveDeviceResponse,
  NotificationServiceRemoveDeviceError,
  Options<NotificationServiceRemoveDeviceData>
> => {
  const mutationOptions: UseMutationOptions<
    NotificationServiceRemoveDeviceResponse,
    NotificationServiceRemoveDeviceError,
    Options<NotificationServiceRemoveDeviceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await notificationServiceRemoveDevice({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
